Add theta, phi and r attributes to Vector3d, plus Vector3d.to_polar()
pyxem/orix pull request #116
Opened 2020-08-26 14:04 UTC by hakonanes

Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

See #115 for brief motivation.

* Add derived `Vector3d.theta`, `Vector3d.phi` and `Vector3d.r` attributes.
* Add `Vector3d.to_polar()` method to return `theta`, `phi` and `r`. The method takes no parameters.

Written simple tests, which pass. Coverage remains at 100%.

@pc494, very you thinking of a `polar()` function defined outside of `Vector3d`, so this could be used elsewhere? If so, where do you think this should be placed?

2020-08-26 15:29 UTC, pc494 commented
In the short term I prefer `Scalar`, it's architecturally consistent even is Scalar as a class has always seemed a bit shallow in orix. I don't think we need to abstract `polar` just yet, for example if you got axes (from axis-angle rep) they would already be Vector3D. Review coming up.

2020-08-26 15:33 UTC, pc494 requested changes
Conventions and docstrings, I think we are using "ISO 31-11" - see https://mathworld.wolfram.com/SphericalCoordinates.html

2020-08-26 15:33 UTC, pc494 commented on orix/vector/vector3d.py
> +    def theta(self):
can we have a one liner describing convention here please?

2020-08-26 15:33 UTC, pc494 commented on orix/vector/vector3d.py
> +    def phi(self):
same again, just be clear which angle we are using

2020-08-26 15:33 UTC, pc494 commented on orix/vector/vector3d.py
> +    def to_polar(self):
I know we've not always been consistent, but this should have normal method docstrings, especially as it's returning 3 separate things, and it's not obvious that the order would be what it is.

2020-08-27 10:16 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def theta(self):
Added a bit more than a oneliner... Please say so if you think it is too much.

2020-08-27 10:18 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def to_polar(self):
Now returns `Scalar`. This lead to e.g. me having to add the `.data` when feeding coordinates back into `Vector3d.to_polar()`, which should be unnecessary:

```python
    def test_polar_loop(self, vector):
        theta, phi, r = vector.to_polar()
        vector2 = Vector3d.from_polar(theta=theta.data, phi=phi.data, r=r.data)
        assert np.allclose(vector.data, vector2.data)
```

Either `Vector3d.from_polar()` should accept `Scalar`, or we should stop using it.

2020-08-27 12:16 UTC, pc494 approved these changes

2020-08-27 12:16 UTC, pc494 commented on orix/vector/vector3d.py
> +    def to_polar(self):
I actually don't mind this as is, I've got quiet used (from hyperspy) to `.data` whenever I'm expecting numpy arrays and the "test loop case" is an edge case in day to day usage. If you @hakonanes are okay with leaving it as it is, this is good to go

2020-08-27 12:28 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def to_polar(self):
I'm fine with this now.

I agree that accessing .data is simple and not at all a user barrier. `Scalar` might make some internal tasks/logic simpler, I don't know, it's just that I've yet to encounter a situation where I need `Scalar`.

2020-08-27 12:49 UTC, pc494 commented
Merging, we scan (and probably should) consider `Scalar`'s place within `orix` at a future point

2020-08-27 12:50 UTC, merged