Add Vector3d.get_circle() and StereographicPlot.circle() methods
pyxem/orix pull request #158
Opened 2021-02-18 17:12 UTC by hakonanes

Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
* Add `Vector3d.get_circle(opening_angle=0.5 * np.pi, steps=100)` method to get great or small circles (depending on the opening angle, by default a great circle) about the vectors in the `Vector3d` instance. The output are a set of `steps` vectors delineating the circle per vector in the instance in its own `Vector3d` instance of shape `(n, steps)`, no matter the shape of the `Vector3d` to get circles from.
* Add `StereographicPlot.circle(*args, opening_angle=0.5 * np.pi, **kwargs)` method to draw these circles in the stereographic projection.
* Add better annotation of vectors in stereographic plots.

#### Progress of the PR
- [ ] Annotation of vectors
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
This updated code snippet from the stereographic projection user guide notebook

```python
import matplotlib.pyplot as plt
import numpy as np 
from orix import plot, vector

fig, ax = plt.subplots(ncols=2, subplot_kw=dict(projection="stereographic"))

marker_size = 500
ax[0].grid(False)
# 4-fold (outer markers will be clipped a bit...)
v4fold = vector.Vector3d(
    [[0, 0, 1], [1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0]]
)
ax[0].symmetry_marker(v4fold, fold=4, c="C4", s=marker_size)
ax[0].circle(v4fold, c="C4")
# 3-fold
v3fold = vector.Vector3d([[1, 1, 1], [1, -1, 1], [-1, -1, 1], [-1, 1, 1]])
ax[0].symmetry_marker(v3fold, fold=3, c="C3", s=marker_size)
ax[0].circle(v3fold, c="C3")
# 2-fold
v2fold = vector.Vector3d([
    [1, 0, 1],
    [0, 1, 1],
    [-1, 0, 1],
    [0, -1, 1],
    [1, 1, 0],
    [-1, -1, 0],
    [-1, 1, 0],
    [1, -1, 0],
])
ax[0].symmetry_marker(v2fold, fold=2, c="C2", s=marker_size)
ax[0].circle(v2fold, c="C2")

ax[1].grid(True)
v = vector.Vector3d([[0, 1, 1], [1, 0, 1], [0, -1, 1], [-1, 0, 1]])
ax[1].scatter(v, c=["C0", "C1", "C2", "C3"])
ax[1].circle(v, opening_angle=0.25 * np.pi)
```

produces this figure

![great_small_circles](https://user-images.githubusercontent.com/12139781/108394139-b0706380-7214-11eb-855e-8b399b7ddd8a.png)

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-03-04 21:36 UTC, hakonanes commented
@din14970, I would be greatful if you could have a quick look at the final notebook updates in the PR built docs. I removed the `Vector3d.figure` attribute, as it was too much work keeping track of it when building upon the current figure... I instead opted for the solution you suggested, by providing a `return_figure` parameter, and a `figure` parameter to pass it to.

2021-03-05 10:10 UTC, din14970 commented
looks very cool! I think it looks fine. As I wrote in the issue, I'm never totally sure how to best handle these matplotlib objects, so I guess this way has advantages but the old way might also have advantages. I guess if it ends up feeling unnatural it can be changed at a later point.

2021-03-05 11:03 UTC, hakonanes commented
Yeah, Matplotlib's highly customizable object oriented functionality means it might be confusing sometimes. But I think the approach of returning a figure if the user want's it, and then passing it on to build upon that figure later, is simple and intuitive, and also way easier to maintain...

2021-03-05 13:37 UTC, pc494 requested changes
I've not yet reviewed vector3d.py or test_vector3d.py ~ the functionality looks excellent, just got a couple of syntax questions to try and keep the code noise down, as my experience debugging stuff like this at a later suggests clarity is very important. Will hopefully have a finished review by the end of today.

2021-03-05 13:37 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    def draw_circle(self, *args, opening_angle=0.5 * np.pi, steps=100, **kwargs):
think `np.pi/2` is easy to read as the default parameter

2021-03-05 13:37 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    # Elements' zorder (let's try to keep this updated!):
This could be done via dictionary mapping at a later point (rather than hardcoding the numbers), although that change isn't for this PR

2021-03-05 13:37 UTC, pc494 commented on orix/plot/stereographic_plot.py
>          if len(values) == 2:
I feel like there is an edge case that will slip past this. The duck typing is fine, but are we sure we can't get a `Vector3D` object with a `len == 2`. Similarly, do we want a np.array of the correction dimensions to throw an error.

Does
```python
try:
    value = value.unit
    azimuth = value.azimuth.data
    polar = value.polar.data
except (AttributeError):
    try:
         azimuth,polar = values[0],values[1]
    except IndexError:
         raise ValueError(...)
```
help this? Leaving at your discretion.

2021-03-05 13:37 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +        value = [value,] * n
Too much logic going on here for my taste. Would pull the len(value)!=n block out at the top to get:

```
if len(value) == n:
      return value
```

Then the `value = value[0] ` block is for non-strings, that I understand. But will anything that doesn't have an __iter__ have a __len__ (needed above)? If not I think you can drop "__iter__" bits of code, but let me see what else we have.

I should probably read the test cases before I write more here.

2021-03-05 13:37 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    indices = np.where(visible != visible[0])[0]
This is hard to read, also consider from the docstrings of np.where()

```
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.
```

Also, taking the zeroth element from this confused me...

2021-03-05 13:37 UTC, pc494 commented on orix/tests/test_stereographic_plot.py
> +        assert np.allclose(polar_out, desired_polar)
Not sure this will catch the behaviour I was talking about earlier. Could you expand on the why we shift the order around for this bit of code?

2021-03-05 13:39 UTC, pc494 commented
(also my bad, I thought I had been pinged for a review here, apparently not...)

2021-03-05 14:08 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        value = [value,] * n
I plan to mainly use that function to create an array of colors and sizes per vectors so that these can be iterated over together with the vectors in e.g. `StereographicPlot.draw_circle()`. Matplotlib singles out colors and sizes as scatter point and line styles that can be iterables, all other arguments are fixed for all scatter points and lines. In many cases, `value` is the default blue Matplotlib color "C0". If number of vectors visible in the hemisphere is 2, this would then return an array with "C0" in it, while I wanted an array with ["C0", "C0"] instead.

I agree that the logic is horrible, but if we don't check whether `value` has the `__iter__` attribute, `len(value)` throws `TypeError`. So they have to be in front of those checks.

Do you prefer try/except? I could use that.

2021-03-05 14:08 UTC, hakonanes commented on orix/plot/stereographic_plot.py
>          if len(values) == 2:
The input `values` should always be a tuple (as per the docstring), either with two elements (two arrays or floats with azimuth and polar coordinates) or one (a Vector3d object). What's more, `Vector3d` has no `len()`, so if `values` was a `Vector3d` instance that if clause would raise a `TypeError`.

I suggest we leave it as it is, and revisit if we would like for `values` to not strictly be a tuple, but something else (like a `Vector3d` object).

2021-03-05 14:09 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    # Elements' zorder (let's try to keep this updated!):
Very good suggestion. I anticipate we would like to extend this class quite a bit, and it is important to keep track of what goes on top of what. Putting the `zorder`s in a dictionary was quick to do, so I did it in this PR. Better to do it right right away.

2021-03-05 14:09 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    def draw_circle(self, *args, opening_angle=0.5 * np.pi, steps=100, **kwargs):
Yup, good suggestion, have changed this in all places in `stereographic_plot.py` and new functionality in `vector3d.py`.

2021-03-05 14:13 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    indices = np.where(visible != visible[0])[0]
I use numpy where here to get the first element in the boolean array not equal to the first element in the array (don't know if True or False is the first element). The use case here is as follows: when we draw a great circle in a hemisphere, only half of it will be visible, so half of the elements in `visible` are True. But these values doesn't have to always be at the start of the array or at the end, like [True True True False False False], but can be [True True False False False True]. In the latter case, Matplotlib will upon calls to `plot()` draw a line between all the azimuthal and polar coordinates, and when there is a jump around to the other side of the equatorial plane, a straight line is drawn across the plane as well. We don't want this, therefore this logic.

2021-03-05 14:15 UTC, hakonanes commented on orix/tests/test_stereographic_plot.py
> +        assert np.allclose(polar_out, desired_polar)
I agree that it isn't obvious! See my comment above https://github.com/pyxem/orix/pull/158#discussion_r588324465.

2021-03-05 14:17 UTC, hakonanes commented
Thanks for the review so far, @pc494! I hope I've answered your questions so that all the if/else clauses and other parts are more clear.

(I'm not sure about your latest comment above, because I did ping you for a review.)

2021-03-05 14:20 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    indices = np.where(visible != visible[0])[0]
I'll give `nonzero` a try

2021-03-05 14:21 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    indices = np.where(visible != visible[0])[0]
Which works like a charm, will use that instead. Thanks!

2021-03-05 17:12 UTC, pc494 commented on orix/plot/stereographic_plot.py
>          if len(values) == 2:
I read `tuple of numpy.ndarray or Vector3d` as (tuple of numpy.ndarray) **or** Vector3d, but given the interpretation you've just given this seems okay

2021-03-05 17:26 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +        value = [value,] * n
On reflection I think this is giving the right answer in a fairly efficient way. I think the final `or len(value)!= n` can be dropped though. Then the four cases run:

single string: False on the first block, True on the second plot, returns ['string'] * n
single float:  False on the first block via the hasattr clause, true on the second one by extension job done
list of length n: False on the final clause for block one and False on the hassattr clause on block two
list of length !=n : block 1 gets the first element, which means block two is dealing with a single float/string (and doesn't use the final bit of or logic)

Is that at least a correct understanding of the code?

2021-03-05 17:28 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    indices = np.where(visible != visible[0])[0]
Marking as resolve, the code is more "numpy consistent" and I now know why we have to reorder the arrays

2021-03-05 17:30 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    if indices.size != 0:
Can `indices.size` be zero?

2021-03-05 18:38 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    if indices.size != 0:
Yes, for the great circle about the north pole in the when the upper hemisphere is plotted and for the lower equivalent. If no elements are not visible, indices[-1] yields an IndexError.

2021-03-05 18:45 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        value = [value,] * n
Yes, you explained it much better than I did with my example. I removed the last bit of logic in block two, which as you say isn't necessary.

2021-03-06 15:01 UTC, pc494 commented on orix/plot/stereographic_plot.py
> +    if indices.size != 0:
cool, resolved

2021-03-06 15:04 UTC, pc494 approved these changes

2021-03-06 15:04 UTC, merged

2021-03-06 15:29 UTC, hakonanes commented
Thanks a lot for the feedback, @din14970, and for reviewing, @pc494!