Improving the performance of the gridding utils (see #175)
pyxem/orix pull request #177
Opened 2021-04-25 12:35 UTC by pc494

#### Description of the change
Improving the performance of the gridding utils by allowing a uniform sampling of a subspace (see #175 for details) - this is a work in progress, but I put the starting code up just in case people were curious.

#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix import vector
>>> v = vector.Vector3d([1, 1, 1])
>>> # Your new feature...
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-04-26 15:26 UTC, pc494 commented
While I'm here I'm going to tidy up the class method "random": https://github.com/pyxem/orix/blob/692c54aefae59a2c3b5d1e1454e50f361d6849d3/orix/quaternion/rotation.py#L530 which is quiet sloppy at the moment.

I'll also look into the https://github.com/pyxem/orix/blob/692c54aefae59a2c3b5d1e1454e50f361d6849d3/orix/quaternion/rotation.py#L549 functionality.

2021-04-30 12:10 UTC, pc494 commented
> While I'm here I'm going to tidy up the class method "random":
> 
> https://github.com/pyxem/orix/blob/692c54aefae59a2c3b5d1e1454e50f361d6849d3/orix/quaternion/rotation.py#L530
> which is quiet sloppy at the moment.
> 
> I'll also look into the
> 
> https://github.com/pyxem/orix/blob/692c54aefae59a2c3b5d1e1454e50f361d6849d3/orix/quaternion/rotation.py#L549
> functionality.

Going to transfer this into an issue to be dealt with when the large refactor comes in at some point in the future.

2021-05-02 09:50 UTC, hakonanes requested changes
Thanks for looking into the rotation sampling, @pc494.

I haven't fully understood the maths involved here, but the sample returned with angles of about 1-7 degrees accompanied by a resolution in the order of 0.5 degrees returns an empty sampling. Could you explain this to me?

Apart from this, I like that you've renamed the utilities to SO3, so that we can easily fit SO2 in the future into this `orix.sampling` module.

2021-05-02 09:50 UTC, hakonanes commented on orix/sampling/sample_generators.py
> +    q = uniform_SO3_sample(resolution,max_angle=grid_width)
This requires almost no memory at all, great work! I haven't looked into the actual rotations I'm getting back, other than the mean and that the misorientation to the mean is not greater than the `grid_width`.

Ah, looking at a narrow sampling, I get no rotations with a grid width of 4 degrees and a resolution of half a degree:
```python
>>> import numpy as np
>>> from orix import quaternion, sampling
>>> r = quaternion.Rotation.from_euler(np.deg2rad([133.3, 88.7, 177.8]))
>>> sampling.get_sample_local(resolution=0.5, center=r, grid_width=4)
Rotation (0,)
[]
```

Is this as expected?

Checking the sample sizes
```python
>>> widths = np.arange(1, 10)
>>> resolution = 0.5
>>> sample_sizes = np.zeros_like(widths)
>>> r = quaternion.Rotation.from_euler(np.deg2rad([133.3, 88.7, 177.8]))
>>> for i in range(widths.size):
..         r2 = sampling.get_sample_local(resolution=resolution, center=r, grid_width=widths[i])
..         print(widths[i], r2.size)
1 0
2 0
3 0
4 0
5 10
6 11
7 13
8 7924
9 18711
```

Looking into `uniform_SO3_sample()`, when `max_angle` is True and below 5, `u1` is empty because `u1max` is small, on the order of 1e-7.

2021-05-02 09:50 UTC, hakonanes commented on orix/sampling/SO3_sampling.py
> +        u_1 = np.linspace(0,u_1_max,num=int(num_steps*(u_1_max)),endpoint=True)
`int(num_steps * u_1_max)` becomes zero when `u_1_max` is small (see comment to `get_sample_local()`). Is there some way to handle the case where max angle is small (1-7 degrees) and a resolution of below 1 degree?

2021-05-02 11:37 UTC, pc494 commented
Thanks @hakonanes for this review, it's very good. It'll take me a little while to loop back to this but when I do I think most of the style changes will be simple to implement. The version in `0.6` is going to be a bit lacking (although we can fix the bug that gives back empty regions) and I've got a sense of what a more complete implementation will look like (probably for `0.7.0`)

2021-05-02 11:46 UTC, hakonanes commented
That sounds like a good plan. As mentioned in #175, there is no rush.

2021-05-07 13:28 UTC, pc494 reviewed
Working on these locally, will be up shortly.

2021-05-07 13:50 UTC, hakonanes approved these changes

2021-05-07 13:53 UTC, hakonanes commented
Good stuff! I'll let you merge yourself, @pc494.

2021-05-07 14:08 UTC, merged