Reader of xmap from Bruker's HDF5 file, rewrite EMsoft reader
pyxem/orix pull request #206
Opened 2021-06-22 11:23 UTC by hakonanes

Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
* Reader of a crystal map from Bruker's HDF5 file (h5ebsd format) from orientation data obtained from Hough indexing of either EBSD or Transmission Kikuchi Diffraction (TKD) data.
* Since this format is similar to EMsoft's HDF5 file (h5ebsd format), I rewrote this reader as well. Both h5ebsd readers are now implemented as classes inheriting from a base `H5ebsdFile` class. This will make it easier to add a EDAX TSL h5ebsd reader and Oxford Instruments h5ebsd reader in the future.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix import io
>>> xmap = io.load("file.h5")
>>> xmap
Phase   Orientations         Name  Space group  Point group  Proper point group     Color
   -1   1178 (23.4%)  not_indexed         None         None                None         w
    1   3862 (76.6%)         Gold        Fm-3m         m-3m                 432  tab:blue
Properties: PCX, PCY, DD, MAD, NIndexedBands, RadonBandCount, RadonQuality, XBEAM, YBEAM, XSAMPLE, YSAMPLE, ZSAMPLE
Scan unit: um
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-06-26 17:53 UTC, dnjohnstone requested changes
This basically looks good to me - a couple of very minor possible things flagged

2021-06-26 17:53 UTC, dnjohnstone commented on orix/io/plugins/_h5ebsd.py
> +        ----------
Please could you have another quick look at this docstring? looks a little incomplete on what group_name and dict are?

2021-06-26 17:53 UTC, dnjohnstone commented on orix/tests/io/test_io.py
> +            ("Oxford", None),
Do you want to test Bruker here also now?

2021-06-28 09:17 UTC, hakonanes commented on orix/io/plugins/_h5ebsd.py
> +        ----------
I've updated the docstring with a clear reference for a developer to look at the referenced function for further details on the parameters. This class will always be private, so I think it's OK to not explain its use in great detail in this method.

2021-06-28 09:17 UTC, hakonanes commented on orix/tests/io/test_io.py
> +            ("Oxford", None),
Yes, and I've updated the test to do so now. Thanks!

2021-06-29 14:50 UTC, pc494 approved these changes
This LGTM, merging

2021-06-29 14:50 UTC, merged

2021-06-29 14:51 UTC, hakonanes commented
Great, thanks!