add transpose class method
pyxem/orix pull request #210
Opened 2021-06-23 18:01 UTC by harripj

#### Description of the change
Duplicate of #209 with a new branch name.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-06-24 08:09 UTC, hakonanes requested changes
As @pc494 mentioned, thanks for this PR! It adds functionality that definitely should be there.

I've made some requests regarding style, tests, and overwriting the method in `Orientation` and `Misorientation` to carry over `Orientation.symmetry`. Please tell me if you need any assistance with anything.

2021-06-24 08:09 UTC, hakonanes commented on orix/base/__init__.py
> +        return self.__class__(self.data.transpose(*order, -1))
An issue with orix' class inheritance is that necessary properties, like `Orientation.symmetry`, isn't carried over. Could you overwrite this method in the `Misorientation` class like so

```python
class Misorientation(Rotation):
[...]
    def transpose(self, *axes):
        mori = super().transpose(*axes)
        sym1, sym2 = self.symmetry
        mori.set_symmetry(sym1, sym2)
        return mori
```

and in `Orientation`

```python
class Orientation(Misorientation):
[...]
    def transpose(self, *axes):
        ori = super().transpose(*axes)
        ori = ori.set_symmetry(self.symmetry)
        return ori
```

I think that should work, not 100% sure. Please tell me if you encounter some issues.

2021-06-24 08:09 UTC, hakonanes commented on orix/base/__init__.py
> +
Regarding tests. Have you written those using pytest before? If you want to write them, I think adding some in `orix/tests/test_orientation.py` and `orix/tests/test_vector3d.py` should be OK. In the former, you should also check that the symmetry carries over.

2021-06-24 08:11 UTC, hakonanes commented on orix/base/__init__.py
> +
If you don't want to write them, I could do that.

2021-06-24 09:30 UTC, harripj commented on orix/base/__init__.py
> +        """Returns a new object containing the same data transposed.
No problem!

2021-06-24 09:39 UTC, hakonanes commented on orix/base/__init__.py
> +        """Returns a new object containing the same data transposed.
Great! If you could just change to `axes : int, optional` that would be perfect.

2021-06-24 10:12 UTC, hakonanes commented
@harripj you can see how the docstring looks on the Read the Docs build: https://orix--210.org.readthedocs.build/en/210/reference.html#orix.base.Object3d.transpose

2021-06-24 11:59 UTC, harripj commented on orix/base/__init__.py
> +        return self.__class__(self.data.transpose(*order, -1))
I've just been trying to implement this, but in the case of '''Orientation''' this doesn't work as far as I can tell as '''super''' will call the method from '''Misorientation''' which will fail as '''Misorientation''' has two symmetries compared to '''Orientation''''s one. We could possibly just call '''Object3D''' init and then cast after transpose?

Another comment would be whether symmetries should or could be assumed to maintain order after transpose? Not sure on this point either, any thoughts?

2021-06-24 12:00 UTC, harripj commented on orix/base/__init__.py
> +        return self.__class__(self.data.transpose(*order, -1))
Sorry for the misformatting, not currently at a computer!

2021-06-24 16:55 UTC, hakonanes commented on orix/base/__init__.py
> +        return self.__class__(self.data.transpose(*order, -1))
> I've just been trying to implement this, but in the case of '''Orientation''' this doesn't work as far as I can tell as '''super''' will call the method from '''Misorientation''' which will fail as '''Misorientation''' has two symmetries compared to '''Orientation''''s one.

Pulled your changes locally and found out you can do:

```python
        mori = super().transpose(*axes)
        mori.set_symmetry(self.symmetry)
        return mori
```

> Another comment would be whether symmetries should or could be assumed to maintain order after transpose? Not sure on this point either, any thoughts?

I'm comfortable with leaving the `Symmetry` class be, since I cannot think of a relevant use case at the moment.

2021-06-24 16:58 UTC, hakonanes commented on orix/base/__init__.py
> +            if len(self.shape) != 2:
I think this error is misleading when an instance is 1D. I suggest you just let a 1D array pass through to the final return.

2021-06-24 17:05 UTC, hakonanes commented on orix/base/__init__.py
> +        return self.__class__(self.data.transpose(*order, -1))
A (hopefully!) final request regarding overriding: the `Miller` class should pass along the `Miller.phase` and `Miller.coordinate_format`, like is done for [`Miller.flatten()`]: https://github.com/pyxem/orix/blob/dffb68e0619d8b2381de629efbc2962b8e81c284/orix/vector/miller.py#L602-L605

`Miller` stores vectors in cartesian coordinates internally as `Miller.data`, that's why `xyz` is used in initialization.

2021-06-25 09:53 UTC, harripj commented on orix/base/__init__.py
> +            if len(self.shape) != 2:
Yes, I have added an initial pass through for 1d data.

2021-06-25 09:58 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
Could you explain to me why my suggestion in https://github.com/pyxem/orix/pull/210#discussion_r658124898 isn't enough?

2021-06-25 11:12 UTC, harripj commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
#210 works as expected for ```Misorientation```, but not so for ```Orientation``` as ```Orientation``` (as far as I am aware) has one symmetry attribute whereas ```Misorientation``` has two. In this case when ```super``` is called from ```Orientation.transpose``` it calls ```Misorientation.transpose``` which expects to unpack two symmetries but can only unpack one and crashes. I also tried this with a vararg but couldn't get it to work. Commit #e5e15e2 attempts to handle this case and in fact this means that ```Orientation.transpose``` can be handled by ```Misorientation.transpose``` (commit b1b5cb2).

2021-06-25 11:18 UTC, harripj commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
I believe ```Misorientation.set_symmetry``` accepts two arguments rather than a tuple of symmetries. If I try to unpack ```*self.symmetry``` it will work for ```Misorientation``` but not ```Orientation``` (as it then unpacks the single symmetry).

2021-06-25 12:15 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
Ah yes, sorry! I suggest that you just set the private `mori._symmetry = self._symmetry` attribute, to avoid going via `Misorientation.set_symmetry()`. This should be safe to do, since `transpose()` should never change the crystal symmetry.

Also, the `Misorientation` class can assume that `Misorientation._symmetry` is a valid `Symmetry` instance, so these checks are unnecessary.

What do you think, @harripj?

2021-06-25 12:56 UTC, harripj commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
Makes sense! I will update this in the next commit.

2021-06-25 13:45 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
Looking better! What I meant was to remove *all* the checks, and just do

```python
def transpose(self, *axes):
    mori = super().transpose(*axes)
    mori._symmetry = self._symmetry
    return mori
```

This way you dont need `Orientation.transpose()`, or the checks.

2021-06-25 14:06 UTC, harripj commented on orix/quaternion/orientation.py
> +        elif isinstance(self.symmetry, tuple) and all(
Ideal! Updated in latest commit.

2021-06-25 14:41 UTC, hakonanes commented
Note that coverage can be checked locally with the coverage.py package as explained in the [contributing guide](https://orix.readthedocs.io/en/latest/contributing.html#run-and-write-tests).

2021-06-26 16:06 UTC, hakonanes requested changes
Great stuff @harripj, thank you! In my opinion this is nearly ready to be merged. @pc494 might have something to add.

I've made some final suggestions. In addition to these, I would very much appreciate it if you could:
1. Add a one-line explanation of the addition (e.g. the PR title) to the changelog (CHANGELOG.rst in top directory) under Unreleased/Added, at the bottom of the list (newest additions).
2. Update the API reference (which is not 100% auto generated) with the transpose method in the list of class methods under Orientation/auto_summary (alphabetically), and likewise for Misorientation, Rotation, Miller and Vector3d.

2021-06-28 09:49 UTC, harripj commented on orix/tests/test_vector3d.py
> +    try:
Also incorporated for test_transpose_3d_wrong_number_of_axes

2021-06-28 11:59 UTC, hakonanes approved these changes

2021-06-28 12:01 UTC, hakonanes commented
Again, thanks for this @harripj! I'd appreciate it if either @dnjohnstone or @pc494 could merge this, to get another pair of eyes.

2021-06-29 14:57 UTC, pc494 commented
I'll review this and fix the conflict :)

2021-06-29 15:05 UTC, pc494 approved these changes
I am happy with this, will deal with the conflict and merge. Many thanks @harripj

2021-06-29 15:17 UTC, merged