Inverse pole figure plotting and coloring
pyxem/orix pull request #235
Opened 2021-10-22 16:27 UTC by hakonanes

#### Description of the change
New functionality:
1. Rotations of directions in the sample coordinate system by orientations to find crystal coordinate directions parallel to these sample directions. This is available via `Orientation.scatter()` with the `projection="ipf"` option, which defaults to out-of-plane direction (IPFZ). Closes #122.
2. Coloring of orientations by specifying a direction in the sample reference frame and a crystal symmetry. Only distinguish between Laue groups so far, based on the TSL coloring in MTEX. Closes #166.
3. Projection of vectors, typically crystal coordinates, into the fundamental sector in the stereographic projection of a symmetry, via `Vector3d.in_fundamental_sector(sector)`. This is based on `vector3d.project2fundamentalRegion` in `MTEX`. Closes #169.

This functionality uses a new `orix.plot.InversePoleFigurePlot` class which inherits from `orix.plot.StereographicPlot`.

Other changes which were necessary but need some consideration:
1. All use of `Orientation.set_symmetry()` internally (via __invert__, __neg__, etc) is removed, because otherwise I couldn't get any directions to rotate where I wanted them. **All tests depending on indirect calls to `set_symmetry()` will fail for now**. See #233.
2. Took the *S2* cube mesh generation in `diffsims` implemented by @din14970. It would be best if you could make a PR with this code, perhaps to my branch `add-inverse-pole-figure-plot`, so that the contribution carries your name. As mentioned before, I think these functions belong in orix, since diffsims depends on orix.

#### Credit
The orientation coloring is based on the procedure explained in section 2.4 in Gert Nolze's and Ralf Hielscher's "Orientations – perfectly colored" [paper](https://doi.org/10.1107/S1600576716012942). MTEX's source code has also been of much help, specifically the functions [project2fundamentalRegion](https://github.com/mtex-toolbox/mtex/blob/develop/geometry/%40vector3d/project2FundamentalRegion.m) and [polarCoordinates](https://github.com/mtex-toolbox/mtex/blob/develop/geometry/%40sphericalRegion/polarCoordinates.m). Credit is made in the source code and documentation to these references.

The interpolation between colored vectors used in the IPF color key uses the `scipy.interpolate.griddata` approach suggested by @din14970 in #166.

#### Thoughts on patching this post-release
It would be great if people try this functionality out on their own datasets *before* merging this PR. However, experience tells me few people will do this, and that bugs will be found when released into the wild in a v0.8 release... I anticipate that we need to patch and improve this functionality many times, but I think this is OK. orix is still a v0.x code, i.e. no stable v1.0 release has been made yet. I'm comfortable with adding warnings to calls to `IPFColorKeyTSL` and `Orientation.scatter(projection="ipf")` stating that this is brand new functionality which needs "real world" testing, if people want that.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Fix ~plotting~ colouring of triclinic ,-1, IPF (full upper circle)
- [x] Fix projection to *-3m* (might be related to https://github.com/pyxem/orix/issues/236#issuecomment-963273120)
- [x] Make IPF user guide pedagogical
- [x] Use IPF plotting and coloring in crystal map user guide
- [x] Adjust spacing between IPF and fundamental sector vertex labels
- [x] Fix "splitting" of white centers seen in some IPF color keys
- [x] Incorporate changes in #240
- [x] Support adding to an already created IPF (https://github.com/pyxem/orix/pull/235#discussion_r751043008)
- [x] Support 2D navigation shape?

#### Minimal example of the bug fix or new feature
```python
>>> from orix import io, plot
>>> from orix.vector import Vector3d
>>> xmap = io.load("dot_product_file_from_emsoft.h5", refined=True)
>>> xmap
Phase    Orientations  Name  Space group  Point group  Proper point group     Color
    0  29800 (100.0%)    ni         None         m-3m                 432  tab:blue
Properties: AvDotProductMap, CI, IQ, ISM, KAM, OSM, RefinedDotProducts, TopDotProductList, TopMatchIndices
Scan unit: um
>>> ipfkey = plot.IPFColorKeyTSL(xmap.phases["ni"].point_group, direction=Vector3d.zvector())
>>> ipfkey
IPFColorKeyTSL, symmetry: m-3m, direction: [0 0 1]
>>> ipfkey.plot()
>>> ori = xmap.orientations
>>> rgb_z = ipfkey.orientation2color(ori)  # NumPy array
>>> ori.scatter(projection="ipf", c=rgb_z, direction=ipfkey.direction)
>>> xmap.plot(rgb_z, overlay="RefinedDotProducts")
```

![ni_ipf_key](https://user-images.githubusercontent.com/12139781/138488723-a3f965c0-2eab-4726-8c0f-0d89f02c541a.png)

![ni_ipfz_scatter](https://user-images.githubusercontent.com/12139781/138488732-fffbf3a5-caab-497b-b130-7185a275b1b5.png)

![ni_ipfz_dp](https://user-images.githubusercontent.com/12139781/138488729-1a3c81a3-99b3-477a-8a54-b6ef83be5172.png)

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-11-09 09:48 UTC, hakonanes commented
The issue with projection of vectors into the fundamental sector of *-3m* might be related to the discussion of difference between symmetry operations in orix and MTEX highlighted in https://github.com/pyxem/orix/issues/236#issuecomment-963273120.

2021-11-10 19:05 UTC, pc494 reviewed
This problem might be more more boring than it looked (or it might not, not 100% on this)

2021-11-10 19:05 UTC, pc494 commented on orix/vector/vector3d.py
> +        elif symmetry.name in "-3":
The looks like a bug - Either `elif symmetry.name == "-3"` or `elif symmetry.name in ["-3"]` ought to work, as is I think this will always evaluate to false.

2021-11-11 09:21 UTC, hakonanes commented on orix/vector/vector3d.py
> +        elif symmetry.name in "-3":
Good catch, thanks, this is a bug, will see if it changes anything.

2021-11-26 15:02 UTC, harripj requested changes

2021-11-26 15:02 UTC, harripj commented on orix/plot/direction_color_keys/_util.py
> +        polar = np.full(v.size, np.inf)
I have just been playing around with generating IPF colours directly from 2d maps. At the moment this does not work as `v.size` creates a 1d array which then flows through the rest of the code. If this is changed to `v.shape`, and including another change below, then IPF colour maps can be produced directly from n-dimensional sets of `Orientations`.

2021-11-26 15:02 UTC, harripj commented on orix/plot/direction_color_keys/_util.py
> +    return mcolors.hsv_to_rgb(np.column_stack([h, s, v]))
As per comment above, this would also need adapting as:
```python 
mcolors.hsv_to_rgb(np.stack([h, s, v], axis=-1))
```

2021-11-26 20:29 UTC, hakonanes commented on orix/vector/vector3d.py
> +        rotated_centers = rot * fs.center
You're right, thanks for pointing to the failing bit! (This PR was never meant to be merged without fixing this (it's a task in top comment).)

2021-11-26 20:32 UTC, hakonanes commented on orix/quaternion/orientation.py
> +
Yes, this should be supported, I've added a task in the top comment.

2021-11-26 20:35 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +        polar = np.full(v.size, np.inf)
Hm, I think we could support this without too much extra effort and it being error prone. I'm thinking perhaps storing the original shape and reshaping the RGB array right before returning.

2021-11-26 20:37 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +    return mcolors.hsv_to_rgb(np.column_stack([h, s, v]))
Yes, if we decide for all the utility functions to support 2D navigation shapes, this should be changed. As mentioned above I might be inclined to just support 2D shapes in some top level functions/methods, but not in the "lower" level stuff. If it's easy and not prone to errors, we'll do it.

2021-11-26 20:42 UTC, hakonanes commented
Thanks for your great input, @harripj! I hope to find time this weekend or early next week to work some more on this PR with the feedback from you and @pc494. (And some time to work on your open PR.)

2021-11-29 16:03 UTC, hakonanes commented
I think we need plotting of crystal symmetry elements ([in MTEX](https://mtex-toolbox.github.io/CrystalSymmetries.html#2), [current functionality in orix](https://orix.readthedocs.io/en/stable/stereographic_projection.html#Experimental-functionality)) before finishing this PR, as I don't know the basis for the choices of symmetry axes for the various hard-coded crystal symmetries:

https://github.com/pyxem/orix/blob/73a8127b67a707bba5a423d9f18853e403055d06/orix/quaternion/symmetry.py#L402-L403

Choosing Y (*Csy*, what MTEX uses) as the mirror plane instead of X (*Csx*) here solves the issue with projection into the fundamental sector of -3m.

@pc494, do you know the source of the choice of symmetry axes?

2021-11-29 20:31 UTC, hakonanes commented on orix/vector/vector3d.py
> +        elif symmetry.name in "-3":
The issue with projecting vectors into the fundamental sector of *-3m*, shown in https://github.com/pyxem/orix/pull/235#issuecomment-952913720, is now resolved. The issue was that the sector defined in `Symmetry.fundamental_sector` for *-3m* was incorrect, i.e. bounded by [0001], [2 -1 -1 0], [0 1 -1 0], instead it should be [0001], [1 -1 0 0], [1 0 -1 0].

2021-11-29 20:32 UTC, hakonanes commented on orix/vector/vector3d.py
> +        rotated_centers = rot * fs.center
This change is now done, thanks!

2021-11-30 16:11 UTC, hakonanes commented on orix/quaternion/orientation.py
> +
This is now supported as with stereographic plots. This means it's also possible to plot a scatter on top of an IPF color key.

2021-11-30 16:18 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +        polar = np.full(v.size, np.inf)
This is now supported.

2021-11-30 16:18 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +    return mcolors.hsv_to_rgb(np.column_stack([h, s, v]))
The changes you suggested were enough to support this, thanks a lot @harripj!

2021-11-30 16:29 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +    return mcolors.hsv_to_rgb(np.column_stack([h, s, v]))
Feel free to resolve a conversation in a review you've done when you're sufficiently satisfied with the changes :)

2021-11-30 16:37 UTC, hakonanes commented on orix/plot/direction_color_keys/_util.py
> +    return mcolors.hsv_to_rgb(np.column_stack([h, s, v]))
Aha, didn't realize that, thanks.

2021-11-30 18:52 UTC, hakonanes commented
I've changed my mind, I'll stick to this PR. I anticipate making it ready for final review within the end of this week.

It's mostly simple documentation and testing left. I'll leave a user guide for another PR, as I think we should restructure the notebooks into sections to facilitate shorter and more focused notebooks, and not all encompassing notebooks as we mostly have now.

2021-12-01 11:19 UTC, hakonanes commented
There are some docstring changes left, but I consider this PR ready for review.

2021-12-01 13:17 UTC, pc494 approved these changes
I'm happy with what I've been asked to review here, and will merge when that's requested.

2021-12-01 14:55 UTC, hakonanes commented
Thanks, @pc494! I'd appreciate it if @harripj could quickly try the functionality with the latest updates for his needs, since he's already given useful feedback on usability.

Going forward, hoping that this functionality will attract more people to orix, I anticipate that there will be discussions on crystal basis vector alignment (undocumented), which fundamental sector (of the symmetrically equivalent ones) to use, and perhaps the color given to each crystal direction. I'll try my best to patch any bugs in this IPF functionality in minor releases following v0.8.

2021-12-01 15:07 UTC, harripj commented
@hakonanes thanks for the ping, I will definitely give it a look over and test with what I have been using it for.

> Going forward, hoping that this functionality will attract more people to orix, I anticipate that there will be discussions on crystal basis vector alignment (undocumented), which fundamental sector (of the symmetrically equivalent ones) to use, and perhaps the color given to each crystal direction.

I think the work you've done here is really great and a big step forward towards diversifying the code, especially for crystal mapping.

2021-12-01 15:15 UTC, hakonanes commented
> @hakonanes thanks for the ping, I will definitely give it a look over and test with what I have been using it for.

Great, thanks, I'm grateful for the feedback you've given.

> I think the work you've done here is really great and a big step forward towards diversifying the code, especially for crystal mapping.

Yes, and with out-of-the-box pole figure plotting (very little extra work needed, really) I believe we have a complete set of the "simplest" usual tools we need for orientation analysis in orix (in addition to the more "advanced" 3D plots and rotation sampling).

2021-12-02 13:25 UTC, harripj commented
@hakonanes this looks good to me! I'm sure that if there are any problems, they can be updated or ironed out in the future.

2021-12-02 13:37 UTC, hakonanes commented
Thanks @harripj. Feel free to merge, @pc494.

2021-12-03 09:32 UTC, merged