Add symmetry property to Orientation-based classes in favour of set_symmetry
pyxem/orix pull request #240
Opened 2021-11-10 13:15 UTC by harripj

#### Description of the change
As discussed in #235 the use of ```set_symmetry``` produces behaviour which may be undesired in certain circumstances. As such a ```symmetry``` property has been introduced for ```Orientation``` and ```Misorientation``` classes which sets the instances ```_symmetry``` attribute without further calculations.

These extra calculations, in the case of the ```Orientation``` class, take the form of finding the symmetry component with the smallest angular distance to the ```C1``` symmetry, which is the identity orientation. In this PR no calculations are automatically performed when the ```symmetry``` property is set. A new function currently named ```compute_symmetry_reduced_orientations``` performs the calculations previously defined within ```set_symmetry```. In this case, the old functionality afforded by ```set_symmetry```:
```python
o = Orientation.random((5, 3))
o.set_symmetry(Oh)
```
can still be achieved as:

```python
o = Orientation.random((5, 3))
o.symmetry = Oh
o = o.compute_symmetry_reduced_orientations()
```

This would be in favour of possibly deprecating ```set_symmetry``` in a future release.

The tests have been updated to use the new syntax above and are passing.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from orix.quaternion import Orientation
o = Orientation.random((5, 3))
o.symmetry = Oh
o.symmetry
>>> Symmetry (48,) m-3m
    [[ 1.      0.      0.      0.    ]
    ...
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-11-10 15:50 UTC, hakonanes requested changes
This reflects nicely what I had in mind after our discussion in #235! I have several suggestions for improvements, and also some suggestions for further changes, but we should leave these for other PRs.

**Before implementing the suggested changes though, I would like to get @pc494 broad impressions on this change, as he is most familiar with this part of the code among us.**

Also, we need to check the notebooks that they produce expected results. E.g. plotting of (mis)orientations inside fundamental zones. This was the motivation for always assigning (mis)orientations the smallest rotation angle, since they then fall inside the zones. I'll do this and suggest further changes where necessary.

2021-11-10 15:50 UTC, hakonanes commented on CHANGELOG.rst
> +- `symmetry` property for `Orientation` and `Misorientation` classes.
Both classes already have a symmetry ([see API](https://orix.readthedocs.io/en/stable/reference.html#orix.quaternion.Orientation.symmetry)).

```suggestion
- Setting the symmetry of a (Mis)Orientation via a `symmetry.setter`.
```

2021-11-10 15:50 UTC, hakonanes commented on CHANGELOG.rst
> +  >>> o = o.compute_symmetry_reduced_orientations()
We should be brief in the changelog, ideally one, max. two lines per point.

```suggestion
- Setting (Mis)Orientation symmetry via `set_symmetry()` is deprecated in 0.8, in favour of
  setting it directly via a `symmetry.setter`, and will be removed in 0.9. Use
  `assign_smallest_angle()` instead.
```

2021-11-10 15:50 UTC, hakonanes commented on orix/crystal_map/crystal_map.py
> +            return o.compute_symmetry_reduced_orientations()
I suggest changing the behaviour of `CrystalMap.orientations` and not returning the orientations with the smallest rotation angle, and leaving that up to the user to do. This change should be added to the changelog.

```suggestion
            orientations = Orientation(rotations)
            orientations.symmetry = phases[:].point_group
            return orientations
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        self._symmetry = tuple(values)
```suggestion
    def symmetry(self, value):
        err_message = "Value must be a tuple with two Symmetry instances."
        if not isinstance(value, (list, tuple)):
            raise TypeError(err_message)
        if len(value) != 2 or not all(isinstance(s, Symmetry) for s in value):
            raise ValueError(err_message)
        self._symmetry = tuple(value)
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +    )
```suggestion
    @deprecated(
        since="0.8",
        alternative="orix.quaternion.Misorientation.assign_smallest_angle",
        removal="0.9",
    )
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return misori.compute_symmetry_reduced_orientations()
```suggestion
        return misori.assign_smallest_angle()
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        Gl, Gr = self._symmetry
Following the docstring, I find `assign_smallest_angle()` a more informative name, what do you think @harripj?

What do you think @pc494? You've touched this part of the code the most of us.

I've also suggested small changes to the docstring example, in anticipation of us testing these as part of CI (using `pytest --doctest`).

```suggestion
    def assign_smallest_angle(self, verbose=False):
        """Computes equivalent transformations which have the smallest
        angle of rotation and assigns these in-place.

        Returns
        -------
        Misorientation
            A new misorientation instance with the smallest angle of rotation.

        Examples
        --------
        >>> import numpy as np
        >>> from orix.quaternion import Misorientation, symmetry
        >>> data = np.array([[0.5, 0.5, 0.5, 0.5], [0, 1, 0, 0]])
        >>> m = Misorientation(data)
        >>> m.symmetry = (symmetry.C4, symmetry.C2)
        >>> m.assign_smallest_angle()
        Misorientation (2,) 4, 2
        [[-0.7071  0.7071  0.      0.    ]
        [ 0.      1.      0.      0.    ]]
        """
        Gl, Gr = self._symmetry
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +                "Value must be an instance of orix.quaternion.symmetry.Symmetry."
The `Symmetry` class is reachable from the `orix.quaternion` module, and should be imported from here.

```suggestion
                "Value must be an instance of orix.quaternion.Symmetry."
```

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +            o.symmetry = symmetry
The fact that these methods don't return orientations with the smallest angle of rotation under symmetry should be added to the changelog!

2021-11-10 15:50 UTC, hakonanes commented on orix/quaternion/orientation.py
> +    )
```suggestion
    @deprecated(
        since="0.8",
        alternative="orix.quaternion.Orientation.assign_smallest_angle",
        removal="0.9",
    )
```

2021-11-10 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    o.symmetry = symmetry
We should allow passing the symmetry upon initialization, no? This should be documented in the `Orientation.__init__(self, data, symmetry=None)` docstring. *C1* should be default when `symmetry` isn't given, to give same result as before.

```suggestion
    o = Orientation(orientation.data, symmetry)
```

2021-11-10 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    o.symmetry = symmetry
This should be done for `Misorientation.__init__(self, data, symmetry=None)` as well, with `symmetry` being a tuple with `Symmetry` instances.

2021-11-10 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +        o.symmetry = 1
Shorten with `pytest.mark.parametrize`?

```suggestion
@pytest.mark.parametrize("error_type, value", [(ValueError, (1, 2)), (ValueError, (C1, 2)), (TypeError, 1)])
def test_symmetry_property_wrong_type_misorientation(error_type, value):
    mori = Misorientation.random((3, 2))
    with pytest.raises(error_type, match="Values must be a tuple"):
        mori.symmetry = value
```

2021-11-10 15:50 UTC, hakonanes commented on orix/tests/test_miller.py
> +        o = o.compute_symmetry_reduced_orientations()
Do we need to assign smallest rotation angle for this test to pass? If not, I'd skip it!

2021-11-10 16:05 UTC, harripj commented on orix/tests/test_miller.py
> +        o = o.compute_symmetry_reduced_orientations()
The test looks like it passes without assigning smallest angle! Updating this.

2021-11-10 16:08 UTC, harripj commented on orix/crystal_map/crystal_map.py
> +            return o.compute_symmetry_reduced_orientations()
Makes sense to me too, I will update the tests to reflect this.

2021-11-10 16:21 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    o.symmetry = symmetry
I suggest leaving this for another PR!

2021-11-10 16:22 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +    o.symmetry = symmetry
I agree.

2021-11-10 17:07 UTC, harripj commented on orix/quaternion/orientation.py
> +        Gl, Gr = self._symmetry
The name of this function is certainly up for debate!

@hakonanes I think that the `smallest_angle` part is very informative, but to me `assign` indicates assign in-place rather than return a new instance (which is what the function is currently doing). I would prefer `compute` or `calculate` to this end. What do you think?

2021-11-10 17:17 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +    o.symmetry = symmetry
Created issue #241 to discuss this.

2021-11-11 09:28 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        Gl, Gr = self._symmetry
I agree that by assign we mean in-place, which is what the docstring says, but actually doesn't do! Another place where this docstring could be improved, good catch indeed.

I think @pc494's suggestion of `map_into_symmetry_reduced_zone()` (or perhaps `map_into_fundamental_zone()`) is even better, what do you think?

2021-11-11 11:07 UTC, harripj commented on orix/quaternion/orientation.py
> +        Gl, Gr = self._symmetry
Yes, well spotted! I will update the docstring here.

I think that both of these suggestions are informative and make sense. `map_into_symmetry_reduced_zone()` is easy to understand. `map_into_fundamental_zone()` I think we have to be clear that this is what is actually happening, and what would distinguish `zone` from `region` (as in `OrientationRegion`)?

2021-11-11 11:33 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        Gl, Gr = self._symmetry
Let's use map_to_symmetry_reduced_zone() then!

2021-11-16 09:34 UTC, hakonanes reviewed
This looks good, and I approve the changes that are in this PR now.

Before I approve the changes for merging, I'd just like to test plotting of orientations within the symmetry reduced zone (axis/angle and Rodrigues), and seeing that this works as before. We might have to call `map_into_symmetry_reduced_zone()` on the (mis)orientations *within* the plotting methods to achieve the desired result. Will report back in this PR after I've checked.

2021-11-16 09:34 UTC, hakonanes commented on CHANGELOG.rst
> +  `assign_smallest_angle()` instead.
```suggestion
  `map_into_symmetry_reduced_zone()` instead.
```

2021-11-16 09:34 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        alternative="orix.quaternion.Misorientation.assign_smallest_angle",
```suggestion
        alternative="orix.quaternion.Misorientation.map_into_symmetry_reduced_zone",
```

2021-11-16 09:34 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        alternative="orix.quaternion.Orientation.assign_smallest_angle",
```suggestion
        alternative="orix.quaternion.Orientation.map_into_symmetry_reduced_zone",
```

2021-11-16 09:34 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +
I would remove these blank lines, as per [PEP 8](https://www.python.org/dev/peps/pep-0008/#blank-lines).

2021-11-16 09:34 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    ):  # can only get this to work properly with one backtick...
Yeah, according to the [pytest documentation](https://docs.pytest.org/en/6.2.x/warnings.html#warns), `match` accepts text or a regex (with the string prepended by an `r`). I'd just leave this as it is, but remove the comment.

2021-11-16 09:58 UTC, hakonanes commented
I might push fixes to the failing tests to your branch, if that's OK @harripj.

2021-11-16 10:01 UTC, harripj commented
@hakonanes Absolutely.

2021-11-16 10:02 UTC, hakonanes commented
As expected, we need to call `map_into_symmetry_reduced_zone()` when plotting (mis)orientations in symmetry reduced zones. This code

```python
from orix.quaternion import Orientation, symmetry
ori = Orientation.random(1000)
ori.symmetry = symmetry.Oh
ori.scatter()
```

produces this plot

![orientation_scatter_outside](https://user-images.githubusercontent.com/12139781/141964364-7218c787-8e4b-4090-9352-b26c3c8dd07c.png)

2021-11-16 10:42 UTC, hakonanes commented
We need to add a call to `map_into_symmetry_reduced_zone()` in [`RotationPlot.transform()`](https://github.com/pyxem/orix/blob/master/orix/plot/rotation_plot.py#L33) method for (mis)orientations to retain previous behaviour:

```python
    def transform(self, xs):
        from orix.quaternion import Misorientation, Rotation

        if isinstance(xs, Misorientation):  # Also true for Orientation instances 
            xs = xs.map_into_symmetry_reduced_zone()
# As before below this
```

However, this means that `map_into_symmetry_reduced_zone()` is called with *every* call to `RotationPlot.transform()` with (mis)orientations, in contrast to only *once* in the previous implementation. This is a drawback when a workflow is mainly built out of many plots of (mis)orientations in fundamental zones.

The only solutions I can think of are:
1. Add a boolean parameter to `Misorientation.scatter()` which carry over to `RotationPlot.scatter()` and `RotationPlot.transform()` which allows us to bypass the call to `map_into_symmetry_reduced_zone()`. The user should only bypass this call when they themselves call `map_into_symmetry_reduced_zone()` before plotting.
2. Somehow check whether all (mis)orientation angles (`Orientation.angle.data.max()`) are within the fundamental zone, and only call `map_into_symmetry_reduced_zone()` when this is not the case. This requires adding something like the following to `RotationPlot.transform()`:

```python
from orix.quaternion import Misorientation, OrientationRegion, Rotation

if isinstance(xs, Misorientation):
    if isinstance(xs.symmetry, tuple):
        fr = OrientationRegion.from_symmetry(xs.symmetry[0], xs.symmetry[1])
    else:
        fr = OrientationRegion.from_symmetry(xs.symmetry)
    region_edge = fr.get_plot_data().angle.data.max()
    if xs.angle.data.max() > region_edge:
        xs = xs.map_into_symmetry_reduced_zone()
# The rest as before
```

The added computation of the orientation region and get_plot_data()  seems to be fairly cheap, 2.05 ms on my machine with `Oh` symmetry.

What do you think of these options, @harripj? And this would also be a good time to ask @pc494 what he thinks of these changes to fundamental zone plotting.

2021-11-16 12:34 UTC, harripj commented
@hakonanes well spotted. I think that 2ms is not a problem when calling a plot function, but on my machine I am getting ~50 ms:
```
%timeit fr = OrientationRegion.from_symmetry(*ori._symmetry)
47 ms ± 400 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit region_edge = fr.get_plot_data().angle.data.max()
53.3 ms ± 807 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

I would tend toward the first option though, providing a `bool` to pass to `scatter` etc. which allows for the user to use the functionality (by default) or not and this may make it easier to debug too.

A third option would be an internal flag within `Misorientation` classes, something like `_IS_IN_SYMMETRY_REDUCED_ZONE` which is `False` by default and is only set as `True` when the new instance is created within the `map_into_symmetry_reduced_zone` method. This would be very cheap computationally, but would limit the solution to `Misorientation` classes. Is there a need to extend this to 'Rotation' and 'Quaternion' classes too?

2021-11-16 12:50 UTC, hakonanes commented
> @hakonanes well spotted. I think that 2ms is not a problem when calling a plot function, but on my machine I am getting ~50 ms:

Hah, I believe I reported the uncertainty, not the mean. Sorry! However a 50 ms penalty isn't so bad either in my opinion.

> I would tend toward the first option though, providing a `bool` to pass to `scatter` etc. which allows for the user to use the functionality (by default) or not and this may make it easier to debug too.

Thanks, that's good to know. It's important to note that solution 1. assumes that the user has either read the API reference for the `scatter()` method or `RotationPlot` or a user guide (where we have to document this optional parameter). I prefer solution 2. since I cannot think of a state of (mis)orientations where this wouldn't work. We should still document the fact that if the user reduces (mis)orientations to the fundamental zone themselves, plotting will be faster (although we will *always* perform that check).

> A third option would be an internal flag within `Misorientation` classes, something like `_IS_IN_SYMMETRY_REDUCED_ZONE` which is `False` by default and is only set as `True` when the new instance is created within the `map_into_symmetry_reduced_zone` method.

Keeping track of such "state" parameters is difficult, and I would advice against it. For example, since all 3D objects in orix are mutable, we would have to update that parameter every time an element in an instance is changed. What we could do instead is to return whether the check I proposed in solution 2. is true or not as that parameter. Then we would never have to set it.

> This would be very cheap computationally, but would limit the solution to `Misorientation` classes. Is there a need to extend this to `Rotation` and `Quaternion` classes too?

Only `Misorientation` and `Orientation` classes have a notion of symmetry, so we don't have to worry about `Rotation` or `Quaternion` :)

2021-11-16 13:10 UTC, harripj commented
> Thanks, that's good to know. It's important to note that solution 1. assumes that the user has either read the API reference for the scatter() method or RotationPlot or a user guide (where we have to document this optional parameter). I prefer solution 2. since I cannot think of a state of (mis)orientations where this wouldn't work. We should still document the fact that if the user reduces (mis)orientations to the fundamental zone themselves, plotting will be faster (although we will always perform that check).

Good points and yes, case 2 will be more user friendly.

> Keeping track of such "state" parameters is difficult, and I would advice against it. For example, since all 3D objects in orix are mutable, we would have to update that parameter every time an element in an instance is changed. What we could do instead is to return whether the check I proposed in solution 2. is true or not as that parameter. Then we would never have to set it.

I hadn't thought of this at the time and it would certainly make it more difficult to implement. I like the idea of using your suggestion as a check. Perhaps `OrientationRegion` can be an optional argument to avoid its recalculation?

2021-11-16 13:26 UTC, hakonanes commented
> Perhaps OrientationRegion can be an optional argument to avoid its recalculation?

Yes, we could provide a function accepting an `OrientationRegion`, instead of providing an attribute where the region is created every time the attribute is accessed.

Ultimately, I cannot say which solution is best until @pc494 has reviewed that part of this PR. I know he's quite busy these days, so we just have to be patient :)

2021-11-20 09:23 UTC, pc494 commented
I'll be on it this weekend! 

NB: turns out that github tagging doesn't give me an extra ping

2021-11-20 11:17 UTC, hakonanes commented
Great, thanks! Good to know, will send you an email next time.

2021-11-20 16:25 UTC, pc494 commented
Apologies for the delay, unfortunately I'm going to be a dissenting voice on this.

If the user has an option to set a symmetry I think they would anticipate that the values of the quaternions left can be used to ID if Orientations/Misorientations are different. Otherwise, what exactly is the symmetry doing? This implementation would mean I could have two symmetry identical rotations, I could set the symmetry and I would they would still have different numerical values. If the objects represent the same physical transformation surely we want them to have the same numerical value. Also doing it at the start saves you a lot of fiddling around later (as the comments on this PR suggest).

I think the plots in https://github.com/pyxem/orix/issues/233#issuecomment-958779927 suggest 1 (or more) bugs. I'll have a quick look at the simplest case and feedback.

2021-11-22 11:49 UTC, hakonanes commented
> If the user has an option to set a symmetry I think they would anticipate that the values of the quaternions left can be used to ID if Orientations/Misorientations are different. Otherwise, what exactly is the symmetry doing?

Of course symmetry should be used in operations, like in class methods such as `angle_with()`. That is what I expect when using MTEX, that subsequent operations will respect symmetry; but I don't inspect the Euler angles in the `orientation` instance representation before and after setting the symmetry. Orientations don't change underlying quaternions in MTEX after setting the symmetry `ori.CS` (the representation, showing Euler angles, doesn't change either).

> Also doing it at the start saves you a lot of fiddling around later (as the comments on this PR suggest).

A problem is that `set_symmetry()` is a comparatively demanding computational task, and it is called many times internally when performing operations on (mis)orientations (just look at this PR), not just upon creation.

> I think the plots in [#233 (comment)](https://github.com/pyxem/orix/issues/233#issuecomment-958779927) suggest 1 (or more) bugs. I'll have a quick look at the simplest case and feedback.
> 
> EDIT: Ignore my last comment, I think the two plots in the linked comment describe different situations. The top/left case are figures for a no symmetry case while the bottom/right case are for an object that has symmetry.

It should form a complete track in the IPF with crystal symmetry, as the boundaries are symmetry axes, so it must be a bug, right? Either in `master` or in #235.

___

This PR would make setting orientation symmetries in orix more like how it's done in MTEX. This would make it simpler to compare results to MTEX, and also to draw inspiration from MTEX' code. It doesn't mean it is the correct way to do it, though.

2021-11-22 14:13 UTC, pc494 commented
> > If the user has an option to set a symmetry I think they would anticipate that the values of the quaternions left can be used to ID if Orientations/Misorientations are different. Otherwise, what exactly is the symmetry doing?
> 
> Of course symmetry should be used in operations, like in class methods such as `angle_with()`. That is what I expect when using MTEX, that subsequent operations will respect symmetry; but I don't inspect the Euler angles in the `orientation` instance representation before and after setting the symmetry. Orientations don't change underlying quaternions in MTEX after setting the symmetry `ori.CS` (the representation, showing Euler angles, doesn't change either).
> 
> > Also doing it at the start saves you a lot of fiddling around later (as the comments on this PR suggest).
> 
> A problem is that `set_symmetry()` is a comparatively demanding computational task, and it is called many times internally when performing operations on (mis)orientations (just look at this PR), not just upon creation.

Okay, I think you've convinced me. Still some thing I'm unsure about but I think this is at least one question answered. The functionality set symmetry used to perform should be renamed to something more explicit.

2021-11-23 12:52 UTC, harripj commented
> It should form a complete track in the IPF with crystal symmetry, as the boundaries are symmetry axes, so it must be a bug, right? Either in master or in #235.

Yes there must be a bug somewhere, although I am not sure where at the moment! If we can find this bug then maybe this conversation becomes easier.

> The functionality set symmetry used to perform should be renamed to something more explicit.

Perhaps the naming is part of the problem. In a Pythonic way `set_symmetry` reads to me as an assignment, eg. `.symmetry =`, whereas it is currently doing more than this.

2021-11-23 13:37 UTC, hakonanes commented
> The functionality set symmetry used to perform should be renamed to something more explicit.

This is what this PR addresses by introducing `Misorientation.map_into_symmetry_reduced_zone()` inplace of `set_symmetry()`, and deprecating the latter.

As I see it, the only outstanding thing in this PR as it is now is to resolve the questions I raised in https://github.com/pyxem/orix/pull/240#issuecomment-970143921.

2021-11-23 15:18 UTC, harripj commented
> This is what this PR addresses by introducing Misorientation.map_into_symmetry_reduced_zone() inplace of set_symmetry(), and deprecating the latter.

Absolutely.

@hakonanes I have implemented path 2 in https://github.com/pyxem/orix/pull/240#issuecomment-970143921 and allowed the `fundamental_region` to be passed into `RotationPlot.transform` to avoid duplication in the case of `Misorientation.scatter`.

2021-11-23 17:17 UTC, pc494 commented
Am I correct in thinking this will be good for review fairly soon? :D

2021-11-23 17:40 UTC, harripj commented
@pc494 yep, I think it's good to go!

2021-11-25 15:15 UTC, pc494 reviewed
I'm basically happy with this, I have two small changes (that I'm happy to put in myself) which I've made as comments, if you (@harripj) could just agree to them that would be great.

My one question is how did you check that you had got all calls to .`set_symmetry` in when you changed it in the package (example in 'comment 3')?

2021-11-25 15:15 UTC, pc494 commented on CHANGELOG.rst
> +- `Orientation` class methods `from_euler`, `from_matrix`, and `from_neo_euler` no longer
Would like to adjust the wording here

2021-11-25 15:15 UTC, pc494 commented on orix/quaternion/orientation.py
> +        err_message = "Value must be a tuple with two Symmetry instances."
I see why you've used this pattern but I would prefer to have the two error messages made explicitly where they are called.

2021-11-25 15:15 UTC, pc494 commented on orix/quaternion/orientation.py
> +        o.symmetry = self.symmetry
eg. this (comment 3)

2021-11-25 15:49 UTC, harripj commented
> My one question is how did you check that you had got all calls to .set_symmetry in when you changed it in the package (example in 'comment 3')?

I searched `.set_symmetry` globally in the repository and changed each one to the equivalent calculation (which is now `o.symmetry = ..., o.map_into_symmetry_reduced_zone()`). This is apart from `CrystalMap` as discussed here https://github.com/pyxem/orix/pull/240#discussion_r746697369, and the class methods and both are documented in the Changelog here https://github.com/pyxem/orix/pull/240/commits/5062b738aff8e5040eb6fba3c2f073ac44d27969 and here https://github.com/pyxem/orix/pull/240/commits/5347279b7c27d6caeeca7367a705e42a0fcad9db.

A global search in the repository now only shows 4 instances of `set_symmetry` in the working code, specifically in `orientation.py`, all of which are wrapped within the deprecation warnings.

2021-11-25 16:30 UTC, pc494 commented
> > My one question is how did you check that you had got all calls to .set_symmetry in when you changed it in the package (example in 'comment 3')?
> 
> I searched `.set_symmetry` globally in the repository and changed each one to the equivalent calculation (which is now `o.symmetry = ..., o.map_into_symmetry_reduced_zone()`). This is apart from `CrystalMap` as discussed here [#240 (comment)](https://github.com/pyxem/orix/pull/240#discussion_r746697369), and the class methods and both are documented in the Changelog here [5062b73](https://github.com/pyxem/orix/commit/5062b738aff8e5040eb6fba3c2f073ac44d27969) and here [5347279](https://github.com/pyxem/orix/commit/5347279b7c27d6caeeca7367a705e42a0fcad9db).
> 
> A global search in the repository now only shows 4 instances of `set_symmetry` in the working code, specifically in `orientation.py`, all of which are wrapped within the deprecation warnings.

That seems robust.

2021-11-29 09:20 UTC, hakonanes requested changes
I've suggested some doc changes and some minor simplifications of code, otherwise I think this change is robust and the right way forward.

2021-11-29 09:20 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    o = Misorientation.random((3, 2))
Name the variable mori or m?

2021-11-29 09:20 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +        (ValueError, (C1, C2, C1)),
Make list one line by dropping the final comma in this line.

2021-11-29 09:20 UTC, hakonanes commented on orix/tests/test_crystal_map.py
> +        expected_o1 = xmap1.orientations
Why two lines? I would revert to one line, also in the change below.

2021-11-29 09:49 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +    oc = Orientation(o.data)
This would be a nice improvement.

2021-11-29 09:51 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +    o = Misorientation.random((3, 2))
Good spot! Updated.

2021-11-29 09:55 UTC, harripj commented on orix/tests/test_crystal_map.py
> +        expected_o1 = xmap1.orientations
Not sure why this happened... updated!

2021-11-29 10:06 UTC, harripj commented on orix/plot/rotation_plot.py
> +    def transform(self, xs, fundamental_region=None):
No problem with this. `_get_region_extent` and `_correct_aspect_ratio` also within `plot/rotation_plot.py` use `fundamental_region`, perhaps they should all be consistent? I am not sure whether there is a difference between region and zone in orix, would you be be able to shed some light on this if possible?

2021-11-29 10:16 UTC, harripj commented on orix/plot/rotation_plot.py
> +                    fundamental_region = OrientationRegion.from_symmetry(xs.symmetry)
I think for `Orientation` this won't work as `xs.symmetry` returns just a single `Symmetry` which is iterable and then gets unpacked into the tuple. `xs._symmetry` should return the correct tuple though, eg. `(C1, Th)`? This will, however, be inverted for the default arguments for `OrientationRegion.from_symmetry(s1, s2=C1)`.

2021-11-29 10:20 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        Misorientation
`Orientation.map_into_symmetry_reduced_zone()` must return an `Orientation` instance.

We have a separate docstring for `Orientation.set_symmetry()` because we *have* to override `Misorientation.set_symmetry()` anyway due to the different number of parameters it accepts. With `map_into_symmetry_reduced_zone()` we don't have to do this, and I think we should keep it this way to not increase the number of docstrings to maintain. The docstring is inconsistent with `Orientation`, but I think it should be clear *enough* for the user. What do you think?

2021-11-29 10:22 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        err_message = "Value must be a tuple with two Symmetry instances."
I believe that is what @pc494 means, yes.

2021-11-29 10:24 UTC, harripj commented on orix/plot/rotation_plot.py
> +    def transform(self, xs, fundamental_region=None):
I have just noticed that whilst `(Mis)Orientation` DS use fundamental zone, within the function body they use `fundamental_region`. This leaves is us with the case in `RotationPlot.scatter` where `fundamental_zone=fundamental_region`, which is perhaps not ideal. I can remove the kwarg for now, but perhaps this should be cleared up in the future?

2021-11-29 10:24 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                    fundamental_region = OrientationRegion.from_symmetry(xs.symmetry)
I've tested that this works. It works because `tuple(Orientation.symmetry)` becomes a 1-tuple which is passed to `s1`.

2021-11-29 10:27 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +    def transform(self, xs, fundamental_region=None):
Ouch, my bad... I'd prefer to rename everything to `zone` in `RotationPlot`. This does not break any API, since the methods you point to are private.

2021-11-29 10:32 UTC, hakonanes commented
One of the user guide notebooks have cell output stored and so must be re-uploaded using the new API. The other notebooks using `set_symmetry()` will after this PR show the deprecation warning, but still work as expected. I'll deal with this in a separete PR #246.

2021-11-29 10:33 UTC, harripj commented on orix/quaternion/orientation.py
> +        Misorientation
Sounds okay to me. I think it should be okay for the user.

2021-11-29 10:35 UTC, harripj commented on orix/plot/rotation_plot.py
> +    def transform(self, xs, fundamental_region=None):
No sweat, and leave as `fundamental_region` in `Orientation.scatter` or change to `zone` as well?

2021-11-29 10:40 UTC, harripj commented on orix/quaternion/orientation.py
> +        err_message = "Value must be a tuple with two Symmetry instances."
Okay, I have assigned the errors in place and they read "Value must be a 2-tuple of Symmetry objects."

2021-11-29 10:49 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +    def transform(self, xs, fundamental_region=None):
The variables in the code can be renamed to `fundamental_zone` as well!

2021-11-29 10:49 UTC, harripj commented on orix/plot/rotation_plot.py
> +                    fundamental_region = OrientationRegion.from_symmetry(xs.symmetry)
This works for `C1` for me, but not other `Symmetry` with more than one transformation:
```python
from orix.quaternion.symmetry import Th, C1
from orix.quaternion import Orientation

o1 = Orientation.random()
o1.symmetry = C1
tuple(o1.symmetry)
>>> (Symmetry (1,)
    [[1. 0. 0. 0.]],)  # this is okay

o2 = Orientation.random()
o2.symmetry = Th
tuple(o2.symmetry)
>>> (Symmetry (1,)
    [[1. 0. 0. 0.]], Symmetry (1,)
    [[0. 0. 0. 1.]], Symmetry (1,)
    [[0.5 0.5 0.5 0.5]], Symmetry (1,)
    [[-0.5 -0.5  0.5  0.5]], Symmetry (1,)
    [[-0.5  0.5 -0.5  0.5]], Symmetry (1,)...  # I don't think this will work

tuple(o2._symmetry)
>>> (Symmetry (1,) 1
    [[1. 0. 0. 0.]], Symmetry (24,) m-3
    [[ 1.   0.   0.   0. ]
     [ 0.   0.   0.   1. ]
     [ 0.5  0.5  0.5  0.5]
     [-0.5 -0.5  0.5  0.5]...)  # this works but C1 is now tuple[0]
```

The last case works but `C1` is now tuple[0], which is the wrong argument order for `OrientationRegion.from_symmetry(s1, s2=C1)`. Do you foresee this being a problem?

2021-11-29 11:41 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                    fundamental_region = OrientationRegion.from_symmetry(xs.symmetry)
You're right, I was too quick, sorry. This should work for all symmetry sizes, right?

```python
                symmetry = xs.symmetry
                if not isinstance(symmetry, tuple):
                    symmetry = tuple((symmetry,))
                fundamental_region = OrientationRegion.from_symmetry(*symmetry)
```

2021-11-29 11:54 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
I have to correct myself here, this check is naive and won't work for all zones. We already have [a check for this](https://github.com/pyxem/orix/blob/73a8127b67a707bba5a423d9f18853e403055d06/orix/quaternion/orientation_region.py#L172-L182) implementing `<` for (Mis)Orientation (left) and OrientationRegion (right). Therefore the check must be

```python
import numpy as np
[...]
            # if xs is out of fundamental region, calculate symmetry reduction
            if not np.all(xs < fundamental_region):
                xs = xs.map_into_symmetry_reduced_zone()
```

2021-11-29 11:58 UTC, harripj commented on orix/plot/rotation_plot.py
> +                    fundamental_region = OrientationRegion.from_symmetry(xs.symmetry)
Yes this should work no problem. I will update the code!

2021-11-29 12:01 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
This check performs a `Quaternion(self).dot_outer(other.data)`, which shouldn't be too time consuming, since `self.data` contains 14 rotations at most for the point groups.

2021-11-29 12:19 UTC, harripj commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
Makes sense. Do you want to commit this? Happy to do it also. Could also avoid the import with `(xs < fundamental_region).all()`.

2021-11-29 14:57 UTC, hakonanes requested changes
I've got two final comments, after that I'll approve and wait for Phillip to approve and merge!

2021-11-29 14:57 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                raise TypeError("Fundamental_zone is not an OrientationRegion object.")
```suggestion
                raise TypeError("fundamental_zone is not an OrientationRegion object.")
```

2021-11-29 14:57 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
This snippet should test this bit

```python
>>> import numpy as np
>>> from orix.quaternion import Orientation, OrientationRegion, symmetry
>>> ori = Orientation((1, 0, 0, 0), (0.5, 0.5, 0.5, 0.5))
>>> ori.symmetry = symmetry.D6
>>> fz = OrientationRegion.from_symmetry(ori.symmetry)
>>> assert np.allclose(ori < fz, (True, False))
>>> ori.scatter()
```

I cannot get the positions of the scatter points from the returned figure (I tried looking around in `figure.axes[0].collections[1]` which is a `Path3DCollection` with the two scatter points), but couldn't find the 3D coordinates to test whether the last point is actually plotted inside the fundamental zone. But it is at least on my machine...

2021-11-29 15:41 UTC, harripj commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
We can get them from the plot as:
```python
from orix.vector import Vector3d
fig = ori.scatter(return_figure=True)
# pathCollection
pc = fig.axes[0].collections[1]
x, y, z = pc._offsets3d
vec = Vector3d(np.column_stack((x, y, z))
```
if that helps! Not sure how to go about testing whether vectors are within `OrientationRegion` though!

2021-11-29 15:49 UTC, hakonanes commented on orix/plot/rotation_plot.py
> +                xs = xs.map_into_symmetry_reduced_zone()
There you go, great! Then I'd write the test as

```python
>>> import numpy as np
>>> from orix.quaternion import Orientation, OrientationRegion, symmetry
>>> ori = Orientation((1, 0, 0, 0), (0.5, 0.5, 0.5, 0.5))
>>> ori.symmetry = symmetry.D6
>>> fz = OrientationRegion.from_symmetry(ori.symmetry)
>>> assert np.allclose(ori < fz, (True, False))
>>> fig = ori.scatter(return_figure=True)
>>> xyz_symmetry = fig.axes[0].collections[1]._offsets3d
>>> ori.symmetry = symmetry.C1
>>> fig2 = ori.scatter(return_figure=True)
>>> xyz = fig.axes[0].collections[1]._offsets3d
>>> assert not np.allclose(xyz_symmetry, xyz)
```

Here we've established that there's at least a change in where the points are plotted in the 3d axes.

2021-11-30 11:27 UTC, pc494 commented
Approved - Merging.

2021-11-30 11:28 UTC, merged