Add symmetry arg to Orientation __init__ and override methods to maintain symmetry
pyxem/orix pull request #252
Opened 2021-12-15 10:52 UTC by harripj

#### Description of the change
As mentioned in #241 and https://github.com/pyxem/orix/pull/251#discussion_r768914214 we should introduce a `symmetry` argument to `Orientation.__init__` which would allow the user to set the symmetry of the instance at instantiation. This is already the case for the class methods, eg. `from_euler` etc., so this PR would just be bringing the syntax together.

A secondary goal of this PR is to maintain the `symmetry` of a `(Mis)Orientation` instance when operating on it. This is done by overriding the methods in either class and docstrings will be inherited. Currently the following methods are overridden and maintain symmetry:
`Misorientation`:
- `__getitem__`

`Orientation`:
- `__invert__`
- `__neg__`

This PR proposes that the following are added:
`Misorientation`:

- `reshape`
- `transpose`
- `flatten`
- `squeeze`

I also think that potentially `unique` should be overridden to maintain symmetry, and in fact possibly should account for symmetry, but would like to know what other people think about this.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)
- [x] Add symmetry arg to `Misorientation.__init__`
- [x] Override `Misorientation` `reshape` `transpose` `flatten` and `squeeze` methods to maintain symmetry
- [x] Update dead link in `contributing.rst`
- [ ] Update changelog
- [ ] Change notebooks to demonstrate this syntax

#### Minimal example of the bug fix or new feature
```python
>>> from orix.quaternion import Orientation
>>> from orix.quaternion.symmetry import C2
>>> o = Orientation(data, symmetry=C2)
>>> o.symmetry
Symmetry (2,) 2
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]]

>>> o = Orientation.random((5, 4))
>>> o.symmetry = C2
>>> o1 = o.reshape(4, 5)
>>> o1.symmetry
Symmetry (2,) 2
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]]

```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-12-15 11:46 UTC, hakonanes commented
Sorely needed update, since the loss of symmetry has surprised myself many times before, and surely some other users!

Will review once you mark it as ready for review. I hope we can get it in for v0.8, that is merged within the week end?

> I also think that potentially unique should be overridden to maintain symmetry, and in fact possibly should account for symmetry, but would like to know what other people think about this.

This should be as simple as (1) mapping them into the fundamental zone, (2) finding the indices into the initial orientation array of the unique orientations within the zone using `Rotation.unique(return_index=True)`, and (3) returning the initial orientations in the unique indices, right? I suggest to leave this for its own PR.

2021-12-15 15:55 UTC, harripj commented
@pc494 no it's okay. Once this is merged we can make some small changes to the docs in #251, but this can be done after the fact in a new small PR!

2021-12-15 15:56 UTC, harripj commented
@pc494 I will do some small changes to the docs in #251 in this PR- it's all good!

2021-12-15 20:31 UTC, harripj commented
I have just updated the notebooks from #251 to use the `symmetry` arg in `Orientation.__init__()`. I would appreciate it if @hakonanes you could have a quick look over it to make sure everything still runs smoothly on your machine! (Everything looks fine on my machine but I don't have the data in "clustering_orientations.ipynb" to hand to check for sure).

@pc494 this means that it is good for review when you get a chance!

2021-12-16 15:42 UTC, pc494 requested changes
A set of docstrings to add and then this is good to merge.

2021-12-16 15:42 UTC, pc494 commented on orix/quaternion/orientation.py
> +        return m
Each of these should have one line docstrings.

2021-12-16 17:00 UTC, pc494 commented on orix/quaternion/orientation.py
> +        return m
I had assumed overwriting methods meant you didn't inherit docstrings... Will double check and get back to you.

2021-12-16 17:10 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return m
One way to find out is to add these to the list of `Orientation` methods in `reference.rst`, build the documentation locally, and inspect the `Orientation` section in the API reference in the local HTML files in the browser (as per the [contributing guide](https://orix.readthedocs.io/en/stable/contributing.html#build-and-write-documentation)).

2021-12-16 17:16 UTC, pc494 commented on orix/quaternion/orientation.py
> +        return m
My minimum working examples suggests overwritting methods loses the docstrings (I also checked the call to super didn't help, although that's not in the image).

![do_docstrings_get_overwritten](https://user-images.githubusercontent.com/32455330/146418148-9e7c8a7c-7c64-469a-8ee6-b3c9586ed06a.png)

2021-12-16 17:27 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return m
Huh, this surprised me, as I thought base (parent) docstrings carried over when a new one wasn't written. Thank you for checking this, @pc494!

Then I think we should add docstrings for all methods, so they look nice in the API reference (and via IPython, Jupyter, etc.). We must be careful in the future to also update any "downstream" (read Orientation) docstrings when we update "upstream" (read Rotation) docstrings!

2021-12-16 17:32 UTC, pc494 commented on orix/quaternion/orientation.py
> +        return m
In general the best option is to overwrite as few methods as possible, but in this case the symmetry property does make that kind of difficult.

2021-12-16 17:34 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return m
Yes, that's the motivation behind parts of this PR: to maintain any properties the user would assume are maintained, like the symmetry, when transposing, reshaping, flattening, etc.

2021-12-16 17:52 UTC, hakonanes commented
If it's OK with you @harripj, I'll push the updated "Clustering orientations" notebook with your addition to this PR.

2021-12-16 17:53 UTC, hakonanes commented
The other two affected notebooks "Crystal map" and "Clustering across fundamental region boundaries" look good in the [documentation](https://orix--252.org.readthedocs.build/en/252/index.html) built from this PR.

2021-12-16 17:56 UTC, hakonanes commented
Other methods which could (not saying *should* here) be overwritten:
* `Orientation.mean()`
* `Orientation.stack()` (when the instances to stack are orientations with the same symmetry)
* `Orientation.__mul__()` perhaps? When two orientations of the same symmetry are multiplied, the symmetry can be kept?

2021-12-16 17:56 UTC, hakonanes commented
I'll review this tomorrow.

2021-12-16 17:59 UTC, harripj commented on orix/quaternion/orientation.py
> +        return m
So in the current state of the repo `Object3d.squeeze` has a docstring and `Misorientation.squeeze` does not. After building the docs the docstring for `Misorientation.squeeze` is inherited from `Object3d.squeeze`:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/16853829/146422767-510f245d-50e6-43a2-a4a9-1133498fca8f.png">

@pc494 I have tested your notebook and experience the same behaviour: `__doc__` remains `None` in the inherited method, but IPython correctly inherits the docstring:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/16853829/146423375-e6933791-5f5c-417c-b6cd-03408205311c.png">

(in fact in this case the docstring for `Orientation.flatten` is inherited from `Rotation.flatten` rather than `Object3d.flatten` and is why they are different, but the point is the same that IPython will inherit the docstrings. In fact if we decide to stick with inherited docstrings then we should remove the one for `Rotation.flatten`.)
So for the docs this isn't a problem, but the `__doc__` attribute isn't set for the inherited methods, and it is whether we mind this behaviour or not as it means less maintenance. From my POV I am always working with IPython and use the `?` operator regularly, whereas I never use `__doc__`, so I don't mind this but appreciate others may have different viewpoints. What do you all think?

2021-12-16 18:03 UTC, harripj commented
> If it's OK with you @harripj, I'll push the updated "Clustering orientations" notebook with your addition to this PR.

Yes of course, go ahead.

> Other methods which could (not saying should here) be overwritten:
> Orientation.mean()
> Orientation.stack() (when the instances to stack are orientations with the same symmetry)
> Orientation.__mul__() perhaps? When two orientations of the same symmetry are multiplied, the symmetry can be kept?

I was thinking about `stack` for sure, it makes sense to me, but only if _all_ of the inputs have the same symmetry. `mean` also makes sense, but `__mul__` seems to be more complex and I would have to do some more thinking/reading on it.

2021-12-16 18:44 UTC, pc494 commented
I think the approach in #254 would resolve most of these issues (docstring would be written once, and would be correct, code duplication would be kept to a minimum etc.) - I think it's probably easier to merge this and #253 first though and then I'll do the refactor separately.

2021-12-16 20:06 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return m
@harripj, good catch. Seems like the Python language with `__doc__` doesn't do any inspection, while IPython/Jupyter does some inspection and finds the docstring both with `?` and with `Shift` + `Tab` with the cursor within function parantheses.

2021-12-17 09:46 UTC, pc494 commented
The Ipython support is good enough for now, we can deal with the tidy ups elsewhere. I will resolve the conflicts (from merging #253) and merge this.

2021-12-17 10:00 UTC, hakonanes approved these changes
Looks great. I have a few small comments which aren't required but would be nice to change.

2021-12-17 10:00 UTC, hakonanes commented on CHANGELOG.rst
> +- `Orientation`-based classes now accept a `symmetry` argument for `__init__()`.
```suggestion
- `Orientation` based classes now accept a `symmetry` argument upon initialisation.
```

2021-12-17 10:00 UTC, hakonanes commented on CHANGELOG.rst
> +  object.
```suggestion
  `Misorientation` based classes to maintain the initial symmetry of the returned
  instance.
```

2021-12-17 10:00 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    m = Misorientation.random((4, 5))
Why not set the symmetry in this line?

2021-12-17 10:00 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    for s1, s2 in zip(m1.symmetry, symmetry):
I'd use `np.allclose(m1.symmetry.data, symmetry.data)` here instead.

2021-12-17 14:44 UTC, pc494 commented
Sorry, I had forgotten that @hakonanes had a review pending. This is good to go as far as I am concerned, so I will leave @hakonanes to merge.

2021-12-17 17:46 UTC, hakonanes commented
If it's OK with everyone, I'll apply the changes suggested in the review, fix the conflicts and merge.

2021-12-17 19:14 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    m = Misorientation.random((4, 5))
It's not overwritten...

2021-12-17 19:14 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +    for s1, s2 in zip(m1.symmetry, symmetry):
Nevermind, this makes sense with the symmetry tuple.

2021-12-17 19:15 UTC, hakonanes commented
Will merge when checks pass.

2021-12-17 19:20 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        return m
See https://github.com/pyxem/orix/pull/252#issuecomment-996082199

2021-12-17 19:20 UTC, merged

2021-12-17 22:20 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +    m = Misorientation.random((4, 5))
Sorry for the delay, I wasn't very available today. But yes, perhaps we should add a `symmetry` argument to `random` in the future.