remove deprecated import convention (kh)
pyxem/orix pull request #259
Opened 2021-12-20 13:33 UTC by pc494

#### Description of the change
Removing a deprecation in advance of 0.8, see #230. Will let the CI find the tests that need removing.

#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2021-12-20 15:32 UTC, hakonanes requested changes
Will merge when the suggested change and a black run is done!

2021-12-20 15:32 UTC, hakonanes commented on CHANGELOG.rst
> +- `fromo_euler()' no longer accepts "Krakow_Hielscher" as a convention, use "MTEX" instead.
```suggestion
- `from_euler()` no longer accepts "Krakow_Hielscher" as a convention, use "MTEX" instead.
```

2021-12-20 18:21 UTC, hakonanes commented
Will merge after checks pass.

2021-12-20 18:22 UTC, hakonanes approved these changes

2021-12-20 18:23 UTC, hakonanes commented
Will also delete the branch after it's merged.

2021-12-20 18:29 UTC, merged

2021-12-21 10:08 UTC, pc494 commented
This was very lazy of me, thank you for fixing @hakonanes

2021-12-21 10:08 UTC, hakonanes commented
No problem!