Directionality in `Euler` methods
pyxem/orix pull request #294
Opened 2022-02-23 17:32 UTC by harripj

#### Description of the change
As discussed in #249 the default `direction` kwarg in `from_euler` methods is currently `crystal2lab`, but should be `lab2crystal`. This is the Bunge convention as described in ref. [1] of #249 and opposite of the convention used by [MTEX](https://mtex-toolbox.github.io/MTEXvsBungeConvention.html). Previously a `convention` parameter was also optional, this has been removed as it is potentially confusing.

This PR aims to make a more consistent and easy-to-follow definition of `Rotation` from Euler angles by deprecating the `convention` parameter and relying only on `direction`, as the two have overlap. `'mtex'` is offered as a supported direction for those users coming from MTEX. `object_type="argument"` has been created `deprecated` and currently removes the argument.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from orix.quaternion import Rotation
import numpy as np
e = np.deg2rad((45, 30, 90))
        
r_mtex = Rotation.from_euler(e, direction="mtex")
r_c2l = Rotation.from_euler(e, direction="crystal2lab")
r_l2c = Rotation.from_euler(e, direction="lab2crystal")
r_default = Rotation.from_euler(e)

assert np.allclose(r_default.data, r_l2c.data)
True

assert np.allclose(r_mtex.data, r_c2l.data)
True

assert np.allclose((r_l2c * r_c2l).angle.data, 0)
True

Rotation.from_euler(e, convention='bunge')
VisibleDeprecationWarning: Argument `convention` is deprecated and will be removed in version 1.0. Use `direction` instead.
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-02-24 09:51 UTC, hakonanes requested changes
I like the solution adopted in this PR. Neat extension of the `@deprecated` decorator for arguments.

Note that this PR changes the API for users who've set the `direction` themselves in `from_euler()`, that is we won't warn those users in a release before making the change, so they can adapt. The default behaviour stays the same (when not setting `direction`) so the API is not changed for users who don't set the `direction`.

I'm OK with releasing this in a 0.8.3 patch to get it out as quickly as possible, so users can adapt before 1.0. Another solution is to leave the meaning of the two `direction` options, but warn that they will swap in 1.0, and release this in 0.8.3.

The PR is WIP, but since I'm looking at it, I'll just mention:
* Should update the changelog with an entry under "Changed" stating that the meaning of the two (in addition to "mtex") options in `direction` has changed
* `removal` should be set to 1.0, since we decided we won't release a 0.9
* Two lines in the tests aren't covered (and can thus be removed?): https://coveralls.io/builds/46820525

2022-02-24 11:33 UTC, harripj commented
Yes this is currently a breaking change for those who have specified `direction`. In my mind we could either leave the codebase as is and add a deprecation warning, as you mentioned, to change in 1.0, or make the change now and add a one-time warning that 'direction` has swapped for anyone using `from_euler()` which is removed in 1.0.

I would be happy with either, but favour the breaking patch and warning.

2022-02-24 13:21 UTC, hakonanes commented
> I have thought about it more and this goes against semantic versioning. I now thing we should deprecate, warn of the change and make the breaking change in 1.0.

One shouldn't break semver, but I'm OK with doing it if not doing it if the break is "mild" and (1) blocks development or (2) takes unproportional maintainer effort. In this case, I'd say (1, 2) isn't met, so I'm fine with doing the change first in 1.0.

2022-02-24 15:32 UTC, harripj commented
I am still a bit confused whether you mean release this in a minor 0.8.3 patch or deprecate now and change for 1.0!

So I have made the breaking change here. I think the deprecation should be done in another PR, and this PR can be left until the 1.0 release.

2022-02-24 16:07 UTC, harripj commented
> we should release the warning and/or break in a 0.8.3 patch.

Sounds like a plan! 👍

2022-02-24 18:22 UTC, pc494 commented
just as an addition on semvar:

"Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

[source here](https://semver.org/#spec-item-4).

2022-02-24 18:22 UTC, pc494 commented
will review this tomorrow to check that I'm 100% on the convention change uses discussion, but am fairly certainly it'll be an easy merge

2022-02-27 15:55 UTC, pc494 requested changes
This looks good, just needs a CHANGELOG entry, ideally pointing out that this version will now give different (correct) results.

2022-02-28 08:54 UTC, harripj commented
For what it is worth I think that this would be best suited to a `0.9` release that we have been considering https://github.com/pyxem/orix/pull/295#issuecomment-1050296527.

2022-02-28 09:46 UTC, pc494 approved these changes
Great :D, will let @hakonanes merge

2022-02-28 14:20 UTC, hakonanes requested changes
This improves the API and makes it clearer.

I'm sorry for being vague about what I think we should do regarding deprecation. See my comments on this.

Otherwise, I've got a few docstring suggestions and such.

2022-02-28 14:20 UTC, hakonanes commented on orix/quaternion/orientation.py
> +            "lab2crystal" or "crystal2lab". If "MTEX" is provided then
Is it useful to specify that "lab2crystal" is the Bunge convention?

Should add a `"lab2crystal" (default)`.

2022-02-28 14:20 UTC, hakonanes commented on orix/quaternion/rotation.py
> +from orix._util import deprecated
This is now unused.

It seems like you @harripj and @pc494 are in favor of not deprecating the `convention` argument. I've never used the argument myself (the `direction` argument I've used a couple of times), but there might be users who do. They will get a `TypeError` with 0.9. I prefer to emit a warning in 0.9 instead, stating that it will be removed in 1.0. This takes little effort from our end (since you've already done the work, @harripj), we just have to remember to remove the warning in 1.0.

I'm sorry for being vague on what I thought was the best solution here.

I'd appreciate it if you could just quickly state here whether you still want to remove it.

2022-02-28 14:20 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +def test_from_euler_convention_raises():
If we go for deprecation, a comment like "# TODO: Remove in 1.0" would be good.

2022-02-28 14:20 UTC, hakonanes commented on orix/tests/quaternion/test_rotation.py
> +    # def test_convention_arg
I'd remove this?

2022-02-28 14:20 UTC, hakonanes commented on orix/tests/quaternion/test_rotation.py
> +    def test_conv_from_raises(self, e):
If we don't go for deprecation, I'd remove any test ensuring that passing the `convention` argument raises an error.

2022-02-28 14:20 UTC, hakonanes commented on orix/tests/test_util.py
> +            @deprecated(
If we don't go for deprecation, these tests test internal utilities that aren't in use. Will they be in the future? If so I think we should keep the functionality. If not, we should remove it. What do you think?

2022-02-28 14:24 UTC, harripj commented on orix/_util.py
> +            name = self.argument
No you are right, these are only useful for development. In fact this causes a bit of a headache when it comes to testing. As it should only be used for development, perhaps we could just remove the `if` statement, in which case `argument` defaults to `None`, and assume that if used the developer will read the deprecation warning and correct this `None`?

2022-02-28 14:31 UTC, harripj commented
@hakonanes @pc494 from my end I am happy to deprecate the `convention` argument in this PR but correct the `lab2crystal` error. That way any use of `convention` will not throw an error. I think that the `direction`s should be corrected in this PR (and not deprecated and warned to change in a future release).

From my end I don't use the other `pyxem` libraries, so this is not much of a headache for me, but I think that you both, as developers for dependent libraries, are better suited to decide whether to deprecate this now and remove later or remove now.

2022-02-28 14:47 UTC, hakonanes commented on orix/_util.py
> +            name = self.argument
Yes, I think this is safe to do!

2022-02-28 14:53 UTC, hakonanes commented
> @hakonanes @pc494 I am happy to deprecate the `convention` argument in this PR but correct the `lab2crystal` error.

Yes, that is exactly what I meant, sorry again for not being 100% clear on which of the two changes to deprecate.

> From my end I don't use the other `pyxem` libraries, so this is not much of a headache for me, but I think that you both, as developers for dependent libraries, are better suited to decide whether to deprecate this now and remove later or remove now.

Thankfully, we only pass Euler angles to `Rotation.from_euler()` in kikuchipy, so as long as the default behaviour doesn't change, this PR has no effect on that package. It's with regards to end users of orix I'm (mildly) concerned: basically, we haven't broken public API arguments without warning previously (as far as I can tell), and it would be good to keep it that way.

2022-03-01 12:30 UTC, harripj commented on orix/tests/quaternion/test_orientation.py
> +def test_from_euler_convention_raises():
Good idea!

2022-03-01 14:05 UTC, harripj commented
@pc494 @hakonanes I have updated the PR to deprecate the `convention` argument in `0.9` for removal in `1.0`, as discussed to not break others' code, so want to check this is okay with you both.

2022-03-01 14:29 UTC, pc494 commented
Broadly (pre-1.0) I lean more towards breaking stuff so I'm absolutely fine with this as implemented and am merging.

2022-03-01 14:30 UTC, merged