Remove scalar class
pyxem/orix pull request #301
Opened 2022-03-01 15:26 UTC by harripj

#### Description of the change
I made a fairly annoying mistake where I deleted my fork instead of deleting my branch after the last PR. I am sorry for this as it has made a bit of a mess. On the plus side I had a local copy of the code so reinstated my fork but now need to make new PR.

This PR is a direct follow on from #295.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-03-02 10:25 UTC, hakonanes requested changes
Fantastic PR. Another benefit of removing `Scalar` is that the code is easier to read and write.

Have to two suggestions only, one request and one question.

No problem on my end from you deleting your fork. The git diff is still available in the [old PR](https://github.com/pyxem/orix/pull/295/files), even though it isn't possible to re-open it, so if you didn't have a local copy, you would still be able to copy/paste the contents of the files in the old PR to make a new one.

2022-03-02 10:25 UTC, hakonanes commented on CHANGELOG.rst
> +- `orix.scalar.Scalar` class has been removed and the data held by `Scalar` is now
This should be moved to a "Removed" section as per [Keep a Changelog](https://keepachangelog.com/en/1.1.0/#how).

2022-03-02 10:25 UTC, hakonanes commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
Why is this test needed?

2022-03-02 10:49 UTC, harripj commented on CHANGELOG.rst
> +- `orix.scalar.Scalar` class has been removed and the data held by `Scalar` is now
Good spot!

2022-03-02 10:51 UTC, harripj commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
Sorry, didn't realize that this was there. VS Code must have auto-added the file encoding when I made the file.

2022-03-02 10:54 UTC, hakonanes commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
I mean the test, why is it needed?

2022-03-02 11:11 UTC, harripj commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
From a clean build I don't think it is, however I ran into an error where the scalar.py class had been removed but was still cached, so it would actually try to import. You are right though, we shouldn't need this for the build. I will remove it.

2022-03-02 12:09 UTC, harripj commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
It was cached in `__pycache__` in the `orix.scalar` directory, but I have completely removed this module in the PR. I haven't come across the problem since deleting the directory (and so `__pycache__`).

2022-03-03 08:54 UTC, hakonanes commented on orix/tests/test_misc.py
> +# -*- coding: utf-8 -*-
OK, thanks for checking, let's this doesn't become an issue for others.

2022-03-03 08:57 UTC, hakonanes approved these changes
I'm happy with this removal. Since I've contributed to this PR, I'll leave it up to @pc494 to merge.

2022-03-03 10:23 UTC, merged