Angle with outer
pyxem/orix pull request #302
Opened 2022-03-01 15:28 UTC by harripj

#### Description of the change
As mentioned in #301 I made the mistake of deleting my fork. As a result a new PR must be made from the unmerged branch.

This PR is a direct follow on from #298 .

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-03-02 10:41 UTC, hakonanes requested changes
Very good re-use of existing functionality. Also good additions to the test by checking the diagonal.

Non-inline requests:
* Add method to API reference
* Add note to "Added" in changelog

We must remember to update "Returns" to a NumPy array if the PR removing the scalar module is merged before this.

Since this computation can be memory intensive, I think we should still allow `lazy`, `chunk_size` and `progressbar`, even though it is not possible with `angle_with()` etc. We should keep in mind that supporting more operations with `dask` to keep memory in check could be necessary in the future.

2022-03-02 10:41 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        another instance.
Could you add

```python
See also
--------
angle_with_outer
```

above "Notes" and a simple usage example in an "Examples" section below "Notes"?

2022-03-02 14:30 UTC, harripj commented
I have just added `angle_with_outer` to `Rotation` as well, as it was missing.

It has brought up an interesting problem, however. Due to the different implementations of `dot_outer` between `Orientation` and `Rotation`, the shape of the output is inconsistent. We should address this. This comes back in part to @pc494's previous comment that we should reuse code where possible #254.

An example of the current problem:
```python
>> from orix.quaternion import Orientation Rotation
>>> r1 = Rotation.random((5,))
>>> r2 = Rotation.random((6,))
>>> dist_r = r1.angle_with_outer(r2)
>>> dist_r.shape
(5, 6)

>>> o1 = Orientation(r1)
>>> o2 = Orientation(r2)
>>> dist_o = o1.angle_with_outer(o2)
>>> dist_o.shape
(6, 5)

>>> np.allclose(dist_r.data, dist_o.data.T)
True
```

@hakonanes @pc494 what do you think? Should the shape be `(self.shape, other.shape)` or the other way around?

2022-03-03 09:01 UTC, hakonanes commented
> Should the shape be (self.shape, other.shape) or the other way around?

Well spotted. I suggest to use the shape returned by the parent class `Rotation`, since this was implemented first. A test assuring that shapes returned from equivalent `Rotation` and `Orientation` methods would be good in this case.

2022-03-06 10:53 UTC, hakonanes requested changes
Another very good addition to the rotation classes. I think this is in good shape except for my two minor requests.

I anticipate to approve and merge after these two have been addressed.

2022-03-06 10:53 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        Scalar
These can now be updated since #301 is merged.

2022-03-06 10:53 UTC, hakonanes commented on CHANGELOG.rst
> +Added
We should add a note to "Fixed" explaning that results from `Orientation.dot_outer()` are now `self.shape + other.shape`, in line with results shape from `Rotation.dot_outer()`. I think "Fixed" instead of "Changed" because the shapes from both classes should be equal.

2022-03-07 11:20 UTC, harripj commented on CHANGELOG.rst
> +Added
Good idea, I will add it.

2022-03-07 11:55 UTC, hakonanes commented on CHANGELOG.rst
> +- The results from `Orientation.dot_outer()` are now now returned as
```suggestion
- The results from `Orientation.dot_outer()` are now returned as 
```

2022-03-07 12:25 UTC, hakonanes approved these changes
I find this a very good addition! Merging.

2022-03-07 12:25 UTC, merged