Speed up `dot` and `dot_outer` by not calling `unique` for identical `Symmetry`
pyxem/orix pull request #303
Opened 2022-03-01 15:51 UTC by harripj

#### Description of the change
As discussed in #296. The use of `unique` is slow and causes a significant performance hit when not needed. Currently in `Orientation.dot` and `.dot_outer` unique values of the two symmetries are computed, however when the two `Symmetry` are identical, eg. both `Th`, then this call to unique is not needed. I suggest we add a check to the function to test whether the two `Symmetry` are unique, and if so avoid the `unique` call. This may be further extended to related symmetries, eg. `Oh` and `Th`.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from orix.quaternion import Orientation, Rotation, symmetry
import numpy as np

o1 = Orientation.random((6, 4))
o2 = Orientation.random((6, 4))

o1.symmetry = symmetry.Th
o2.symmetry = symmetry.Th

def dot(o1, o2):
        """Symmetry reduced dot product of orientations in this instance
        to orientations in another instance, returned as
        :class:`~orix.scalar.Scalar`.
        See Also
        --------
        dot_outer
        """
        symmetry = o1.symmetry.outer(o2.symmetry).unique()
        misorientation = o2 * ~o1
        all_dot_products = Rotation(misorientation).dot_outer(symmetry).data
        highest_dot_product = np.max(all_dot_products, axis=-1)
        return highest_dot_product

def dot_skip_unique(o1, o2):
        """Symmetry reduced dot product of orientations in this instance
        to orientations in another instance, returned as
        :class:`~orix.scalar.Scalar`.
        See Also
        --------
        dot_outer
        """
        if o1.symmetry == o2.symmetry:
                symmetry = o1.symmetry
        else:
                symmetry = o1.symmetry.outer(o2.symmetry).unique()
        misorientation = o2 * ~o1
        all_dot_products = Rotation(misorientation).dot_outer(symmetry).data
        highest_dot_product = np.max(all_dot_products, axis=-1)
        return highest_dot_product

>>> d = dot(o1, o2)
>>> dsu = dot_skip_unique(o1, o2)
>>> np.allclose((d - dsu).angle.data, 0)
True

>>> %timeit dot(o1, o2)
1.77 ms ± 107 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit dot_skip_unique(o1, o2)
280 µs ± 8.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

#### For reviewers

- [x] The PR title is short, concise, and will make sense 1 year later.
- [x] New functions are imported in corresponding `__init__.py`.
- [x] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-03-02 11:01 UTC, hakonanes requested changes
This is a great speed-up and good additions to the tests.

In addition to the other requests, could you update the changelog?

2022-03-02 11:01 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        # this is checking the symmetry ids
I suggest we add a `Symmetry.__eq__` method which returns True if `data ` and `improper` are equivalent in a try/except? Checking `data` with `numpy.allclose()` will ensure that the shapes are identical as well. I don't think the `name` needs to be identical.

2022-03-02 11:45 UTC, harripj commented on orix/quaternion/orientation.py
> +        # this is checking the symmetry ids
Perhaps this can be added to the `Rotation` class instead?

2022-03-02 11:47 UTC, hakonanes commented on orix/quaternion/orientation.py
> +        # this is checking the symmetry ids
Yes, even better.

2022-03-03 08:45 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    symmetries = [C1, Ci,  # triclinic
Thanks for this, much cleaner.

2022-03-03 08:55 UTC, harripj commented
In fact I believe this can be generalised further by checking whether either `Symmetry` exists in the subgroup of the `other`.

```python
all_sym_sg = []

for s1 in symmetry._groups:
    res = []
    for s2 in s1.subgroups:
        # outer of symmetry with its subgroups
        u = s1.outer(s2).unique()
        # assert that unique is same size as main symmetry
        if u.size != s1.size:
            res.append(False)
        else:
            # check that there is no difference between unique
            # and main symmetry
            diff = (s1 * ~u).angle.data
            if np.allclose(diff, 0):
                res.append(True)
            else:
                res.append(False)
    all_sym_sg.append(all(res))
all(all_sym_sg)
True
```

2022-03-03 16:53 UTC, pc494 reviewed
I've got no comments on this, the coverage has dropped though - happy to let @hakonanes lead reviewing on this.

2022-03-03 20:44 UTC, harripj commented
> I've got no comments on this, the coverage has dropped though.

Thanks, I will get on it.

2022-03-04 10:01 UTC, harripj commented
I have written a function that aims to test whether one symmetry exists within the subgroup of the other, and hence avoid the unique operation:

```python
def get_unique_symmetry_elements(sym1, sym2):
     """Returns the unique symmetry elements between two `Symmetry`."""
     if sym1 == sym2:
         return sym1
     # test whether either symmetry is in the subgroup of the other
     sym2_in_sym1_sg = True if sym2 in sym1.subgroups else False
     sym1_in_sym2_sg = True if sym1 in sym2.subgroups else False
     # if either one of in_sym1 or in_sym2 is satisfied then return the
     # larger parent group
     if sym2_in_sym1_sg + sym1_in_sym2_sg == 1:
         if sym2_in_sym1_sg:
             return sym1
         else:  # in sym2
             return sym2
     else:
         # either no common parent
         # or both in_sym1 and in_sym2 are True, in which case ambiguous
         return sym1.outer(sym2).unique()
```

This works in the large majority of cases, however, for example, in the case of some symmetries:
```python
>>> sym1 = symmetry.C2h
>>> sym2 = symmetry.S4

>>> sym1 in sym2.subgroups, sym2 in sym1.subgroups
True, True

>>> sym1.outer(sym2).unique()
Symmetry (4,) 
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [-1.  0.  0.  0.]]

>>> sym2.outer(sym1).unique()
Symmetry (4,) 
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
```
ie. the `unique` value between these sets of symmetry operations is order dependent. Any thoughts?

2022-03-04 10:27 UTC, pc494 commented
```
>>> sym1 in sym2.subgroups, sym2 in sym1.subgroups
True, True
```

This feels like it's probably at least part of the bug as I doubt two groups can both be subgroups of one another.

2022-03-15 09:10 UTC, hakonanes commented
I'm wondering if we should focus on the operations themselves in this PR and leave the equality in subgroups for a later PR?

> the unique value between these sets of symmetry operations is order dependent. Any thoughts?

Hm, sorting of operations can be done using [`numpy.lexsort()`](https://numpy.org/doc/stable/reference/generated/numpy.lexsort.html#numpy.lexsort):

```python
>>> import numpy as np
>>> from orix.quaternion.symmetry import C2h, S4
>>> C2h[np.lexsort(C2h.data)]
Symmetry (4,) 
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [-1.  0.  0.  0.]]
>>> S4[np.lexsort(S4.data)]
Symmetry (4,) 
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
```

Don't know whether this helps, though.

2022-03-19 17:11 UTC, harripj commented
> This feels like it's probably at least part of the bug as I doubt two groups can both be subgroups of one another.

This makes sense to me. In fact the `_differentiator` of both symmetries are the same, which doesn't appear to make sense.

Looking at the symmetry stereographic projections halfway down [this page](http://xrayweb.chem.ou.edu/notes/symmetry.html) it appears as through the rotations between `S4` and `C4` should be the same (different of course as to whether the rotations are improper (circles vs crosses in figure)). The rotational elements of `C2h` do not look as though they match `S4`, so I am surprised that the differentiators between `S4` and `C2h` are identical.

2022-03-21 12:58 UTC, hakonanes commented
Thanks for making this notebook. It is the best visualization of the symmetry operations we have so far, and I suggest to add this as the default projection of a `Symmetry.plot()` method. What do others think?

What do you think about renaming the axes to "a" and "b" instead of "X" and "Y", since the operations are expressed in the crystal direct lattice reference system?

Now that others have started contributing more user guide notebooks, I suggest we restructure it as suggested in #248. What do you think?

2022-03-29 11:18 UTC, harripj commented
It looks like the answer was already written in an example in the comments: https://github.com/pyxem/orix/blob/0d975204a2298f59b71bb599524b62ab0b45d308/orix/quaternion/symmetry.py#L375-L377

Except that is the 4-fold rotoinversion around z is combined with `C2`, we get to what I believe is the expected result:
```python
>>> _4fold_rotoinversion_z = Symmetry([(1, 0, 0, 0), (0.5**0.5, 0, 0, 0.5**0.5)])
>>> _4fold_rotoinversion_z.improper = [0, 1]

>>> S4 = Symmetry.from_generators(C2, _4fold_rotoinversion_z)
>>> S4
Symmetry (4,) 
[[ 1.      0.      0.      0.    ]
 [ 0.      0.      0.      1.    ]
 [ 0.7071  0.      0.      0.7071]
 [-0.7071  0.      0.      0.7071]]

>>> S4.improper
array([False, False,  True,  True])

>>> S4.subgroups
[Symmetry (1,) 1
 [[1. 0. 0. 0.]],
 Symmetry (2,) 112
 [[1. 0. 0. 0.]
  [0. 0. 0. 1.]],
 ```

and itself is of course part of its subgroup.

2022-03-29 15:50 UTC, hakonanes requested changes
The speed-up and much more robusts tests are great!

I have a couple of questions. Also, could you add to the changelog stating that the S4 symmetry has been corrected?

2022-03-29 15:50 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +def get_unique_symmetry_elements(sym1, sym2):
Should this be public? If you don't anticipate to use it directly yourself, I say no. If yes, then a complete docstring explaining parameters and returns must be added. It should also then be added to the list of functions in the `symmetry` module in the reference API.

2022-03-29 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> +def test_from_euler_convention_mtex():
Why is this test added?

2022-03-29 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    T, Th, O, Td, Oh, get_unique_symmetry_elements,  # cubic
Put this on the next line, since it isn't a cubic point group.

2022-03-29 15:50 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    symmetry = all_symmetries
Could you explain how this fixture works? Is `symmetry == _groups`, or one element in `_groups`?

2022-03-29 16:08 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    symmetry = all_symmetries
This is one element in groups.

2022-03-29 16:08 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    T, Th, O, Td, Oh, get_unique_symmetry_elements,  # cubic
Thanks, will do.

2022-03-29 16:11 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    symmetry = all_symmetries
Does the fixture operate like `pytest.mark.parametrize()`, when a list is passed as `params`? This test is then executed number of times equal to elements in `_groups`?

2022-03-29 16:27 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +def get_unique_symmetry_elements(sym1, sym2):
Fantastic!

2022-03-29 16:49 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    symmetry = all_symmetries
Yes pretty much, this allows the parameterization to be written once and then used for each test which calls the fixture. https://docs.pytest.org/en/6.2.x/fixture.html#parametrizing-fixtures

2022-03-29 16:52 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    symmetry = all_symmetries
Cool, I haven't used a fixture in this way. Thanks for the explanation.

2022-03-29 16:52 UTC, hakonanes approved these changes

2022-03-30 14:42 UTC, harripj commented
Just a note on performance:
```python
>>> import orix
>>> from orix.quaternion.symmetry import Oh
>>> %timeit Oh == Oh
58.8 µs ± 784 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

>>> %timeit Oh in Oh.subgroups
10 ms ± 124 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

>>> %timeit Oh.outer(Oh).unique()
3.25 ms ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Checking subgroups is currently detrimental to perfoomance, I will add a boolean parameter to the `_get_unique_symmetry_elements` function to define whether subgroups are tested. This performance hit is probably due to computation of `_differentiators` and `subgroups` at run time. Perhaps these could be computed at instantiation in the future, which may help.

2022-03-30 15:05 UTC, hakonanes commented
> Perhaps these could be computed at instantiation in the future, which may help.

We would then have to make `Symmetry.data` immutable (unchangable). Alternatively, we could try to implement a check that updates `subgroups` whenever `data` changes. I don't know how to do such a thing, but it might be worth looking into it.

> Checking subgroups is currently detrimental to perfoomance

I assume the timings in the top comment still hold, roughly?

2022-03-30 15:16 UTC, harripj commented
> We would then have to make Symmetry.data immutable (unchangable).

This I am okay with, it is essentially the premise with which we implemented the hash. I'm not considering user-created symmetries for now.

> I don't know how to do such a thing, but it might be worth looking into it.

I suspect that this feature could be implemented with a setter, at least for the whole array.

> I assume the timings in the top comment still hold, roughly?

Yes, for identical symmetries. I think for this PR we can keep this identical symmetry check for the performance benefit. `_get_unique_symmetry_elements` by default now computes whether the symmetries are identical, and if not explicitly computes the `unique()` as at the moment this is faster than checking for a subgroup relationship. I have left the subgroup checking code there in the case where we could use it in the future.  Otherwise the implemented tests are of benefit for the codebase.

2022-03-31 08:12 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +    If no relationship can is determined between the symmetries then the
```suggestion
    If no relationship is determined between the symmetries then the
```

2022-03-31 08:22 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    if i + 1 == len(_groups):
I find this if/else clause a bit strange, can't we just do `if i + 1 != len(_groups):` and then do `assert not any(v == 2 for v in values)` as the only assert?

2022-03-31 08:50 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    if i + 1 == len(_groups):
Good idea, we don't need the `if else`.

2022-03-31 09:01 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    if i + 1 == len(_groups):
What I meant was for the assert to be within the if clause, that should make pytest happy, right?

2022-03-31 09:03 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    if i + 1 == len(_groups):
Ah okay! 👍

2022-03-31 09:10 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    if i + 1 == len(_groups):
`pytest` doesn't require anything to be asserted in a test, so the else *could* be left out entirely. But of course the solution you chose now is OK.

2022-03-31 10:07 UTC, hakonanes commented
I'm very happy with this PR, and I'll leave it up to @pc494 to review and merge when he finds the time.

2022-04-01 08:55 UTC, pc494 approved these changes
LGTM, merging

2022-04-01 08:55 UTC, merged