Add Symmetry plot method
pyxem/orix pull request #306
Opened 2022-03-22 13:04 UTC by harripj

#### Description of the change
As discussed in #303 and #171, it would be a good idea to add a `plot` method to `Symmetry` to display symmetry elements in the crystal reference frame under the stereographic projection.

Closes #171.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix.quaternion import symmetry
>>> symmetry.O.plot()
```
![image](https://user-images.githubusercontent.com/16853829/159481662-ac8ed7c2-b8ad-416d-8c25-c0f91f417375.png)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-03-25 09:42 UTC, hakonanes requested changes
Very helpful and nice visualization of symmetry operations! All requests and comments are related to documentation and tests.

Should add `plot` to the list of `Symmetry` methods below `from_generators` in the [reference](https://github.com/pyxem/orix/blob/master/doc/reference.rst#symmetry).

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +
Remove this blank line to maintain the style.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +
Remove this blank line to maintain the style.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +            The created figure, returned if `return_figure` is True.
I suggest to clarify that `return_figure` has to be passed as a keyword argument.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +            The created figure, returned if `return_figure` is True.
I suggest to clarify that `return_figure` has to be passed as a keyword argument.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +        if isinstance(orientation, str) and orientation.lower() == "default":
This will then be `if orientation is None:`

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +        if isinstance(orientation, str) and orientation.lower() == "default":
This will then be `if orientation is None:`

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +            raise TypeError("Orientation must be a Rotation instance or 'default'.")
Must be updated as well.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +            raise TypeError("Orientation must be a Rotation instance or 'default'.")
Must be updated as well.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +        figure = v_upper.scatter(
This is just an idea for the future, but it might be that we should support a boolean parameter to `Vector3d.scatter()` to set whether vectors on the other hemisphere (northern if `hemisphere="south` is passed and vice versa) should be projected up to the projection plane as well. We should then force the scatter points to be different.

2022-03-25 09:42 UTC, hakonanes commented on orix/quaternion/symmetry.py
> +        figure = v_upper.scatter(
This is just an idea for the future, but it might be that we should support a boolean parameter to `Vector3d.scatter()` to set whether vectors on the other hemisphere (northern if `hemisphere="south` is passed and vice versa) should be projected up to the projection plane as well. We should then force the scatter points to be different.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +from matplotlib.figure import Figure
`Figure` can be accessed from `matplotlib.pyplot.Figure`, so you can skip this import.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +from matplotlib.figure import Figure
`Figure` can be accessed from `matplotlib.pyplot.Figure`, so you can skip this import.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    num = 2 if symmetry.improper.any() else 1
We have `Symmetry.is_proper` for this check.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    num = 2 if symmetry.improper.any() else 1
We have `Symmetry.is_proper` for this check.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    assert np.allclose(c0.get_sizes(), 100)  # default value
Is this check necessary? What is tested here, that it is a circle? If it's not very important, I suggest to drop these checks.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +    assert np.allclose(c0.get_sizes(), 100)  # default value
Is this check necessary? What is tested here, that it is a circle? If it's not very important, I suggest to drop these checks.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +        # in my experience there are 26 points in circle marker path
Remove first person phrasing here, but leave the comment if these checks are kept. I've had to change many tests in orix and elsewhere with hardcoded numbers "deep" within Matplotlib that change between releases.

2022-03-25 09:42 UTC, hakonanes commented on orix/tests/quaternion/test_symmetry.py
> +        # in my experience there are 26 points in circle marker path
Remove first person phrasing here, but leave the comment if these checks are kept. I've had to change many tests in orix and elsewhere with hardcoded numbers "deep" within Matplotlib that change between releases.

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +            "metadata": {},
Add "nbsphinx": "hidden" to the metadata, so that this notice isn't shown when built on the Read the Docs web page (because there links actually work).

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +            "metadata": {},
Add "nbsphinx": "hidden" to the metadata, so that this notice isn't shown when built on the Read the Docs web page (because there links actually work).

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "import orix.plot.stereographic_plot\n",
The projection is registered with `from orix import plot`, I suggest to use this command instead since its simpler.

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "import orix.plot.stereographic_plot\n",
The projection is registered with `from orix import plot`, I suggest to use this command instead since its simpler.

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "Vectors located on the upper (`z > 0`) hemisphere are displayed as crosses (`+`), whereas vectors on the lower hemisphere are reprojected onto the upper hemisphere and shown as open
I suggest to link to for example http://xrayweb.chem.ou.edu/notes/symmetry.html#point to give the reader an opportunity to understand the visualizations. Either that, or we add some theory here ourselves. I think adding the link is OK for now.

2022-03-25 09:42 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "Vectors located on the upper (`z > 0`) hemisphere are displayed as crosses (`+`), whereas vectors on the lower hemisphere are reprojected onto the upper hemisphere and shown as open
I suggest to link to for example http://xrayweb.chem.ou.edu/notes/symmetry.html#point to give the reader an opportunity to understand the visualizations. Either that, or we add some theory here ourselves. I think adding the link is OK for now.

2022-03-25 09:44 UTC, hakonanes commented
Seems like GitHub has submitted all my comments twice. I suggest to leave the extra comments, in case both are deleted when one is deleted...

2022-03-25 09:53 UTC, harripj commented on orix/tests/quaternion/test_symmetry.py
> +    num = 2 if symmetry.improper.any() else 1
Thanks, didn't know this.

2022-03-25 10:28 UTC, harripj commented on orix/quaternion/symmetry.py
> +        figure = v_upper.scatter(
This seems like a good idea. We could move the code here to `Vector3d.scatter` and the keyword argument could be called something like `reproject_upper`. This would then simplify the method here too.

2022-03-25 13:52 UTC, harripj commented
Doc build error looks like it is part of jinja2 or nbconvert and is being experienced elsewhere recently: https://github.com/sphinx-doc/sphinx/issues/10289

2022-03-25 13:59 UTC, harripj commented
> Doc build error looks like it is part of jinja2 or nbconvert and is being experienced elsewhere recently: [sphinx-doc/sphinx#10289](https://github.com/sphinx-doc/sphinx/issues/10289)

Looks like a fairly minor fix. I suggest we wait until `nbconvert` pushes the patch which will hopefully sort everything from our side without change, An alternative is to pin `jinja2` to `3.0` in requirements, but it seems that like this will be cleared up pretty quickly.

2022-03-25 16:16 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "from orix.quaternion import symmetry\n",
All notebooks must use the "inline" backend, so add `%matplotlib inline` here (don't know how to set this in `doc/conf.py`, checked nbsphinx docs now).

2022-03-25 16:17 UTC, hakonanes commented
> I suggest we wait until `nbconvert` pushes the patch which will hopefully sort everything from our side without change

I agree. Checked the notebook locally, just had one important comment.

2022-03-25 16:30 UTC, hakonanes commented
After the notebook change, I have a final suggestion: could you update the locations of other relevant packages references in `conf.py`

from

```python
    "h5py": ("http://docs.h5py.org/en/stable/", None),
    "matplotlib": ("https://matplotlib.org", None),
    "numpy": ("https://docs.scipy.org/doc/numpy", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
```

to

```python
    "h5py": ("https://docs.h5py.org/en/stable", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
```

Sphinx tells us nicely that they have changed when running `make html`.

2022-03-25 18:18 UTC, harripj commented
> > Doc build error looks like it is part of jinja2 or nbconvert and is being experienced elsewhere recently: [sphinx-doc/sphinx#10289](https://github.com/sphinx-doc/sphinx/issues/10289)
> 
> Looks like a fairly minor fix. I suggest we wait until `nbconvert` pushes the patch which will hopefully sort everything from our side without change, An alternative is to pin `jinja2` to `3.0` in requirements, but it seems that like this will be cleared up pretty quickly.

NB this is the PR in question https://github.com/jupyter/nbconvert/pull/1737.

2022-03-28 13:49 UTC, harripj commented
> NB this is the PR in question https://github.com/jupyter/nbconvert/pull/1737.

This appears to have been fixed.

2022-03-29 07:36 UTC, hakonanes commented
This PR can now use reprojection functionality of vectors on the other hemisphere!

2022-03-29 14:50 UTC, hakonanes approved these changes
This is a very good way to visualize symmetry operations; I'm sure I'll use it many times!

I've suggested an insignificant change to the user guide notebook. Performing the change isn't required to merge, but I think it shows the user a slightly simpler way to reflect a vector about the projection plane.

2022-03-29 14:50 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
This can be done as suggested in https://github.com/pyxem/orix/pull/308#issuecomment-1081939951.

2022-03-29 14:53 UTC, harripj commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
```python
v_reproject = Vector3d(v.data)
v_reproject += -1
```

2022-03-29 14:55 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
Yes, that looks cleanest. And then negate only the Z coordinate!

2022-03-29 14:55 UTC, harripj commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
Doesn't work actually, the memory is shared.

2022-03-29 14:58 UTC, harripj commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
```python
v_reproject = Vector3d(v.data.copy())
v_reproject += -1
```
This is okay if that works for you?

2022-03-29 15:00 UTC, hakonanes commented on doc/point_groups.ipynb
> +                "    v_reproject = Vector3d(v.data * (1, 1, -1))\n",
Yes, but it's only the z coordinate that should be negated?

2022-03-29 15:07 UTC, pc494 approved these changes
This looks good, assuming the tests green light. I'll let @hakonanes merge.

2022-03-29 15:23 UTC, merged