Add `Vector3d.scatter()` reproject onto hemisphere functionality
pyxem/orix pull request #307
Opened 2022-03-27 21:48 UTC by harripj

#### Description of the change

As discussed with @hakonanes in https://github.com/pyxem/orix/pull/306#discussion_r835078799

> This is just an idea for the future, but it might be that we should support a boolean parameter to Vector3d.scatter() to set whether vectors on the other hemisphere (northern if hemisphere="south is passed and vice versa) should be projected up to the projection plane as well. We should then force the scatter points to be different.

We should include the option to reproject vectors onto the visible hemisphere, ie. if `Vector3d.scatter(hemisphere='upper')` is called then vectors projected onto the lower hemisphere are not shown. This PR adds the `reproject` argument to `Vector3d.scatter()` which reprojects vectors located on the hidden hemisphere to the visible hemisphere. The reprojected vectors are displayed with a `'+'` marker by default and can be set using the `reproject_marker` argument. If `hemisphere='both'`, `reproject=True` has no effect.

If approved the changes in this PR should be used to simplify #306.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from orix.quaternion import Orientation, symmetry
from orix.vector import Vector3d

o = symmetry.O * Orientation.random()
v = o * Vector3d.zvector()

v.scatter(hemisphere='upper', show_hemisphere_label=True)
```
<img width="402" alt="image" src="https://user-images.githubusercontent.com/16853829/160302053-601d73c1-2c04-436c-84bc-c16a94f38032.png">

```python
v.scatter(hemisphere='upper', reproject=True, show_hemisphere_label=True)
```
<img width="412" alt="image" src="https://user-images.githubusercontent.com/16853829/160302085-0623a319-5875-478f-bc2e-93c41277204e.png">

`reproject=True` has no effect if `hemisphere='both'`:
```python
v.scatter(hemisphere='both', reproject=True, show_hemisphere_label=True)
```
<img width="570" alt="image" src="https://user-images.githubusercontent.com/16853829/160302110-51620add-b85b-4d2f-a585-c1a51bc53d13.png">

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-03-28 07:58 UTC, hakonanes commented
Just ping me whenever this is ready for review.

2022-03-28 10:00 UTC, hakonanes requested changes
This is a very nice addition to the `scatter()` convenience plotting method! I've made some requests. I think a mention of this possibility in the stereographic projection user guide should be added. Perhaps it is most suitable to add it to the end of the "Upper and/or lower hemisphere" part ([here](https://orix.readthedocs.io/en/stable/stereographic_projection.html#Upper-and/or-lower-hemisphere))?

2022-03-28 11:12 UTC, harripj commented on orix/vector/vector3d.py
> +        v_lower = self[~upper_mask]
Thanks for this suggestion, this simplifies the code a lot!

2022-03-28 11:19 UTC, harripj commented on orix/vector/vector3d.py
> +                reproject_kwargs = {**kwargs, **dict(marker=reproject_marker)}
Good idea! I think we should remove the arg `reproject_marker` entirely in this case and have everything defined by `reproject_scatter_kwargs`.

2022-03-28 17:21 UTC, hakonanes commented on orix/vector/vector3d.py
> +        reproject_marker : str, optional
No problem!

2022-03-28 17:32 UTC, harripj commented on orix/vector/vector3d.py
> +            func:`~orix.plot.StereographicPlot.scatter`, which passes
https://github.com/pyxem/orix/blob/a9bba5696873385275dc41ecfcc5ac052a3ac213/orix/vector/vector3d.py#L642-L645

I copied this from below, although admittedly forgot the colon (whoops). It looks like we should be using `meth` rather than `func` here too?

2022-03-28 17:39 UTC, hakonanes commented on orix/vector/vector3d.py
> +            func:`~orix.plot.StereographicPlot.scatter`, which passes
Hah, yes, good that you copied it so we spotted this "error"! It seems like Sphinx [links correctly](https://orix.readthedocs.io/en/stable/reference.html#orix.vector.Vector3d.scatter) with either "func" or "meth". But "meth" is most correct here, so best to update the docstrings.

2022-03-29 07:35 UTC, hakonanes approved these changes

2022-03-29 07:35 UTC, merged