Add misorientation clustering notebook, update changelog
pyxem/orix pull request #314
Opened 2022-04-04 14:15 UTC by hakonanes

Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

#### Description of the change
Add the misorientation clustering notebook from the [orix-demos](https://github.com/pyxem/orix-demos/blob/master/03%20-%20Clustering%20Misorientations.ipynb). This is the final notebook in the demos that aren't in the user guide, and we can hence archive (and eventually delete) the orix-demos repository after this PR is merged.

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [n/a] Unit tests with pytest for all lines
- [n/a] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-04-04 15:05 UTC, harripj requested changes
Very nice notebook, a few suggestions below. One more suggestion, once the data is loaded I think it would be nice to show an IPF map of the region, that way the user can compare to the final grain boundary map. What do you think?

2022-04-04 15:18 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
Yes something like this. I'm not suggesting to change the code, just curious!

2022-04-04 15:19 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
Good suggestion, it reduces the number of computations, which is always good! Will do the change.

2022-04-04 15:30 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
For example, for the main misorientation distance calculation, the following produces the same output as calculated (code taken from the notebook):
```python
>>> mismisori = (~mori).outer(mori)

>>> # NB the 2 lines below are the memory intense operation, so left commented out
>>> # mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)
>>> # D = mismisori_equiv.angle.data.min(axis=(0, 2, 3, 5))

>>> # load the precomputed file instead
>>> D = np.load("misori-distance((100, 200)).npy")

>>> # alternative with 2 less dot products
>>> mismisori_equiv1 = D6.outer(~mori).outer(D6.outer(mori))
>>> D1 = mismisori_equiv1.angle.min(axis=(0, 2))

>>> np.allclose(D, D1)
True
```

It strikes me that this is possible because in the 4 dot product equation the preceding and succeeding symmetries for each misorientation are the same in this case, ie. `D6`.

2022-04-04 15:36 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
Yes, and I think the authors (@pc494) wanted to show the general approach and not assume identical symmetry. Although fewer dot products are computed, this almost fills my 16 GB RAM, so we can't ask Read the Docs server to do it. But we could add it in the commented out section.

2022-04-04 15:43 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
Thanks for clarifying! I don't think the notebook needs changing, just curious.

2022-04-04 16:05 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "from orix.quaternion import Orientation, OrientationRegion, Misorientation, Rotation\n",
Thanks, removed the two first, since `Vector3d` is now used to specify sample directions when colouring orientations.

2022-04-04 16:06 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "filepath = \"/home/hakon/kode/orix_test/Ti_orientations.ctf\"\n",
Right, these are now shortened to just the file names. I intended to leave them in because it will be simpler for me to run them in the future to check functionality.

2022-04-04 16:07 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "Keep only misorientations assumed to be on boundaries, i.e. with a\n",
Good point, have rephrased slightly to make this clear.

2022-04-04 16:07 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "Select a subset of the orientations to a suitable size for this demonstration"
I agree.

2022-04-04 16:10 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#D = np.empty((misori.size, misori.size))\n",
Thanks, this should be correct now.

2022-04-04 16:10 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#    d = mismisori.angle.data.min(axis=(0, 2, 3, 5))\n",
Thanks, this should be correct now.

2022-04-04 16:10 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "filepath_2 = \"/home/hakon/kode/orix_test/misori-distance((100, 200)).npy\"\n",
Done.

2022-04-04 16:11 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
I added this approach as a second option, specifying that this only works when the misorientation symmetries are the same.

2022-04-04 16:36 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "mori_all = Misorientation(~ori[:, :-1] * ori[:, 1:])"
> Tools like finding indices of nearest neighbours in a 2D map would be useful here. I've been thinking to add such a function(s), to be used for KAM calculations etc., but never found the time for it.

I had a go at something like this before, it may be useful to you:
```python
from orix.quaternion import Orientation
import numpy as np
order = 1
o = Orientation.random((200, 100))
from skimage.morphology import disk
slices = tuple(slice(order, s-order) for s in o.shape)
indices = np.stack(np.mgrid[slices], axis=-1)

footprint = disk(order)
footprint_indices = np.column_stack(np.nonzero(footprint)) - np.array(footprint.shape) // 2

indices_all = indices[..., np.newaxis, :] + footprint_indices
m = o[tuple(indices_all.T)].transpose(2, 1, 0) - Orientation(o[slices].data[..., np.newaxis, :])
```
I didn't finish it off as it requires the mean to be taken along a certain axis (which is currently not implemented). But it's a start if you're looking to do something similar.

2022-04-04 16:45 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "#    d = mismisori.angle.data.min(axis=(0, 2, 3, 5))\n",
I think there is still a reference to `mori2` in the loop in the latest build :).

2022-04-04 16:49 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "#    d = mismisori.angle.data.min(axis=(0, 2, 3, 5))\n",
Ah, sorry. Thank you for looking closely!

2022-04-04 18:05 UTC, hakonanes commented on doc/clustering_misorientations.ipynb
> +    "mori_all = Misorientation(~ori[:, :-1] * ori[:, 1:])"
Thanks, I'll keep this comment in mind if I find the time!

Adding an `axis` argument to various methods, like `mean`, `unique` etc., will be very powerful. Something for the future...

2022-04-04 19:51 UTC, harripj approved these changes

2022-04-04 19:52 UTC, harripj commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
I will leave this open if @pc494 would like to add any comments!

2022-04-05 16:18 UTC, pc494 commented on doc/clustering_misorientations.ipynb
> +    "#mismisori_equiv = D6.outer(~mori2).outer(D6).outer(D6).outer(mori2).outer(D6)\n",
Happy with this.

2022-04-05 16:19 UTC, pc494 approved these changes
This is a really nice tidy up, merging

2022-04-05 16:19 UTC, merged