Add `lazy` parameter to `Quaternion` and `Rotation` `.outer()` for easy `Dask` computation
pyxem/orix pull request #325
Opened 2022-04-27 15:22 UTC by harripj

#### Description of the change
Now that `Vector3d` outer products can be computed in `Quaternion._outer_dask()`, and as previously discussed, this PR allows this functionality to be accessed using the public API through `.outer()`. In line with `._outer_dask()` 2 keyword arguments `lazy` and `chunksize` are added, and `lazy` defaults to `False` to conserve the current behaviour.

`Rotation._outer_dask()` has also been removed as it can be called though the inherited `Quaternion._outer_dask()` method.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix.quaternion import Rotation
>>> import numpy as np
>>> r1 = Rotation.random((5, 3))
>>> r2 = Rotation.random((11, 4))
>>> r12 = r1.outer(r2)
>>> r12_lazy = r1.outer(r2, lazy=True, chunk_size=20)
>>> np.allclose(r12.data, r12_lazy.data)
True

>>> r = Rotation.random((5, 3))
>>> v = Vector3d(np.random.rand(6, 4, 3)).unit
>>> v2 = r.outer(v)
>>> v2_lazy = r.outer(v, lazy=True, chunk_size=20)
>>> np.allclose(v2.data, v2_lazy.data)
True
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.

2022-04-27 15:29 UTC, hakonanes commented
Fantastic! I've got time to review from tomorrow. Just ping me.

2022-04-29 09:16 UTC, hakonanes requested changes
Very nice enhancement and clean-up!

I've suggested that we support the `progressbar` parameter in the methods newly supporting lazy computation, to maintain a consistent lazy API. Wherever `lazy` is supported, some control over chunk size via `chunksize` and whether to show the progressbar via `progressbar` is a sufficient lazy API at the moment, I think.

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    def outer(self, other, lazy=False, chunk_size=20):
`get_distance_matrix()` supports controlling whether a progressbar is shown during computation, this should be added here to maintain a consistent lazy API.

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        lazy : bool
```suggestion
        lazy : bool, optional
```

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    def outer(self, other, lazy=False, chunk_size=20):
The calls to the initialization methods are those that should then be inside a `with ProgressBar():` context if `progressbar` is `True`, because that's when the Dask arrays are converted to NumPy arrays.

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/rotation.py
> +    def outer(self, other, lazy=False, chunk_size=20):
The `progressbar` parameter should be supported here as well.

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        lazy : bool
Likewise below.

2022-04-29 09:16 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    def outer(self, other, lazy=False, chunk_size=20):
A couple extra lines to the tests catching the cases when `progressbar=True` must of course be added. I think it's unnecessary to actually check that the progressbar is shown.

2022-04-29 13:10 UTC, harripj commented on orix/quaternion/quaternion.py
> +    def outer(self, other, lazy=False, chunk_size=20):
Very good point. I think this makes the API simple and consistent.

2022-05-02 18:16 UTC, hakonanes approved these changes
Great, thanks for adding the `progressbar` parameter. I'll merge tomorrow if you don't say otherwise, or you can merge yourself :)

2022-05-03 06:58 UTC, merged