Migrate S2 samplings from diffsims, add hexagonal sampling
pyxem/orix pull request #334
Opened 2022-05-10 19:20 UTC by din14970

#### Description of the change
This is a first in some PRs I still hope to make in order to clean up and enhance `diffsims` a bit by taking out functionality which I believe should reside in `orix`. May take me quite a long time to do so but we'll see how far we get. It seems not all S2 samplings from `diffsims` were copied to orix. This PR moves all of them and gives them names consistent with the other functions. In addition, I've implemented a new "hexagonal" sampling:

```python
>>> from orix.sampling import S2_sampling
>>> points = S2_sampling.sample_S2_hexagonal_mesh(5)
>>> points.scatter(s=2)
```

![image](https://user-images.githubusercontent.com/25320842/167699408-23d8a93d-43c8-400e-9dd3-080da07b063e.png)

My reasoning for this is that for a "beam direction grid" sampling you usually want the edges of the fundamental zone to be sampled. For the existing grids, the sampled fundamental zones for trigonal and hexagonal crystals will have a "rough" edge. This mesh solves that.

In addition, I've refactored the cube mesh sampling a bit to make it more readable and hopefully maintainable.

What is not included in this PR:
* in diffsims, these meshes are [filtered by crystal system](https://github.com/pyxem/diffsims/blob/2b7532946092fe4a8b133f8b2f7ad638fe277cf8/diffsims/generators/rotation_list_generators.py#L173) and converted to orientations and Euler angles, using the [beam directions grid to euler fuction](https://github.com/pyxem/diffsims/blob/2b7532946092fe4a8b133f8b2f7ad638fe277cf8/diffsims/generators/sphere_mesh_generators.py#L479). I'm wondering how this can be streamlined. In my vision, everything related to orientations and vectors is moved to orix. That means:
  * the "filtering" of orientations should ideally use orix' symmetry functionality based on the (diffpy) crystal structure provided. now a user has to specify crystal symmetry with a string.
  * the conversion of a beam direction to an orientation should follow the very specific constraint that phi_1 = 0. The question is where such a function can fit best into orix.

#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
see above

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-05-11 09:19 UTC, hakonanes commented
Great that you're taking the time to add this functionality to orix!

> the "filtering" of orientations should ideally use orix' symmetry functionality based on the (diffpy) crystal structure provided. now a user has to specify crystal symmetry with a string.

This is straight forward using the `FundamentalSector` (derived from MTEX using orix' `OrientationRegion`) which defines a region on *S2*. It has implemented `__eq__`, which checks whether a vector is inside the region, allowing simple slicing. I've added a Gist showing this [here](https://gist.github.com/hakonanes/72d03a886a8d06aa06a64b382637aa92).

Note the different crystal axes alignment in orix compared to diffpy.structure's default, described [here](https://orix.readthedocs.io/en/latest/crystal_reference_frame.html). This might be the main reason for the differences between the monoclinic, orthorhombic, trigonal and hexagonal grids in `diffsims` and `orix`.

I'll review this today or tomorrow. We should follow this PR up with a "Vectors/Sampling" user guide notebook!

2022-05-12 16:03 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    corners: numpy.ndarray (N, 3)
Space around colon here.

2022-05-12 16:04 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    corners: numpy.ndarray (N, 3)
This docstring could need some capitalization and periods.

2022-05-12 16:04 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    # create edges
I suggest to add some blank lines to separate sections.

2022-05-12 16:10 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +def _compose_from_faces(corners, faces, n):
I'm not able to follow the code in this function. Has it been much used in diffsims? If not, do you think it will be more used if in orix? I'm asking because I'm not sure if I'm able to maintain the function. Of course we can leave it in if you're willing to maintain it.

2022-05-14 07:55 UTC, harripj commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
I was thinking at some point that adding type hints would be a good addition to orix.

I also think that this doesn't need to be done all in one go but can be done gradually, and maybe completed before 1.0? Happy to include them starting from here! In that case I would prefer if all functions in this PR used typehints.

On a separate note, I could not find how best to include type hints in the [numpydoc format](https://numpydoc.readthedocs.io/en/latest/format.html) but currently it means possibly duplicating the parameter types as both type hints and in the docstring, which I think is redundant. If we can get it to work with Sphinx then I would prefer to have type hints and remove type parameters in the docstrings. What do you think?

2022-05-14 08:00 UTC, harripj commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
Looks like [this comment](https://stackoverflow.com/a/66295922) could be a solution.

2022-05-14 12:52 UTC, din14970 commented on orix/sampling/S2_sampling.py
> +        length=1.0,
No, but I like to write this explicitly to indicate it is a float

2022-05-14 12:54 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +    :func:`get_icosahedral_mesh_vertices`
it was the name of the function that calls `_compose_from_faces` in diffsims, but I don't think this is necessary here, especially since I've moved it to a different module. So now I've removed it

2022-05-14 15:05 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +    total_angle = np.arctan(length)
Length is actually a unit of distance. The sphere used to generate the mesh has radius 1, so this "length" is actually the distance on the cube around the sphere.

2022-05-14 15:11 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +def _compose_from_faces(corners, faces, n):
To be honest, I'm not able to follow the code either, it came more or less directly from meshzoo. The problem with using meshzoo directly was that the functions not only generated points, but also the triangles connecting them. Plus, adding meshzoo as dependency to diffsims seemed a bit overkill for a pretty small feature -- hence a copy of only the relevant bits of code. This specific function is necessary for the icosahedral sampling which I think might be a nice feature to have. The function has no complex operations or dependencies which would have a high chance of getting depricated in future versions of numpy or python, so I'm pretty sure it can be left as-is. If it ever turns out to be unmaintainable, both icosahedral sampling and this function could be removed.

2022-05-14 15:13 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
In my current job we use type annotations for everything mainly to be able to use [mypy](http://mypy-lang.org/). Has quite a lot of advantages as you can catch dumb issues early during development using a linter (I'm using python language server with a mypy plugin) instead of at runtime. For me this is the main selling point over just annotating them in the documentation. A downside of type annotiations as they currently exist is that you can't specify more details about the types, like shapes of numpy arrays. This IS often done in documentation, since return type or parameter type `np.ndarray` is usually not very informative. There is now `numpy.typing` <https://numpy.org/devdocs/reference/typing.html> with which dtypes of arrays can be specified. It seems shapes for type annotations are still on the roadmap https://numpy.org/neps/roadmap.html.

2022-05-14 19:22 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +def _compose_from_faces(corners, faces, n):
I have had another look at this function and it seems a large part of it was only necessary for generating edges/faces. I've now stripped down the function to the bare essentials for only generating the vertices. I've also improved the icosahedral sampling by now using basic geometry to calculate how large `n` should be, instead of finding `n` through a trial and error loop. This means that the `_compose_from_faces` function only needs to be called once.

2022-05-14 19:53 UTC, din14970 commented
@hakonanes I could work out a short notebook but I might copy paste some stuff from the gist you shared if that's OK with you. Will also probably take some time still.

> This might be the main reason for the differences between the monoclinic, orthorhombic, trigonal and hexagonal grids in diffsims and orix.

For diffsims to continue to work properly for the template matching in pyxem, I'm wondering whether it is important which fundamental zone is sampled. I guess we'll find out when I get to it.

@harripj docs don't seem to have an issue with the type hints AFAICT

2022-05-15 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +        passed to np.random.default_rng(), defaults to None which
We have to spell out "numpy" for intersphinx to catch the reference (see [here](https://orix--334.org.readthedocs.build/en/334/reference.html#orix.sampling.sample_S2_random_mesh)).

2022-05-15 11:05 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
We use type hints in kikuchipy without duplication in the docstring, see e.g. [doc](https://kikuchipy.org/en/stable/reference.html#kikuchipy.signals.EBSD.dictionary_indexing) and [code](https://github.com/pyxem/kikuchipy/blob/2b6feb33a8852b89cbd089721fecc99c4890a6c5/kikuchipy/signals/ebsd.py#L952). We use the [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints) to help Sphinx with the type hints. But, based on [the docs](https://orix--334.org.readthedocs.build/en/334/reference.html#orix.sampling.sample_S2_random_mesh) from one of the functions in this PR, it seems we don't need that? Would be good to check the same function without duplication in the docstring.

2022-05-15 11:06 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    total_angle = np.arctan(length)
Thanks for clarifying!

2022-05-15 11:19 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    k = corners.shape[0]
Seems to me like `k` can be removed?

2022-05-15 11:24 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +import numpy as np
Final comments on code style not picked up by `black`:
1. Add a blank line between imports of standard libraries and third party libraries
2. Start docstring top description on line with """, to be in line with (all?) other docstrings in orix
3. One space missing around colon in docstring parameter on line 132

2022-05-15 11:24 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +def _compose_from_faces(corners, faces, n):
Thank you for making the effort, it is much easier to follow now!

2022-05-15 11:31 UTC, hakonanes commented
> I would suggest we push this to post 0.9.0 as it might well need a couple of weeks. That way we can have a "stable" trio of 0.14 (pyxem) 0.9.0 (orix) and 0.5.0 (diffsims) to expand on.

Sounds good to me, since making a nice vector sampling user guide isn't done by tomorrow when we plan to release orix 0.9. If it turns out some downstream package needs this functionality to build upon, I'm OK with releasing a 0.10 with this in soon if necessary.

> I might copy paste some stuff from the gist you shared if that's OK with you.

Sure, go ahead! I was thinking that as a temporary solution in diffsims, we can hard-code the fundamental sectors with the existing corners in diffsims to reduce the vectors. This should produce the exact list of current vectors in diffsims.

> Will also probably take some time still. Otherwise, I would say this PR should be in decent shape.

That's OK, of course. Since we don't have any better way to cut a release in orix than from `master`, I suggest to merge this PR *after* 0.9 is released.

2022-05-15 11:34 UTC, hakonanes requested changes
As you say, this PR is in decent shape!

I've got four outstanding review comments, and also the two points in https://github.com/pyxem/orix/pull/334#pullrequestreview-971070726.

2022-05-15 12:01 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +    k = corners.shape[0]
good catch

2022-05-15 12:03 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
> Would be good to check the same function without duplication in the docstring.

I checked. From this PR with docstring duplication:

![bilde](https://user-images.githubusercontent.com/12139781/168471529-f62c5f92-1962-4687-a568-a65b9682c66f.png)

Without docstring duplication and without `sphinx-autodoc-typehints` (built locally):

![bilde](https://user-images.githubusercontent.com/12139781/168471550-74e6cdfe-5cf2-45fd-83f1-a89822c4c89a.png)

Without docstring ducplication and with `sphinx-autodoc-typehints` (built locally):

![bilde](https://user-images.githubusercontent.com/12139781/168471716-d2267055-3c43-4632-bf1c-5806c0f4b75b.png)

My preference is for without docstring duplication and without `sphinx-autodoc-typehints`.

Another question is if the docs can be built nicely with the minimal version of Python orix supports, 3.6.

2022-05-15 12:17 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +import numpy as np
> Add a blank line between imports of standard libraries and third party libraries

Have you ever looked into [`isort`](https://pycqa.github.io/isort/)? I can never remember the rules on imports so I just use that. But it seems when I ran it on the orix codebase tests stopped working, so it must be that in some files there is a very deliberate order for imports.

2022-05-15 12:20 UTC, din14970 commented on orix/sampling/_polyhedral_sampling.py
> +    number_of_steps: float,
Ok, so I will remove the duplicated type hints in the documentation then

2022-05-15 20:43 UTC, hakonanes commented on orix/sampling/_polyhedral_sampling.py
> +import numpy as np
Thank you for making the changes.

I haven't used it. I always group imports into three groups of std lib, 3rd party and internal, and list these alphabetically, unless another order is recquired. By the way, this is stated in the [contributing guide](https://orix.readthedocs.io/en/stable/contributing.html#code-style). If using isort hadn't caused any issues as you say, I'd be happy for use to start using it. I run black via pre-commit, and it seems like isort integrates well with those two.

2022-05-16 10:30 UTC, harripj requested changes
A very nice addition to orix which greatly improves the sampling capabilities. I just few a few small comments below.

2022-05-16 10:30 UTC, harripj commented on orix/sampling/S2_sampling.py
> +    angle = np.radians(60)
As @hakonanes mentioned could this be made `deg2rad` too?

2022-05-16 10:30 UTC, harripj commented on orix/sampling/_polyhedral_sampling.py
> +    maximum_grid_spacing = np.tan(np.radians(resolution))
`deg2rad` here too.

2022-05-16 10:30 UTC, harripj commented on orix/sampling/_polyhedral_sampling.py
> +    return int(np.ceil(total_angle / np.radians(resolution)))
`deg2rad` here too.

2022-05-16 20:00 UTC, din14970 commented
I've added a very basic notebook under `vectors`, would be happy to get some feedback (or direct modifications) on this

2022-05-17 13:43 UTC, harripj requested changes
I really like the notebook- a great addition to the docs, thanks @din14970! I have just a few comments below.

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "%matplotlib inline"
This cell could be combined with the one below.

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "from orix.vector import Vector3d"
From my testing `Phase`, `Orientation`, and `Vector3d` are not needed to run this notebook, so I suggest to remove them.

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "The fundamental zone of a point group represents the smallest region of directions unique by symmetry.\n",
Could I suggest rewriting this as: "the smallest region of symmetrically unique directions."? At least for myself this is more clear!

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "The symmetry operations are independent of the S2 sampling methods, so any set of vectors can be limited to the fundamental zone.\n",
Could you use LaTeX formatting on $S_2$ (as done in the top of the notebook).

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "    vectors = sampling_method(resolution = 5)\n",
Could you remove the spaces around `=`?

2022-05-17 13:43 UTC, harripj commented on doc/s2_sampling.ipynb
> +  },
It would also be nice to fill in the final plot. I have created an equal area sampling implementation on S2 in #340 which I think would fit nicely here, if that would be okay with you once that PR is accepted. What do you think?

2022-05-18 09:50 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "The symmetry operations are independent of the S2 sampling methods, so any set of vectors can be limited to the fundamental zone.\n",
I suggest to just write "S2" in the title, because the title is used in the sidebar and it takes bit of time for "\(S_2\)" to be rendered in LaTeX, and the browser tab title does not support LaTeX so it will always read "\(S_2\)".

2022-05-18 10:29 UTC, hakonanes requested changes
Very nice and pedagogical user guide notebook. I've made some new comments and also added to Paddy's comments. The comment on the `orix.sampling` module import structure is the most important one.

I don't think this PR should include more functionality, so after the current review comments are sorted, I suggest to merge.

2022-05-18 10:29 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +SAMPLING_METHODS: Mapping[str, Callable] = {
This dictionary prompts me to review the import structure of the `orix.sampling` module, which I've never really liked. Do you have a suggestion for how this could be simpler, @din14970?

Since this dictionary is used in the user guide, people will use it as well. I'm not sure I understand the benefit of the dictionary other than it is convenient to use in the user guide, was this your motivation?
 
I find it confusing that using for example `orix.sampling.S2_sampling.SAMPLING_METHODS["normalized_cube"]` and `orix.sampling.S2_sampling.sample_S2_cube_mesh()` have different defaults for grid type, is there a reason for this?

2022-05-18 10:29 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +SAMPLING_METHODS: Mapping[str, Callable] = {
This dictionary prompts me to review the import structure of the `orix.sampling` module, which I've never really liked. Do you have a suggestion for how this could be simpler, @din14970?

Since this dictionary is used in the user guide, people will use it as well. I'm not sure I understand the benefit of the dictionary other than it is convenient to use in the user guide, was this your motivation?
 
I find it confusing that using for example `orix.sampling.S2_sampling.SAMPLING_METHODS["normalized_cube"]` and `orix.sampling.S2_sampling.sample_S2_cube_mesh()` have different defaults for grid type, is there a reason for this?

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "resolution = 5\n",
This variable is unused as far as I can tell.

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "    axes[i].scatter(vectors, s=2);"
I suggest to add the axes labels X, Y to the plots via `...scatter(vectors, s=2, axes_labels=["X", "Y"])`

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +  },
An alternative is to hide it with `axes[-1].set_visible(False)`.

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "Usually one only wants to sample the fundamental zone, not the entire sphere, as in the context of a crystal, many vectors are symmetrically equivalent.\n",
I suggest to replace "vectors" with "directions" in "... many vectors are symmetrically equivalent".

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "In general, to sample vectors for crystals with $\\alpha=\\beta=\\gamma=90^\\circ$, one of the `cube` meshes is recommended.\n",
A link to the "cube" mesh function(s) in the API reference would be good here as well.

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "In general, to sample vectors for crystals with $\\alpha=\\beta=\\gamma=90^\\circ$, one of the `cube` meshes is recommended.\n",
Also the case for the hexagonal mesh function(s) and icosahedral mesh function.

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "fig, axes = plt.subplots(len(point_groups), 2, subplot_kw=dict(projection=\"stereographic\"), figsize=(10, 5 * len(point_groups)), facecolor=\"white\")\n",
Breaking this line up ensures we don't have to scroll horizontally in the user guide cell.

2022-05-18 10:29 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "    axes[i].scatter(vectors, s=2);"
Also, setting the Matplotlib preferences in the top cell makes reading the plotting commands simpler:

```python
plt.rcParams.update({"font.size": 20, "lines.markersize": 2})
```

2022-05-18 13:12 UTC, din14970 commented on doc/s2_sampling.ipynb
> +    "The symmetry operations are independent of the S2 sampling methods, so any set of vectors can be limited to the fundamental zone.\n",
I will make it S2 in the title and $S_2$ elsewhere then?

2022-05-18 13:14 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "The symmetry operations are independent of the S2 sampling methods, so any set of vectors can be limited to the fundamental zone.\n",
Perfect!

2022-05-18 13:14 UTC, din14970 commented on doc/s2_sampling.ipynb
> +    "The symmetry operations are independent of the S2 sampling methods, so any set of vectors can be limited to the fundamental zone.\n",
Actually might drop S2 and just write sampling unit vectors, S2 is redundant

2022-05-18 13:22 UTC, din14970 commented on doc/s2_sampling.ipynb
> +  },
@harripj is the "random" meshing not equivalent to this? https://mathworld.wolfram.com/SpherePointPicking.html?

I will for now go with hiding the axes, thanks @hakonanes

2022-05-18 13:23 UTC, din14970 commented on doc/s2_sampling.ipynb
> +    "fig, axes = plt.subplots(len(point_groups), 2, subplot_kw=dict(projection=\"stereographic\"), figsize=(10, 5 * len(point_groups)), facecolor=\"white\")\n",
yes I did it in the cell above but forgot in this one, thanks for the catch

2022-05-18 14:30 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "    axes[i].scatter(vectors, s=2);"
Sorry, this is no surprise, since `axes_labels` is only a parameter of `Vector3d.scatter()` and not `StereographicPlot.scatter()`. See https://github.com/pyxem/orix/blob/14639a15a4c66c87891debb8656ef187c3b6e9ea/orix/vector/vector3d.py#L722.

`axes[i].set_labels("X", "Y")` should work.

2022-05-18 19:30 UTC, din14970 commented on orix/sampling/S2_sampling.py
> +SAMPLING_METHODS: Mapping[str, Callable] = {
When making the notebook I realized that from a user perspective it doesn't make much sense to access each sampling method from different functions with different arguments. It makes a lot more sense to have a function like `sample_s2` where a string argument specifies which type of gridding should be used. The `cube` sampling can then also be "unraveled" using `partial` to map each type of cube sampling to a string, so that each type of sampling has the same interface - just provide a resolution value. One could just define a mapping in a function and then use that instead, the advantage of a mapping is that you can also query the available keys (this would be hidden or only accessible from documentation in the case of a function). The downside is that mappings which return a callable are a kind of weird construct, and directly "calling" something that is returned from a dictionary looks weird. I have to have a think on something that makes more sense, but in my view a simple interface is having a single function to have access to all kinds of mappings.

2022-05-19 08:41 UTC, harripj commented on doc/s2_sampling.ipynb
> +  },
Yes the parameterisation looks similar. The function `sample_S2_random_mesh()` produces random vectors on S2, but the function `sample_S2_equal_area_mesh()` in #340 produces a grid of cells with equal area on S2. This was necessary in that PR as to produce the pole density distribution we need the chance a given vector intercepts each cell to be the same.

Here is a comparison with the UV mesh:
```python
from orix.sampling.S2_sampling import sample_S2_equal_area_mesh, sample_S2_uv_mesh
from orix import plot
from matplotlib import pyplot as plt

fig, ax = plt.subplots(ncols=2, figsize=(8, 4), subplot_kw=dict(projection='stereographic'))

uv = sample_S2_uv_mesh(10, hemisphere='upper')
ea = sample_S2_equal_area_mesh(10, hemisphere='upper')

ax[0].scatter(uv)
ax[1].scatter(ea)

ax[0].set_title('UV mesh')
ax[1].set_title('Equal area mesh')
```
<img width="461" alt="dc7eb148-d9e5-4ed4-bc28-b9bba0538b4b" src="https://user-images.githubusercontent.com/16853829/169251378-e44b3e52-529f-4ad0-8cc8-1fecfeeb3a6d.png">

2022-05-19 08:53 UTC, harripj requested changes

2022-05-19 08:53 UTC, harripj commented on doc/s2_sampling.ipynb
> +   "metadata": {},
I noticed in the built docs that currently there is no thumbnail set for this notebook. Could you set this figure as the thumbnail? (I think the final figure may be a bit too large!)

If you can add something like the following to the `metadata` tag:
```
"metadata" : {
    "nbsphinx-thumbnail": {
         "tooltip": "Sampling directions on orientation space S2"
    },
    "tags": [
     "nbsphinx-thumbnail"
    ]
}
```

2022-05-19 12:08 UTC, din14970 commented on doc/s2_sampling.ipynb
> +    "In general, to sample vectors for crystals with $\\alpha=\\beta=\\gamma=90^\\circ$, one of the `cube` meshes is recommended.\n",
I've now made all the different individual mesh functions private and centralized them into one function.

2022-05-19 12:45 UTC, hakonanes commented
[This documentation](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) might be useful with regards to changing branch names.

2022-05-19 15:48 UTC, hakonanes commented
> Heads up, I've add to change the pre-commit config due to a black dependency issue see https://github.com/OCA/oca-addons-repo-template/issues/133

I think this is unnecessary with black v22.3, which is the current version in `develop`? Anway, going over this PR again now.

2022-05-19 15:49 UTC, hakonanes commented on doc/reference.rst
> -    :undoc-members:
Could you revert these changes?

2022-05-19 15:51 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "Usually one only wants to sample the fundamental zone, not the entire sphere, as in the context of a crystal, many vectors are symmetrically equivalent.\n",
Hehe, I meant rephrasing the marked line "... many VECTORS are symmetrically equivalent" to "... many DIRECTIONS are symmetrically equivalent", while the line "Sampling of VECTORS is most relevant..." was fine.

2022-05-19 15:56 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +_s2_sampling_docstring = (
Why not add this directly to `sample_S2()`?

2022-05-19 15:57 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +_s2_sampling_docstring = (
Nevermind, didn't see the use of `format()`.

2022-05-19 15:57 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    """Generate unit vectors that sample S2 with a specific angular resolution
```suggestion
    """Generate unit vectors that sample S2 with a specific angular resolution.
```

2022-05-19 16:00 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +
```suggestion
    kwargs
        Keyword arguments passed to the sampling function.
```

2022-05-19 16:04 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +        grid_type="normalized",
This is also the case for all function signatures above.

2022-05-19 16:08 UTC, hakonanes commented on orix/sampling/__init__.py
> +    sampling_methods as sampling_methods_S2,
How about `sample_s2_methods`, so we have "sample_S2" for both?

2022-05-19 16:13 UTC, hakonanes commented on doc/s2_sampling.ipynb
> +    "In general, to sample vectors for crystals with $\\alpha=\\beta=\\gamma=90^\\circ$, one of the `cube` meshes is recommended.\n",
I think this is a good idea.

2022-05-19 16:16 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +SAMPLING_METHODS: Mapping[str, Callable] = {
I agree with you and I think you have found a very clean and neat solution. Linking to the docstrings of the individual sampling functions could be good for the interested user to know more.

2022-05-19 16:21 UTC, hakonanes commented
> Basically I've made all the individual sampling methods private

This makes the individual docstrings unreachable, and I think they should be part of the public API since they explain the sampling functions. What do you think about making them public, but basically only using `sample_S2` in the user guide, and also stating that this is the function meant to be used in the individual docstrings?

2022-05-19 16:51 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +).format(sampling_methods)
I suggest to make the private functions public and link to them in `sample_S2` like so:

```python
_sampling_method_names = []
for method in list(_sampling_method_registry.values()):
    if isinstance(method, partial):
        method = method.func
    name = method.__name__
    if name not in _sampling_method_names:
        _sampling_method_names.append(name)

_s2_sampling_docstring = (
    """
Generate unit vectors that sample S2 with a specific angular
resolution.

Parameters
----------
resolution
    Maximum angle between nearest neighbour grid points, in degrees.
method
    Sphere meshing method. Options are: {}.

Returns
-------
vectors
    Vectors that sample the unit sphere.

See Also
--------
{}
"""
).format(sampling_methods, "\n".join(_sampling_method_names))
```

2022-05-19 16:52 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +
Also, the default method must be mentioned in the `method` parameter explanation.

2022-05-22 15:47 UTC, din14970 commented on doc/reference.rst
> -    :undoc-members:
don't know what happened here, very strange.

2022-05-22 15:54 UTC, din14970 commented on orix/sampling/S2_sampling.py
> +
> This will only be relevant for the random seed, as far as I can see from the individual docstrings.

Currently yes, but it might be that there are sampling methods that would require more fine-grained control or additional parameters passed to it, which is why I allow the option. I'll mention that currently this is only relevant for the `seed`.

> Also, the default method must be mentioned in the method parameter explanation.

What is your reasoning for this? Personally I disagree since the default defined in the function definition automatically shows up in the docs; otherwise it is repeated in two places. I would agree if the default is something like `None` which then gets interpreted to something else inside the function.

2022-05-23 08:59 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +
One use for repeating the default in the parameter explanation is that when you have a long docstring with many parameters and read the description of one of them, you don't have to scroll to the function signature at the top to learn what the default is. Also, I think most users expect it from using other Python packages, see e.g. the `mode` parameter in [numpy.choose()](https://numpy.org/doc/stable/reference/generated/numpy.choose.html), the `histtype` parameter in [matplotlib.pyplot.hist()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html#matplotlib.pyplot.hist), or the `mode` parameter in [skimage.filters.difference_of_gaussians()](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.difference_of_gaussians).

2022-05-23 09:01 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +
> but it might be that there are sampling methods that would require more fine-grained control or additional parameters passed to it

Yes, this is a good reason for putting the keyword arguments in the docstring.

2022-05-23 19:06 UTC, din14970 commented on orix/sampling/S2_sampling.py
> +
Ok. I think this is more or less resolved now.

2022-05-24 07:55 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +
I think it is too. Thank you!

2022-05-24 07:59 UTC, hakonanes commented
I'm very happy with this PR now. Is it OK if I make some minor changes to the functions references and add the additions to the changelog before approving?

2022-05-24 08:04 UTC, din14970 commented
@hakonanes yep, feel free!

2022-05-24 08:56 UTC, hakonanes approved these changes
I suggest to merge!

2022-05-24 10:46 UTC, harripj requested changes
Looks great to me! Just a few very small suggestions and a question.

2022-05-24 10:46 UTC, harripj commented on CHANGELOG.rst
> +- Seven methods for sampling unit vectors in spherical grids in *S2* via
I'm a bit confused by the nomenclature here, what is the meaning of "spherical grid"? Also I think this should be `on *S2*`, as S2 is 2d, but happy to be convinced otherwise.

2022-05-24 10:46 UTC, harripj commented on orix/sampling/_polyhedral_sampling.py
> +    """
```suggestion
    """Get array of first nearest neighbor points for all points in a point cloud

    Parameters
    ----------
    points
        Point cloud with shape (N, D) representing N points in D dimensions.
    leaf_size
        The NN search is performed using a cKDTree object. The way
        this tree is constructed depends on leaf_size, so this parameter
        will influence speed of tree construction and search.

    Returns
    -------
    nn1_vec
        Point cloud represented by an array of shape (N, D) with N points in
        D dimensions, representing the nearest neighbor point of each point
        in `points`.
    """
```

2022-05-24 10:46 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "Sampling unit vectors or directions in 3D space is equivalent to sampling points from the surface of the unit sphere ($S_2$).\n",
```suggestion
    "Sampling unit vectors or directions in 3D space is equivalent to sampling points on the surface of the unit sphere ($S_2$).\n",
```

2022-05-24 10:46 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "However, different meshes may be most appropriate for different point groups, as we illustrate below.\n",
```suggestion
    "However, different meshes may be more appropriate for different point groups, as we illustrate below.\n",
```

2022-05-24 10:46 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "For lower symmetry crystals, most samplings will be fine, and the icosahedral sampling may be recommended as points are most evenly spread.\n",
```suggestion
    "For lower symmetry crystals, most sampling methods are suitable, and icosahedral sampling is recommended as the points are most evenly spaced.\n",
```

2022-05-24 10:46 UTC, harripj commented on doc/s2_sampling.ipynb
> +    "Below we demonstrate a sampling of the fundamental zones for all 32 point groups."
```suggestion
    "Below we demonstrate sampling of the fundamental zone for all 32 point groups."
```

2022-05-24 18:40 UTC, harripj approved these changes
Looks great! Thanks @din14970 for your efforts porting this over. LGTM.

2022-05-24 18:40 UTC, merged