Add Pole density function (PDF) functionality
pyxem/orix pull request #340
Opened 2022-05-17 10:29 UTC by harripj

#### Description of the change
orix currently supports plotting poles (vectors) in the stereographic projection, however another useful crystallographic tool is the Pole Density Function (PDF). This representation allows the density of poles to be compared, which can be difficult when studying (overlapping) point data. This functionality was also requested in #320.

The PDF is calculated in angular space on S2 and uses (added) equal area sampling. This follows the work done by [Saylor et al.](http://www.hanser-elibrary.com/doi/abs/10.3139/146.017934) which is also added to the bibliography. The resulting PDF can be plotted on both hemispheres in units of Multiples of Random Density (MRD).

I have also added lazy `Vector3d-Vector3d` outer product, as I needed this at some point when working on this PR.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature

Fot the `Ti_orientation` data from `orix.data`:
```python
from orix.quaternion import Orientation
from orix.vector import Miller, Vector3d
from orix.crystal_map import Phase
from orix.quaternion.symmetry import D6

from orix.data import ti_orientations

ori = ti_orientations(allow_download=True)[::3]
m = Miller(uvw=(1, 0, 0), phase=Phase(point_group=D6)).symmetrise().unique()

poles_100 = (~ori).outer(m).flatten()[::10]
poles_100.scatter(s=2, axes_labels=['x', 'y', None], alpha=0.005, hemisphere='both')
```
<img width="354" alt="4ccfe8e4-bad6-47cd-bae9-60092e773109" src="https://user-images.githubusercontent.com/16853829/168790448-157a628e-a06b-4830-b987-801084532c94.png">

```python
poles_100.pdf(return_figure=True, colorbar=True, sigma=5, log=True, cmap='magma', resolution=5, hemisphere='both')
```
<img width="384" alt="bea9efd7-229a-4cc1-be18-76a76d049c89" src="https://user-images.githubusercontent.com/16853829/168790531-37f6f015-d53d-41bd-991d-670091125606.png">

And for random data:
```python
poles = Vector3d(np.random.randn(100_000, 3)).unit
poles.scatter(s=2, axes_labels=['x', 'y', None], alpha=0.01, hemisphere='both')
```

<img width="354" alt="7a9c590c-f07b-4659-a788-1638c94a7c70" src="https://user-images.githubusercontent.com/16853829/168790879-d75352b6-a2f8-484e-bbb3-8a611535c3bf.png">

```python
poles_100.pdf(return_figure=True, colorbar=True, sigma=5, log=False, cmap='magma', resolution=5, hemisphere='both')
```
<img width="390" alt="045c82b7-bc42-41b7-8505-3e48ea13245d" src="https://user-images.githubusercontent.com/16853829/168791070-7bcfdece-fba0-461d-b916-3ede17b9ee82.png">

In this last example you can see that the PDF is ~1 MRD, which is expected for random data.

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-05-17 11:50 UTC, harripj commented
I wasn't able to check the failing [test](https://github.com/pyxem/orix/runs/6469869427?check_suite_focus=true#step:8:86) on my machine, even after cleaning my environment and using the same matplotlib version. I have removed these minor checks.

The test checked that there was only one `collection` on each axes. On my machine this was correct, but perhaps I have an environment problem somewhere.

2022-05-17 11:54 UTC, harripj commented
Related to #338, `__annotations__` within the `future` package was only introduced in Python 3.7, hence the CI Python 3.6 build fails.

`__annotations__` are needed for type hints when a class operates with another instance of the class, for example: `Vector3d.outer(other: Vector3d)`. There is likely a lot of this in the code base, so introducing type hints while testing with Python 3.6 will cause problems.

2022-05-17 12:13 UTC, harripj commented
I can't replicate the [failing test](https://github.com/pyxem/orix/runs/6470207686?check_suite_focus=true#step:9:151) on my machine. If anybody else would have the time to pull this PR onto their machine, run the testing suite, and let me know the result I would be grateful!

2022-05-18 13:48 UTC, hakonanes requested changes
As far as I can tell, this is the first addition of *quantification* of orientations/vectors to orix, and thus a very important step forward!

Looking at the example you included in the top comment, I think we should reconsider #265 and whether we should add something like the following to generate the first figure in your example

```python
from orix import data
from orix.quaternion import Orientation, symmetry
from orix.vector import Miller
from orix.crystal_map import Phase


g = data.ti_orientations(allow_download=True)[::3]
m = Miller(uvw=(1, 0, 0), phase=Phase(point_group=symmetry.D6))
g.scatter("pf", direction=m, hemisphere="both")  # Pole figure
```

Other things:
 - [x] Changelog entry
 - [ ] Update API reference
 - [ ] User guide notebook(s), either a new one or adding to existing ones

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    azimuth, polar : ndarray
numpy.ndarray

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    if offset < 0 or offset > 1:
I find `not 0 < offset < 1` more readable.

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    azimuth, polar : ndarray
This is required other places as well.

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    # calculate number of steps and step size angular spacing, = D [1]
What does "= D [1]" refer to here?

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +        hemispheres. Default is "both".
Either the docstring or the default value must be updated here.

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    area spacing. Parameterization taken from :cite:`rohrer2004interfaces`.
I suggest to just write "area spacing :cite:\`rohrer2004interfaces\`.

2022-05-18 13:48 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +def sample_S2_equal_area_mesh(
Am I right in thinking that this will then be an alternative to the sampling options to be introduced by @din14970?

2022-05-18 13:48 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
> +        assert np.allclose(polar.min(), min_polar)
I suggest to use `==` to compare numbers here.

2022-05-18 13:48 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
> +    def test_equal_area_angle_coordinate_arrays(self, hemisphere, min_polar, max_polar):
I find "equal_area_angle" a bit confusing, could you just write "equal_area_coordinate_arrays"?

2022-05-18 13:48 UTC, hakonanes commented on orix/tests/test_vector3d.py
> +def test_pdf():
I suggest to add a new class for testing the PDF funtionality, so that potential future tests will be added in the correct place, and it will be easier to just run the PDF tests by running `pytest -k TestPDF`.

2022-05-18 13:48 UTC, hakonanes commented on orix/tests/test_vector3d.py
> +    assert len(fig1.axes) == 2
Some blank lines separating parts would be good here.

2022-05-18 13:48 UTC, hakonanes commented on orix/vector/vector3d.py
> +
Remove this blank line here, as both are imports from the standard library.

2022-05-18 13:48 UTC, hakonanes commented on orix/vector/vector3d.py
> +        [1]: The Distribution of Internal Interfaces in Polycrystals,
I suggest to add :cite:\`rohrer2004distribution\` at the end of the docstring's first sentence instead.

2022-05-18 13:48 UTC, hakonanes commented on doc/bibliography.bib
> +	doi = {10.3139/146.017934},
Also, the bibtex key should be "rohrer2004distribution" to be in line with the other entries in this file.

2022-05-18 13:48 UTC, hakonanes commented on orix/vector/vector3d.py
> +        if return_figure:
Blank line here.

2022-05-18 13:48 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def pdf(
I suggest to rename this to `pole_density_function()`: Yes, it takes longer to type, but I think PDF is a less familiar abbreviation than IPF, which is the only used abbreviation in orix currently. I'm open to other views.

2022-05-18 13:48 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def pdf(
And it cannot be confused with a probability density function or other things abbreviated PDF.

2022-05-18 13:56 UTC, harripj commented on orix/sampling/S2_sampling.py
> +from numpy.typing import NDArray
Good point, I will convert to explicit `np.ndarray`.

2022-05-18 14:37 UTC, harripj commented on orix/sampling/S2_sampling.py
> +    # calculate number of steps and step size angular spacing, = D [1]
From the cited Rohrer paper, but I agree it is not clear. I will update this

2022-05-18 15:36 UTC, harripj commented on doc/bibliography.bib
> +	doi = {10.3139/146.017934},
> Visiting https://doi.org/10.3139/146.017934 gets me nowhere, I suggest to add the URL instead.

Yes this is an interesting observation- it goes against what I thought the purpose of a DOI was! I have changed it for the (working) URL in any case.

2022-05-18 15:38 UTC, harripj commented on orix/sampling/S2_sampling.py
> +        hemispheres. Default is "both".
I have updated the `hemisphere` argument to have default value of `None`. In this case it is converted to `"both"` internally, but is more consistent with other API. Is this what you were thinking?

2022-05-18 17:38 UTC, harripj commented
> I can't replicate the [failing test](https://github.com/pyxem/orix/runs/6470207686?check_suite_focus=true#step:9:151) on my machine. If anybody else would have the time to pull this PR onto their machine, run the testing suite, and let me know the result I would be grateful!

Still not quite sure why there was a difference between running the same code in the same environment with `pytest` vs `ipython`. In any case the problem was that there were multiple collections in the axes when testing using `pytest` and on the CI. In any case the `--pdb` flag for `pytest` comes in handy!

2022-05-18 17:43 UTC, harripj commented
The failing build should be fixed after #347 is merged.

2022-05-18 18:19 UTC, hakonanes commented
Thank you for introducing `Orientation.plot()`, but I suggest to leave the (I)PF convenience methods for another PR. These methods will be very much used, so we should carefully consider the public facing functions and methods. I anticipate some discussion on the naming and parameter choices. We can also then focus on where the existing documentation can benefit from the added functionality.

2022-05-18 18:20 UTC, hakonanes commented
> we should carefully consider the public facing functions and methods

By this I mean it will be difficult to change later on since they will be much used.

2022-05-18 18:21 UTC, harripj commented
No problem, this is fine with me- I had thought your previous comment was a suggestion but I agree it is best to leave this for a later PR. I will remove these changes and we can consider this later.

2022-05-19 13:13 UTC, hakonanes commented
> I had thought your previous comment was a suggestion but I agree it is best to leave this for a later PR

Sorry, my bad, I should have stated that I ment in another PR...

2022-05-19 13:15 UTC, harripj commented
No problem! There is a commit [here](https://github.com/pyxem/orix/pull/340/commits/4f5888bce2f8fc3fc8c78a5a1d43593eeb6f73b5) that could potentially be used as a starting point for that discussion in another issue!

2022-05-19 13:34 UTC, harripj commented on orix/sampling/S2_sampling.py
> +        hemispheres. Default is "both".
This has been implemented.

2022-05-19 17:02 UTC, hakonanes commented
I don't think the notebook was added to git? We have to add the `-f` flag when we `git add` notebooks (see first point in the list in the [contributing guide](https://orix--340.org.readthedocs.build/en/340/contributing.html#build-and-write-documentation)).

2022-05-19 17:04 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +def sample_S2_equal_area_mesh(
Should we add as an alternative method in `orix.sampling.sample_S2` which will be introduced in #334?

2022-05-19 17:45 UTC, harripj commented
> I don't think the notebook was added to git? We have to add the -f flag when we git add notebooks (see first point in the list in the [contributing guide](https://orix--340.org.readthedocs.build/en/340/contributing.html#build-and-write-documentation)).

Well spotted yep! I saw a change to another notebook and assumed that was the one! Newly added now.

2022-05-19 17:47 UTC, harripj commented on orix/sampling/S2_sampling.py
> +def sample_S2_equal_area_mesh(
Yes, I think it is easiest if I reformat the sampling method here to fit in with the syntax in #334 after that PR gets merged.

2022-05-19 18:02 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +def sample_S2_equal_area_mesh(
Good idea, let's wait for that PR to be merged first (very close).

2022-05-20 07:50 UTC, hakonanes requested changes
I've gone over the notebook and have some suggestions.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "# Visualizing Crystal Poles in the Pole Density Function (PDF)\n",
I suggest to remove "(PDF)" so that the title fits on two lines in the sidebar, and rather introduce the abbreviation in the introductory cell.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "NB. if not previously downloaded this will download some example data from an online\n",
Might I suggest to use an info box (admonition) here instead? nbsphinx supports [warning and info boxes](https://nbsphinx.readthedocs.io/en/0.8.8/markdown-cells.html#Info/Warning-Boxes):

```markdown
<div class="alert alert-info">

Note

If not previously downloaded this will download some example data from an online
repository to a local cache, see the docstring of
[ti_orientations](reference.rst#orix.data.ti_orientations) for more details.

</div>
```

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "ori = ti_orientations(allow_download=True)\n",
I always load data in the cell *below* imports, since I often add to the imports as I build up a notebook and I don't want to reload the data every time I do this. I suggest to load the data in a new cell below.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "Let's look at the sample's $\\{011\\}$ texture plotted in the stereographic projection.\n",
Perhaps we should use {hkil} = {01-11} since the orientations describe unit cells of hexagonal symmetry? This is supported in the [Miller class](https://orix.readthedocs.io/en/stable/crystal_directions.html#Trigonal-and-hexagonal-index-conventions).

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "m = Miller(hkl=(0, 1, 1), phase=Phase(point_group=symmetry.D6))\n",
By using `ori.symmetry` here you can drop the import of `symmetry`. To show the user what `ori.symmetry` contains, we can print the `ori` representation after loading it above: this will show the size and symmetry in one line.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "m = m.symmetrise().unique()\n",
I suggest to pass `symmetrise(unique=True)` instead of the extra method call (see [docstring](https://orix.readthedocs.io/en/stable/reference.html#orix.vector.Miller.symmetrise)).

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "w, h = plt.rcParams['figure.figsize']\n",
Is it possible to set some Matplotlib parameters in the import cell to avoid some of these cosmetic calls, e.g. a default figure size suitable for this plot? This makes following the notebook simpler. We should work towards making the convenience methods handle as much as possible of this in the future, without loosing the existing customizability...

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "In this case we can use the [Vector3d.pole_density_function()](reference.rst#orix.vector.Vector3d.pole_density_function)\n",
This method must be listed in the [autosummary](https://github.com/pyxem/orix/blob/develop/doc/reference.rst#vector3d) of `Vector3d`.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "fig, ax = plt.subplots(ncols=2, figsize=(2 * h, h), subplot_kw=dict(projection='stereographic'))\n",
I suggest to split this into three lines so that we don't have to scroll horizontally to see the end.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "fig, ax = plt.subplots(ncols=2, figsize=(2 * h, h), subplot_kw=dict(projection='stereographic'))\n",
You should get the same figure by just doing `v_mesh.scatter(hemisphere="both", axes_labels=["x", "y"])`, right? Possibly return the figure and call `tight_layout()` on a second line.

2022-05-20 07:50 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "`cmap` parameter, and broadening of the density distrbution with `sigma`:"
distribution

2022-05-20 08:08 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "Let's look at the sample's $\\{011\\}$ texture plotted in the stereographic projection.\n",
Good idea.

2022-05-20 08:16 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "In this case we can use the [Vector3d.pole_density_function()](reference.rst#orix.vector.Vector3d.pole_density_function)\n",
Missed that- thanks!

2022-05-20 08:33 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "fig, ax = plt.subplots(ncols=2, figsize=(2 * h, h), subplot_kw=dict(projection='stereographic'))\n",
Yes, you're right. In fact I have updated this figure as I found it a bit redundant to show the sampling on both hemispheres. This has been updated with a 2-axes plot to show the the sampling in the stereographic projection and in 3D.

2022-05-20 08:45 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "w, h = plt.rcParams['figure.figsize']\n",
Good idea. I remembered that there was actually a `figure_kwargs` parameter for this purpose too.

2022-05-20 11:52 UTC, hakonanes reviewed
Two minor comments on aesthetics and some questions for the PDF calculation function.

2022-05-20 11:52 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "        \"font.size\": 20,\n",
Is a font size of 15 enough? Text overlap with figure with 20.

2022-05-20 11:52 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "unique $(01\\overline{1}1)$ poles: "
I think \bar{} is what you want, otherwise the negative index is lower than the others.

2022-05-20 11:52 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +    def pole_density_function(
This must be listed in the API reference and in the autosummary of StereographicPlot. Why don’t you accept azimuth and polar as keyword arguments here?

2022-05-20 11:52 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        args
Should be stated that these are in radians.

2022-05-20 11:52 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        hist = gaussian_filter(hist, sigma / resolution, mode=("wrap", "reflect"))
Is it useful to the user to have access to this histogram outside of this function? Say to compare the mean or max for different distributions, or to obtain the location of the max or n max? If yes, we should consider, probably in another PR, some separate module for this I think. orix.measure is an option, but might be too broad of a name…

2022-05-20 12:48 UTC, harripj commented on orix/plot/stereographic_plot.py
> +    def pole_density_function(
I was following the syntax of the other `StereographicPlot` methods, such as `scatter`, but you are right, there is no need as here we don't use the internal methods. I will replace with `azimuth` and `polar`.

2022-05-20 12:48 UTC, harripj commented on orix/plot/stereographic_plot.py
> +        args
Thanks!

2022-05-20 12:49 UTC, harripj commented on orix/plot/stereographic_plot.py
> +        hist = gaussian_filter(hist, sigma / resolution, mode=("wrap", "reflect"))
Yes, in fact this is accessible through `fig.axes[0].collections` and `get_array()`, but admittedly not that obvious. Perhaps your suggestion is the best and that this calculation becomes part of another module in the future, which returns the histogram and bin coordinates. This function would then simply call that function.

2022-05-20 12:50 UTC, harripj commented on orix/plot/stereographic_plot.py
> +        hist = gaussian_filter(hist, sigma / resolution, mode=("wrap", "reflect"))
I think `orix.measure` is a clear name, any quantification could go in there. Familiar to those who use `skimage` too.

2022-05-20 12:52 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "unique $(01\\overline{1}1)$ poles: "
Good spot, will update

2022-05-20 12:55 UTC, harripj commented on doc/pole_density_function.ipynb
> +    "        \"font.size\": 20,\n",
Looks good to me!

2022-05-23 11:09 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        hist = gaussian_filter(hist, sigma / resolution, mode=("wrap", "reflect"))
We can follow this up in #315.

2022-05-23 11:13 UTC, hakonanes commented
We agreed to wait for #334 to be merged, so that the equal area sampling added here becomes an alternative in the `sample_S2()` function to the unit vector samplings in that PR. From my point of view, this is the only outstanding task in this PR.

2022-05-25 17:40 UTC, harripj commented on orix/sampling/S2_sampling.py
> +def sample_S2_equal_area_mesh(
I have now added `"equal_area"` to the `_sampling_method_registry` introduced in #334, which I think fixes this issue.

2022-05-25 17:43 UTC, harripj commented
I have now merged `upstream/develop` into this PR and added the `equal_area_mesh` sampling method to the new sampling syntax introduced in #334. This PR is good for another look!

2022-05-27 09:56 UTC, hakonanes requested changes
Many minor suggestions, mostly of internal nature (syntax etc.). I suggest to merge after these are addressed.

2022-05-27 09:56 UTC, hakonanes commented on CHANGELOG.rst
> +- `Vector3d.pole_density_function()` has been implemented which allows for calculation
```suggestion
- ``Vector3d.pole_density_function()`` has been implemented which allows for calculation 
```

2022-05-27 09:56 UTC, hakonanes commented on doc/reference.rst
> +    pole_density_function
Could you add the corresponding method to the autosummary of `StereographicPlot` as well?

2022-05-27 09:56 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +            Azimuth and polar angles in radians.
```suggestion
            Azimuth and polar angles of the vectors in radians.
```

... or something similar.

2022-05-27 09:56 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +            If True a colorabar is shown alongside the PDF plot.
```suggestion
            If True a colorbar is shown alongside the PDF plot.
```

2022-05-27 09:56 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        from scipy.ndimage import gaussian_filter
I suggest to import `gaussian_filter` along with the other imports. As far as I remember, all imports within functions in orix are there to avoid circular imports.

2022-05-27 09:56 UTC, hakonanes commented on doc/pole_density_function.ipynb
> +    "v_mesh = sample_S2_equal_area_mesh(resolution=10)\n",
Now that `sample_S2(10, "equal_area")` is available, should this be used instead?

2022-05-27 09:56 UTC, hakonanes commented on doc/reference.rst
> +    pole_density_function
Also, could you add `sample_S2_equal_area_mesh` to the autosummary of the `sampling` module.

2022-05-27 09:56 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    Taken from diffsims.
I suggest to remove this note, now that @din14970 himself have ported the functionality.

2022-05-27 09:56 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
>              _ = S2_sampling.sample_S2_cube_mesh(2, "hexagonal")
This line is never reach, so we can remove it, right?

2022-05-27 09:56 UTC, hakonanes commented on orix/tests/test_vector3d.py
> +    assert "Completed" in out
Nice, did not know of this way to capture output!

2022-05-27 09:56 UTC, hakonanes commented on orix/tests/test_vector3d.py
> +        v = Vector3d(np.empty((0, 3)))
We have `Vector3d.empty()` for this.

2022-05-27 09:56 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def x(self, value: np.ndarray) -> None:
What is the benefit of `-> None`? If there is none, I suggest to drop giving this particular type hint for every method or function that doesn't return anything.

2022-05-27 09:56 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def _dot_outer_dask(self, other: Vector3d, chunk_size: int = 20) -> da.Array:
I suggest to move all private methods to the bottom of the class, even though it is used much further up. I find this cleaner. I'm open to other opinions, of course.

2022-05-27 09:56 UTC, hakonanes commented on orix/vector/vector3d.py
> +            If True a colorabar is shown alongside the PDF plot.
```suggestion
            If True a colorbar is shown alongside the PDF plot.
```

2022-05-27 09:56 UTC, hakonanes commented on orix/vector/vector3d.py
> +        """
Add a "See Also" section with `~orix.plot.StereographicPlot.plot_density_function`?

2022-05-27 09:56 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        matplotlib.axes.Axes.scatter
Add `orix.vector.Vector3d.plot_density_function`?

2022-05-27 10:24 UTC, harripj commented on orix/vector/vector3d.py
> +    def _dot_outer_dask(self, other: Vector3d, chunk_size: int = 20) -> da.Array:
No problem with this!

2022-05-27 10:27 UTC, harripj commented on orix/tests/test_vector3d.py
> +        v = Vector3d(np.empty((0, 3)))
Thanks!

2022-05-27 10:59 UTC, harripj commented on orix/tests/sampling/test_s2_sampling.py
>              _ = S2_sampling.sample_S2_cube_mesh(2, "hexagonal")
Yes, sorry, I think this was a merge error.

2022-05-27 11:19 UTC, harripj commented on orix/plot/stereographic_plot.py
> +    def pole_density_function(
In fact this has now been updated to allow `Vector3d` argument types also.

2022-05-27 11:41 UTC, harripj commented on orix/vector/vector3d.py
> +    def x(self, value: np.ndarray) -> None:
If we ever consider using type checking in the future, [mypy recommends that functions have a declared return type](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#the-any-type). I agree that this seems a bit excessive to be honest and from what I can see it is not so clear whether this also applies to setters.

As we are not using type checking currently, I will remove these `None` return types and we can cross that bridge if we come to it.

2022-05-27 12:06 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +            If True a colorabar is shown alongside the PDF plot.
For some reason this was mixed up? It still reads `colorabar`.

2022-05-27 12:07 UTC, harripj commented on orix/plot/stereographic_plot.py
> +            If True a colorabar is shown alongside the PDF plot.
Whoops, fixed now.

2022-05-27 12:11 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +            If True a colorabar is shown alongside the PDF plot.
Btw, not a big problem, but I prefer if the reviewer marks conversations as resolved rather than the submitter. This makes it a bit faster, at least for me, to look through the comments and check that they are adressed.

2022-05-27 12:12 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
>              _ = S2_sampling.sample_S2_cube_mesh(2, "hexagonal")
No problem, just one fewer lines to worry about :)

2022-05-27 12:14 UTC, harripj commented on orix/plot/stereographic_plot.py
> +            If True a colorabar is shown alongside the PDF plot.
Good point- I will keep this in mind in the future!

2022-05-27 12:16 UTC, hakonanes commented on orix/vector/vector3d.py
> +    def x(self, value: np.ndarray) -> None:
Type checking is indeed something to consider in the future. I've referenced this comment in the relevant issue.

2022-05-27 12:18 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        matplotlib.axes.Axes.scatter
This hasn't been added yet. Do you consider it unnecessary?

2022-05-27 12:25 UTC, harripj commented on orix/plot/stereographic_plot.py
> +        matplotlib.axes.Axes.scatter
I'm sorry about this- I had also committed this suggestion but perhaps this (and the mistake above) got lost when I was changing branches.

2022-05-27 12:36 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        matplotlib.axes.Axes.scatter
No problem!

2022-05-27 12:40 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +            )
Final suggestion here... `StereographicPlot._pretransform_input()` is used in most methods to parse the input arguments with this error message raised if they couldn't be parsed:

```python
                raise ValueError(
                    "Accepts only one (Vector3d) or two (azimuth, polar) input "
                    "arguments"
                )
```

I suggested to use that wording here as well, to be inline with the existing error message.

2022-05-27 13:01 UTC, hakonanes approved these changes
I'm very happy with this functionality, and will merge once the checks pass.

2022-05-27 13:04 UTC, merged