Add `plot_ipf_color_key()` to `InversePoleFigurePlot` 2
pyxem/orix pull request #361
Opened 2022-06-03 12:54 UTC by harripj

#### Description of the change
Duplicate of #354 after that PR was pre-maturely merged.

Previous PR information below
-------------------------------
As raised by @maclariz in #352.

At the moment it is difficult to display an IPF colour key on a custom figure, which would be very useful behaviour for users when presenting their data. In this PR the `IPFColorKeyTSL.plot()` code is refactored such that the same functionality can be called from `InversePoleFigurePlot` through a new `plot_ipf_color_key()` method.

This feature has also been discussed in #332.

EDIT
I have also converted the RGB IPF image to RGBA and made the invalid points, ie. points outside the FS, transparent. This allows for better custom plot overlays, see the 3rd example below.

NB. this is a continuation of #353 as I had messed up the commit history.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
# old behaviour
from orix.plot.orientation_color_keys import IPFColorKeyTSL
from orix.quaternion import symmetry, Orientation
from orix import plot
from orix.vector import Vector3d

ipfkey = IPFColorKeyTSL(symmetry=symmetry.Oh)
ipfkey.plot()
```
<img width="285" alt="de5d449c-8036-4c52-81b4-3c9bf2475b16" src="https://user-images.githubusercontent.com/16853829/169868824-b2cd3f32-b5f3-4ede-8110-b61d98564de9.png">

```python
# new behaviour from this PR
from matplotlib import pyplot as plt
fig, ax = plt.subplots(subplot_kw=dict(projection='stereographic'))
o = Orientation.random(10000)
c = ipfkey.orientation2color(o)
ax.scatter(o * Vector3d.zvector(), s=2, c=c)

ax2 = fig.add_axes([0.8, 0.8, 0.2, 0.2], projection='ipf', symmetry=symmetry.Oh)
ax2.plot_ipf_color_key()
```
<img width="340" alt="a54590b3-e275-4303-b99f-b33f00b088c8" src="https://user-images.githubusercontent.com/16853829/169868968-ce281dc3-33b0-46d5-a93c-0af246320176.png">

```python
from orix import data

xmap = data.sdss_ferrite_austenite(allow_download=True)
fig = xmap.plot(return_figure=True)

with plt.rc_context({'font.size': 6}):
    ax = fig.add_axes([0.23, 0.69, 0.15, 0.15], projection='ipf', symmetry=symmetry.Oh)
    ax.plot_ipf_color_key()
    ax.patch.set_facecolor('None')
```

<img width="289" alt="c1fe10a1-2615-4331-9522-9927c1d1467c" src="https://user-images.githubusercontent.com/16853829/170328164-2f6ec904-2abc-4260-985f-44301a478a38.png">

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-06-29 14:10 UTC, harripj commented
@hakonanes no problem! This was in response to @maclariz's comments raised in #352 and I have also found it useful for making my own custom plots. Perhaps the syntax could/should be adjusted somewhat, but we can discuss this once you have had a chance to look over it.

2022-07-04 13:28 UTC, hakonanes requested changes
This is a nice addition providing a convenient route to a quite common use case of plotting the IPF color key alongside a color map or pole figure.

I've made some suggestions, mostly for docstrings and the like.

Also, this PR addresses my points in https://github.com/pyxem/orix/issues/332#issuecomment-1125124631 nicely.

2022-07-04 13:28 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +    def plot_ipf_color_key(self) -> None:
I suggest to give the user the option to not show the title (Laue group) via `show_title=True`. The entire block starting with `label_xy =...` can be moved inside a `if show_title` block.

2022-07-04 13:28 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        self.imshow(rgba_grid, extent=(x_min, x_max, y_min, y_max), zorder=0)
Passing `extent=x_lim + y_lim` works, I suggest to remove the unpacking of the tuples above and just do that.

2022-07-04 13:28 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        """Plot an IPF color key code on this axis."""
I suggest to add a brief description below the first sentence description (with line break in between) of the intended use case of this function, i.e. to plot it alongside orientations or vectors colored with this key.

2022-07-04 13:28 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +    def plot_ipf_color_key(self) -> None:
I don't see the need for `None` here.

2022-07-04 13:28 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        """Plot an IPF color key code on this axis."""
Also, I suggest to allow passing any `font*` keyword argument allowed by `matplotlib.pyplot.text()` to format the title and axes labels with, like `fontsize`. This we can do like so

```python
from matplotlib.font_properties import FontProperties

kwargs = dict(fontsize=12, fontweight="bold")
fp_args = dict()
for key, value in kwargs.items():
    if key.startswith("font"):
        fp_args[key[4:]] = value
if len(fp_args) != 0:
    fp = FontProperties(**fp_args)
    if show_title:
        self.title.set_font_properties(fp)
    for text in self.texts:
        actual_text = text.get_text()
        if actual_text.startswith("[$") and actual_text.endswith("$]"):
            text.set_font_properties(fp)
```

If you agree with this, I can push this change to your branch.

2022-07-04 14:10 UTC, harripj commented on orix/plot/inverse_pole_figure_plot.py
> +    def plot_ipf_color_key(self) -> None:
This is just needed for type checking, which we discussed in [#338](https://github.com/pyxem/orix/issues/338).

For the moment, as type hinting is not applied everywhere in the codebase, this is not a problem. But if it gets introduced in the development phase, these return types would need to be added.

2022-07-04 14:15 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +    def plot_ipf_color_key(self) -> None:
OK, then you can leave it.

2022-07-04 14:40 UTC, harripj commented on orix/plot/inverse_pole_figure_plot.py
> +        """Plot an IPF color key code on this axis."""
My feeling is that this could be handled with a `plt.rc_context` context manager eg:
```python
with plt.rc_context({'font.size': 20, 'axes.titlecolor': 'w'}):
    # plotting code
```

which would save us handling specifics. And if the user wants to adjust specifics then they could work through the MPL API. This could be better demonstrated in a notebook. What do you think?

2022-07-04 16:15 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        :meth:`orix.vector.Vector3d` data.
```suggestion
        This function may be used to plot the IPF color key alongside
        another plot where the same key was used to color
        :class:`~orix.quaternion.Orientation` or
        :class:`~orix.vector.Vector3d` data.
```

2022-07-04 16:15 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +    def plot_ipf_color_key(self, show_title=True) -> None:
Can you add a "Parameters" section?

2022-07-04 16:15 UTC, hakonanes commented on doc/inverse_pole_figures.ipynb
> +    "An example demonstrating how an IPF color key can be added to a custom plot is shown in the [Crystal map notebook](crystal_map.ipynb#Plotting)."
I suggest to move this note up to after "Plot colour keys: Here we plot the colour keys for the eleven Laue groups. An example demonstrating...", because that's where I think users might want to look to do this, right?

2022-07-04 16:15 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        """Plot an IPF color key code on this axis."""
I agree in general and am OK with leaving this flexibility out of this PR.

I think setting the font size and possibly the weight will be the most desirable option for users of this method. I didn't see the suggested description of the `kwargs` parameter having to change in the future, so I figured this was quite an easy but stable flexibility to provide users. It's at least mentioned here so that we can come back to it in the future!

2022-07-04 16:16 UTC, hakonanes requested changes
I've got a couple of more comments, and then I'm happy with this PR and ready to merge!

2022-07-04 16:16 UTC, harripj commented on orix/plot/inverse_pole_figure_plot.py
> +        :meth:`orix.vector.Vector3d` data.
Thanks!

2022-07-04 16:26 UTC, harripj commented on doc/inverse_pole_figures.ipynb
> +    "An example demonstrating how an IPF color key can be added to a custom plot is shown in the [Crystal map notebook](crystal_map.ipynb#Plotting)."
Good idea!

2022-07-05 04:17 UTC, hakonanes approved these changes

2022-07-05 06:17 UTC, harripj commented
@hakonanes I just passed an eye over this and updated the `show_title` parameter docstring specifying the default value. At the same time tidied up other DS in related files. If you are happy with these changes, I am happy if this PR gets merged! 😄

2022-07-05 06:26 UTC, hakonanes commented
The other docstring changes are nice, thank you! Will merge once the checks pass.

The double back tick marks around e.g. \``True\`` is interpreted by Sphinx effectively as code, similar to Markdown's single back tick giving code on GitHub. I've started to use it, similar to NumPy, SciPy etc., to make interpreting docstrings a little faster. I think we should use this more in our docstrings, as you've done in the latest commit :+1:

2022-07-05 06:26 UTC, merged

2022-08-03 16:54 UTC, maclariz commented
Just out of interest, how soon until this is released in a full update of orix?  The box with the "official" version still has 0.9.0.post0 as the latest version.

2022-08-03 17:49 UTC, hakonanes commented
I'm OK with making a 0.10.0 release next week, as I quite like the pole density function functionality (used to great effect with a thin film dataset recently).

I have some improvements I'd like to make to the docs, separating it into examples (short recipies to common tasks) and tutorials (the existing user guides), like I've done with the [kikuchipy docs](https://kikuchipy.org/en/latest/#learning-resources).

I'll make an issue in preparation for 0.10.0.