Inverse pole density distribution 2
pyxem/orix pull request #362
Opened 2022-06-03 13:42 UTC by harripj

#### Description of the change
This is the new PR for #355 after that PR was pre-maturely merged.

Previous PR description below
-------------------------------
Following on from #340, it is often useful to view the pole density function (PDF) in the fundamental sector of the crystal symmetry, ie. the inverse pole density function (IPDF).

To implement this, the `StereographicPlot.pole_density_function()` has been updated to work with the subclass `InverseStereographicPlot`. When calculating PDF, the axes are checked as to whether they have a `_symmetry` attribute, ie. `IPF`, and if so the calculated `PDF` is folded back into the fundamental sector.

At the moment there are some issues with the implementation, regarding aliasing (during folding procedure) and the axes limits (which I may be due to `QuadMesh`, see plot size below), see the examples below. Grateful for any suggestions, feedback, or help regarding this!

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
from matplotlib import pyplot as plt
from orix import plot
from orix.quaternion import symmetry
from orix.vector import Vector3d

fig = plt.figure(figsize=(15, 5))

ax0 = fig.add_subplot(131, projection='stereographic')
ax1 = fig.add_subplot(132, projection='ipf', symmetry=symmetry.Oh)
ax2 = fig.add_subplot(133, projection='ipf', symmetry=symmetry.C6)

v = Vector3d([(-2, 0, 1), [2, 2, 1], [1, 1, 2], [0.5, -0.3, 0.2]]).unit

ax0.pole_density_function(v)
ax1.pole_density_function(v, resolution=0.25)
ax2.pole_density_function(v, resolution=0.25)
```
![image](https://user-images.githubusercontent.com/16853829/171866111-b009c2c5-e3a5-4902-b233-abfdc117e48e.png)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-06-17 10:58 UTC, hakonanes requested changes
This is a very nice PR with robust testing and neat reusing of one function to provide the inverse pole density function calculations to three classes `Vector3d`, `StereographicPlot` and `InverseStereographicPlot`.

Should the IPDF be used in a user guide tutorial (notebook)? That can be left for another PR, of course, but should perhaps be done before the next release.

I've made several suggestions for changes, mostly in the docstrings and slight changes to code. Otherwise, I think this is good to go.

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +            azimuth_coords[:-1] + np.ediff1d(azimuth_coords) / 2,
Why use `ediff1d` and not `diff`?

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +    # To help with aliasing after reprojection into FS in IPF case,
Could you write out "FS" and "IPF" in this comment, so that following use of the abbreviations is clear?

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +        # generate coorinates with proper resolution. When `symmetry`
```suggestion
        # generate coordinates with proper resolution. When `symmetry`
```

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +        # add hist data to new histogram by buffering
What do you mean "by buffering"? According to [the docstring](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html) this method applies an "unbuffered" in place `ufunc` operation?

2022-06-17 10:58 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        Parameters
Some blank lines here as well :)

2022-06-17 10:58 UTC, hakonanes commented on orix/plot/inverse_pole_figure_plot.py
> +        Parameters
And the reference to Rohrer et al. (2004)?

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +    Parameters
Copy+paste effect I assume, as I've seen this in my own editor (PyCharm) many a time...

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +                "Azimuth_range requires values (min, max) where min < max."
```suggestion
                "`azimuth_range` requires values (min, max) where min < max."
```

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    if azimuth_min < 0:
Just use `azimuth_min = min([azimuth_min, 0])` and similar for `azimuth_max`?

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    if azimuth_range is not None:
You can write `if azimuth_range is not None and azimuth_range[0] >= azimuth_range[1]:`, because if the first conditional is `False` it will immediately move on. But this *looks* safer, so you can leave it if you like (and then resolve this comment yourself).

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    if azimuth_min < 0:
Same for `polar_min/max`.

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +            raise ValueError('Hemisphere must be one of "upper", "lower", or "both".')
```suggestion
            raise ValueError("`hemisphere` must be one of 'upper', 'lower', or 'both'.")
```

2022-06-17 10:58 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
> +        with pytest.raises(ValueError, match="Azimuth_range requires values "):
If my previous change was accepted...

```suggestion
        with pytest.raises(ValueError, match="`azimuth_range` requires values "):
```

2022-06-17 10:58 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +            raise ValueError("Polar_range requires values (min, max) where min < max.")
```suggestion
            raise ValueError("`polar_range` requires values (min, max) where min < max.")
```

2022-06-17 10:58 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
> +        with pytest.raises(ValueError, match="Polar_range requires values "):
```suggestion
        with pytest.raises(ValueError, match="`polar_range` requires values "):
```

2022-06-17 10:58 UTC, hakonanes commented on orix/tests/sampling/test_s2_sampling.py
> +        with pytest.raises(ValueError, match="Hemisphere must be one of "):
```suggestion
        with pytest.raises(ValueError, match="`hemisphere` must be one of "):
```

2022-06-17 10:58 UTC, hakonanes commented on orix/tests/test_measure.py
> +        assert np.allclose(hist1.mean(), 1)
Will `hist1.mean()` always be within 1 to a tolerance of 10^-8 (the default) on all OS? If not, I suggest to restrict the tolerance a bit.

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +        raise ValueError("Azimuth and polar have 0 size.")
```suggestion
        raise ValueError("`azimuth` and `polar` angles have 0 size.")
```

2022-06-17 10:58 UTC, hakonanes commented on orix/tests/test_measure.py
> +        with pytest.raises(ValueError, match="Azimuth and polar have 0 size"):
If my change is accepted...

```suggestion
        with pytest.raises(ValueError, match="`azimuth` and `polar` angles have 0 size"):
```

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        """Plot the inverse Pole Density Function (IPDF) within the
```suggestion
        """Plot the Inverse Pole Density Function (IPDF) within the
```

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +            If True a colorbar is shown alongside the PDF plot.
```suggestion
            If True a colorbar is shown alongside the IPDF plot.
```

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +            `orix.quaternion.symmetry.C1` is used.
Just "*C1*" or "point group *1*"?

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        axes_labels
Does it make sense to provide this option? Aren't the axes labels always [uvw] corners of the fundamental sector?

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +            "None", which means "upper" if a new figure is created,
Either write None or `None`. I prefer "``None``" and "``"upper"``", so that Sphinx displays them as code and not just italic.

2022-06-17 10:58 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +    hemisphere
`hemisphere=None` is typically an option used in functions where a `figure` parameter is allowed, and where this is passed, the `hemisphere` parameter is ignored, which we signal to the user by having `None` as the default.

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        azimuth, polar, _ = self.to_polar()
Should these be made unit vectors before getting the polar angles?

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        projection
This is not an option in the method signature, and should be removed.

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        weights: Optional[np.ndarray] = None,
Then `projection` must be removed from the docstring.

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        projection
This docstring must now be updated to include "ipf" as an option, right?

2022-06-17 10:58 UTC, hakonanes commented on orix/vector/vector3d.py
> +        projection
This makes the `projection` parameter slightly inconsistent in naming, I think, but since the method is private, I guess that's OK. We need to take care not to provide this parameter with these two options in anything user facing!

2022-06-18 09:41 UTC, harripj commented on orix/tests/test_measure.py
> +        assert np.allclose(hist1.mean(), 1)
I haven't tested on all OS, but happy to ease the tolerance.

2022-06-18 10:26 UTC, harripj commented on orix/sampling/S2_sampling.py
> +    if azimuth_range is not None:
I will leave this as it is, if only because the traceback will be easier to follow.

2022-06-18 11:16 UTC, harripj commented on orix/vector/vector3d.py
> +        axes_labels
Good point, I will remove this.

2022-06-18 11:52 UTC, hakonanes commented on orix/sampling/S2_sampling.py
> +    if azimuth_range is not None:
The traceback is a good argument for leaving it!

2022-06-18 11:57 UTC, hakonanes commented
I've resolved all but one insignificant comment on comments... Feel free to ping me when you wan't a second review!

2022-06-18 12:20 UTC, harripj commented
> I've resolved all but one insignificant comment on comments... Feel free to ping me when you wan't a second review!

Thanks, I had missed a couple abbreviations in the inline comments- this should be good for a second look!

2022-06-18 12:40 UTC, hakonanes requested changes
Found a couple of things that should be changed, sorry for missing these in the first review.

2022-06-18 12:40 UTC, hakonanes commented on orix/measure/pole_density_function.py
> +from orix.projections.stereographic import StereographicProjection
```suggestion
from orix.projections import StereographicProjection
```

2022-06-18 12:40 UTC, hakonanes commented on CHANGELOG.rst
> +  ``InverseStereographicPlot.pole_density_function()``.
```suggestion
  ``InversePoleFigurePlot.pole_density_function()``.
```

2022-06-18 12:40 UTC, hakonanes commented on orix/plot/stereographic_plot.py
> +        stereographic projection.
```suggestion
        stereographic projection. See :cite:`rohrer2004distribution`.
```

2022-06-18 12:55 UTC, hakonanes approved these changes
This looks very good to me! Will let you merge once all checks pass and you're happy.

2022-06-21 07:44 UTC, harripj commented
Thanks for the review @hakonanes, I am happy with this. I will just wait to see if @pc494 has any comments on #351, as you commented, before merging.

2022-06-21 14:10 UTC, pc494 commented
Apologies for the delay. I think `measure` is a fine name for this sort of functionality. Feel free to merge @hakonanes

2022-06-21 14:58 UTC, merged