Ndim convert
pyxem/orix pull request #376
Opened 2022-08-18 18:32 UTC by argerlt

#### Description of the change

By default, Rotation objects can contain n-dimensional arrays of Rotation data. However, _conversions.py is written to only accept 2D arrays, since the functions use jit for acceleration. This adds wrappers to the jit functions to allow input and output of any dimensional array of Rotations.

Reasons for this:
1) This makes it possible to add to/from functions for Euler, Rodrigues, homochoric, cubochoric, and axis-angle functions into either Rotations or Quaternions. without losing the n-dimensional object support.
2) all the to/from functions will be able to use the jit-accelerated conversion functions copied directly from the Rowenhorst paper. 
3) Orix contains repeated to/from conversion functions, which adds some bloat and gives more room for errors. Wrapping these functions makes it easier to replace this repeated functionality with the jit-accelerated ones.

4)  This update makes it easier to take care of issues #374, #373, #346, #345, and #254

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [ ] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
The test cases verify the new functions produce identical results to the old 2d versions, but here is some code I used to verify this new code can, in fact, accept n-dimensional arrays of Rotations, and does not slow down the execution of the code by a meaningful amount.

``
import numpy as np
import time
from orix.quaternion._conversions import ro2ax, ro2ax2d

tocA = 0
tocB = 0
tocC = 0

# Run 10 times to get a good average
for i in np.arange(10):
    rod = np.random.rand(1000000, 4)

    # Convert Rod to axangle the old way using the original function
    tic = time.time()
    out_old = ro2ax2d(rod)
    toc = time.time() - tic
    tocA += toc

    # Do it using the new n-dimensional wrapper
    tic = time.time()
    out_new = ro2ax(rod)
    toc = time.time() - tic
    tocB += toc

    # verify they are identical
    assert np.all(out_new == out_old)

    # Do it using the new n-dimensional wrapper on a weird shaped dataset
    rod_weird = rod.reshape(2, 5, 10, 1, 100, 10, 10, 4)
    tic = time.time()
    out_weird = ro2ax(rod_weird).reshape(rod.shape)
    toc = time.time() - tic
    tocC += toc

    # verify they are identical
    assert np.all(out_old == out_weird)

# check out how long each method took
print("old way:{0:0.04f}".format(tocA))
print("new way:{0:0.04f}".format(tocB))
print("new way weird shape:{0:0.04f}".format(tocC))
``
Heres the output I got:
old way:6.9345
new way:6.9778
new way weird shape:6.9356

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-08-20 01:40 UTC, hakonanes commented
Thanks for this @argerlt! It is a nice generalization of existing functionality.

> By default, Rotation objects can contain n-dimensional arrays of Rotation data. However, _conversions.py is written to only accept 2D arrays, since the functions use jit for acceleration.

The conversions are private, not ment to be used by a user. But, with you mentioning them in #374 and opening this PR, I think it is time to make most of them public as methods to `Quaternion`. I suggest to leave this for another PR.

2022-08-20 02:10 UTC, hakonanes requested changes
Thanks for making these generalizations! Some comments on function naming and docstrings, mostly. Please say so if anything is unclear or you disagree with something.

2022-08-20 02:10 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +def eu2qu_single(eu):
The `Parameters` section must be updated.

2022-08-20 02:10 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
Is making these arrays necessary?

2022-08-20 02:10 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    """n-dimensional wrapper for eu2qu2d"""
```suggestion
    """N-dimensional wrapper for eu2qu_2d, see the docstring of that
    function.
    """
```

2022-08-20 02:10 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    """n-dimensional wrapper for ho2ax2d"""
```suggestion
    """N-dimensional wrapper for ho2ax_2d, see the docstring of that
    function.
    """
```

2022-08-20 02:10 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +        2D array of n (qo, q1, q2, q3) quaternions as 64-bit floats.
```suggestion
        2D array of n (q0, q1, q2, q3) quaternions as 64-bit floats.
```

2022-08-20 02:10 UTC, hakonanes commented on orix/tests/quaternion/test_conversions.py
> +        eulers = np.arange(1, 2.5, 0.05).reshape(10, 3)
I suggest to use either `euler` or `eulers` and not both in this test. Is there a reason for these particular values? If not, I suggest to create the angles in a simpler way, like `np.arange(30).reshape(10, 3) / 30`.

2022-08-20 02:19 UTC, argerlt commented on orix/quaternion/_conversions.py
> +def get_pyramid2d(xyz):
This occurred to me yesterday actually: would it be better to call these functions `get_pyramid_vector` or `get_pyramid_vectorized`? after all, they are 2D numpy arrays, but not 2D arrays of objects. calling them 2d might be confusing down the line.
Could also leave as-is, or change to some different suggested name.

2022-08-20 02:25 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +def get_pyramid2d(xyz):
I think the 2D naming is clear, as in the array has two dimensions. These functions will only be available in the public API via `Quaternion` methods anyway, where the shape agnostic version will be used.

2022-08-20 02:28 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    """n-dimensional wrapper for cu2ho2d"""
Follow up on this comment and the comments on all functions like it: 
I originally thought about copy/pasting the docstrings from `the _single` and `_2d` functions into the wrappers, but felt that doing so would result in docstrings repeated in triplicate, which felt unnecessary. I could either:

A) do exactly what you are suggesting here and be done
B) move the verbose docstring to the wrappers and write minimalized versions in the `_single` and `_2d` functions (would make the file shorter as a bonus), or
C) just be verbose and make all three functions have full sized docstrings, so help always gives all the info you need.

Thoughts?

2022-08-20 10:29 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    """n-dimensional wrapper for cu2ho2d"""
I'd go with (A). None of the functionality in `_conversions.py` is user facing (included in [the API reference](https://orix.readthedocs.io/en/stable/reference.html)), so we only need to supply docstrings for developers.

2022-08-20 10:30 UTC, hakonanes commented
@argerlt, do you intend to use these functions outside of orix? If so, we should include them in the API reference, and find a convenient way to import them.

2022-08-21 00:09 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
Yes, or at least something similar is.

Without these arrays, I was getting a problem where the right hand sides of lines 647-650 would produce float32 values that would then be inserted into a float64 array, resulting in incorrect values. This was a jit-only problem, because the .py_func versions of the functions execute correctly (float64 in, float64 out).

I tried several variations, which all gave the incorrect results:
```
qu[3] = -c * np.sin(sigma)
qu[3] = -c * np.sin(sigma, dtype = np.float64)
qu[3] = np.multiply(c, np.sin(sigma))
```
etc.
This FEELS weird and wrong, but it was the only method that worked which didn't involve adding extra variables, which seemed to slow down the computation.
If you or anyone else think of a more elegant solution, feel free to change it.

2022-08-21 00:14 UTC, argerlt commented on orix/tests/quaternion/test_conversions.py
> +        eulers = np.arange(1, 2.5, 0.05).reshape(10, 3)
I agree on both points.

2022-08-21 00:35 UTC, argerlt commented
> @argerlt, do you intend to use these functions outside of orix? If so, we should include them in the API reference, and find a convenient way to import them.

I didn't plan to. I personally cannot think of any situation where I would want to use these conversions where I wouldn't also just use the Orix Quaternion Class.  

Again, using scipy as a point of reference, I often have to go from active euler to Rodrigues-frank. When doing so, I never access those conversion directly. Instead, I just do:

```
from scipy.spatial.transform import Rotation as R
rod = R.from_euler('ZXZ',[euler_angles_here]).as_mrp()
```
Which I think is conceptually simple and keeps the API clean.

2022-08-22 17:48 UTC, argerlt commented
Alright, assuming you have no further feedback on line 647:
> ```[0] = np.array(c * np.cos(sigma), dtype=np.float64)```

I believe I have addressed all the required changes. let me know if that isn't the case

2022-08-22 17:52 UTC, hakonanes requested changes
I agree that a syntax like `Quaternion.from_euler(euler).to_matrix()`etc. is sufficient.

This shapes up rather nicely, thank you very much for addressing all my review comments! I've just got a few of them left.

Just as a heads-up: I prefer to resolve review comments myself, since this makes it easier to decided whether a change has been addressed.

2022-08-22 17:52 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +        1D array of 2hich pyramids ``xyz`` belong to as 64-bit integers.
```suggestion
        1D array of which pyramids ``xyz`` belong to as 64-bit integers.
```

2022-08-22 17:52 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +        1D array of (alpha, beta, gamma) Euler angles given in radians in the
Keep comments within 72 characters.

2022-08-22 17:52 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
Can you do `qu[0] = float(c * np.cos(sigma))`? If not, try `qu[0] = np.float64(c * np.cos(sigma))`.

2022-08-22 17:55 UTC, hakonanes commented on orix/tests/quaternion/test_conversions.py
> -        euler = np.array([1, 2, 3])
One line is not covered anymore (see [coveralls log](https://coveralls.io/builds/51847181/source?filename=orix%2Fquaternion%2F_conversions.py#L669)), I think we should include this rotation in this test.

2022-08-22 17:56 UTC, argerlt commented on orix/tests/quaternion/test_conversions.py
> -        euler = np.array([1, 2, 3])
I was confused why this popped up no but not before. Is this because I got rid of `euler` and replaced it with `eulers[0]`?

2022-08-22 18:09 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
np.float64 passes correctly

2022-08-22 18:25 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
actually, nevermind, np.float64 doesn't work either. I was loading an old __pycache__ file. I think np.array might be the easiest fix to this.

2022-08-22 18:52 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
OK, I'll have a look myself.

2022-08-22 19:26 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
Huh. Okay, this has be totally confused. 
For some reason, every variation of np.float64, float, etc, breaks. However, it ONLY breaks if the value it is inserting into qu is less than zero. 

I was going to suggest we just approve this and move on, but the underlying implication here is SOMEWHERE, things are getting cast incorrectly, possibly from float64 to float32 and then back, which would translate to a big loss in accuracy. 

I also tried explicitly using numpy multiply, divide, etc, like this:
```
    sigma = np.multiply(0.5, np.add(eu[0], eu[2]))
    delta = np.multiply(0.5, np.subtract(eu[0], eu[2]))
    c = np.cos(np.divide(eu[1], 2))
    s = np.sin(np.divide(eu[1], 2))
    nc = np.multiply(-1, c)
    ns = np.multiply(-1, s)

    qu = np.zeros(4, dtype=np.float64)
    qu[0] = np.multiply(c, np.cos(sigma))
    qu[1] = np.multiply(ns, np.cos(delta))
    qu[2] = np.multiply(ns, np.sin(delta))
    qu[3] = np.multiply(nc, np.sin(sigma))

    if qu[0] < 0:
        qu = -qu

```
but that failed as well.

2022-08-22 20:03 UTC, argerlt commented
Most recent push includes all the suggested formatting changes, plus a few I caught on reread.

I also realized that if any of the _conversion.py functions got passed data that wasn't float64, they would fail. Added lines to the wrapper functions to convert inputs to float64, as well as test cases that would pass float32 data to the checks, just to ensure this doesn't pop back up later. 

In reference to the eu2qu in _conversions.py, lines 657-671:
I honestly don't know what is happening here, but if I set atol=1e-40 in test_conversions.py, the test still succeeds, so it seems there is not loss of accuracy with this method, and also no loss of speed. I am ready to just accept this as a "it works and it's correct, so lets move on", but if you can figure out how to write it in a different way, feel free to change it directly.

2022-08-22 21:22 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
I agree that it's OK to leave as is and move on.

Out of curiosity, however, which OS and Python version are you testing with? All `pytest -k test_conversions` pass without any changes to the original code on my Ubuntu 22.04 with Python 3.9. Are you running other tests than the ones in `test_convers.py`? If so, we should similar tests to catch the behaviour you're describing.

2022-08-22 21:24 UTC, hakonanes commented
I'm including "Austin Gerlt" in `__credits__` in `orix/__init__.py`, and also in `.zenodo.json` with the following metadata:

```json
    {
      "name": "Austin Gerlt",
      "orcid": "0000-0002-2204-2055",
      "affiliation": "The Ohio State University"
    },
```

The ORCID is [here](https://orcid.org/0000-0002-2204-2055) and your affiliation I found [here](https://people.engineering.osu.edu/people/gerlt.1). If you're happy with this, I'll push these changes (and some minor formatting) to your branch before merging.

2022-08-23 05:46 UTC, argerlt commented
Yup, works for me. Change what you need.

2022-08-23 07:54 UTC, hakonanes commented
Sorry @argerlt, it seems I cannot push commits to your branch `ndim_convert`. Do you allow commits by maintainers, i.e. have the box at the bottom of the PR's right sidebar named "Allow edits and access to secrets by maintainers" ticked?

2022-08-23 15:51 UTC, hakonanes approved these changes
Thank you for contributing these nice generalizations, and for addressing all my review comments, @argerlt!

Merging when checks pass.

Could you briefly comment on https://github.com/pyxem/orix/pull/376/files#r951924756?

2022-08-23 16:07 UTC, merged

2022-08-23 16:12 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
I'm running on a Windows 10 computer with an AMD CPU. specifically from command prompt, When testing, I was running `pytest orix/tests/quaternion/test_conversions.py`

Since you brought this up, I tried it again, same code, same computer, but using Windows Subsystem for Linux (WSL) to run pytest. It passed without needing the np.array() additions! So, I assume this is a windows specific problem with numba and jit, which honestly, makes it even weirder.

2022-08-23 16:25 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    qu[0] = np.array(c * np.cos(sigma), dtype=np.float64)
Thank you for clarifying. I've encountered surprising effects with Numba in the past, similar to your experience here. This is just a reminder that we should not trust Numba blindly!