Moved to and from class methods from Rotation to Quaternion
pyxem/orix pull request #406
Opened 2022-10-21 22:51 UTC by anderscmathisen

#### Description of the change

Because of discussions in #401,  #345 and #373, it seemed like there is a need to move the `to_` and `from_` methods of `Rotation` to the `Quaternion` class. And so I have copy pasted them over.

I have changed little to nothing about the methods themselves, other than changing names of variables and updated docstrings. 

I did not move the `random_vonmises()` method as that would also require the `angle_with` method of `Rotation` class to be moved as well, and I was unsure whether that should be done or not. 

I included an override of `from_euler` in `Rotation` to keep the proper vs improper rotation that was present in that method as it was implemented in `Rotation`.

#### Progress of the PR
- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix.quaternion import Quaternion, Rotation
>>> import numpy as np
>>> euler = np.random.rand(10, 3)
>>> rot = Rotation.from_euler(euler)
>>> quat = Quaternion.from_euler(euler)
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2022-10-26 07:12 UTC, hakonanes requested changes
Thank you for setting this up @anderscmathisen!

I've made just a few suggestions for improvements, mostly to docstring wordings I or other people originally added...

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    def from_matrix(cls, matrix: np.ndarray) -> Quaternion:
```suggestion
    def from_matrix(cls, matrix: Union[np.ndarray, tuple, list]) -> Quaternion:
```

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        Parameters
We need a `Returns`!

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        quat = np.zeros(n + (4,))
We can replace this check with

```suggestion
        om = np.atleast_3d(matrix)
        quat = np.zeros(om.shape[:-2] + (4,))
```

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/rotation.py
> +    def identity(cls, shape: tuple = (1,)) -> Rotation:
Would be good to allow `shape` to be an integer as in `Quaternion.random()` (see above).

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/rotation.py
> +            The shape out of which to construct identity quaternions.
```suggestion
            The shape out of which to construct identity rotations.
```

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/rotation.py
> +    # TODO: Remove **kwargs, and use of "convention" in 1.0.
```suggestion
    # TODO: Remove **kwargs in 1.0.
```

2022-10-26 07:12 UTC, hakonanes commented on orix/quaternion/rotation.py
> +        n = euler.shape[:-1]
I suggest to just do `rot.improper = np.zeros(euler.shape[:-1])`.

2022-10-26 15:05 UTC, anderscmathisen commented on orix/quaternion/rotation.py
> +    def identity(cls, shape: tuple = (1,)) -> Rotation:
Agreed, I suggest we also move this function to the Quaternion class.

2022-10-27 06:47 UTC, hakonanes requested changes
Looks good. As I can see it's just one check in `Quaternion.identity()` missing, and we can merge this!

2022-10-27 06:47 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        data = np.zeros(shape + (4,))
If `shape` is a tuple this won't work, have to do the check as in `random()` above.

2022-10-29 18:24 UTC, hakonanes commented
We haven't considered that quaternions in orix are not by default unit quaternions, however rotations are unit quaternions. We ensure this by normalizing rotations upon initialization, while quaternions are not normalized.

The conversions we have implemented are based on the work by Rowenhorst et al. (2015) https://doi.org/10.1088/0965-0393/23/8/083501, where they in the abstract state that the transformations in that work including quaternions concern *unit* quaternions. Hence, I suggest that all new
1. `from_x()` methods return unit quaternions
2. `to_x()` methods normalize before returning `x`

I've already done this in my fork of your branch here, @anderscmathisen, among other changes like moving some rotation tests upstream to the quaternion test file. I suggest I make a PR to your branch, merge that, and then someone else has to review this PR since it includes my work...

2022-10-31 11:42 UTC, anderscmathisen commented
Yeah, I agree with your suggestions and nice that you have implemented them in a branch. 
Please let me know if I need to do anything.

2022-11-01 08:57 UTC, hakonanes commented
I can fix the conflits.

2022-11-01 09:07 UTC, hakonanes commented
Don't know if you've fixed lots of git conflicts @anderscmathisen, but what I did was basically (on the `move_to_from_methods` branch):

```bash
> git pull anderscmathisen move_to_from_methods  # Update my local fork of your branch
> git merge develop
Auto-merging CHANGELOG.rst
CONFLICT (content): Merge conflict in CHANGELOG.rst
Auto-merging orix/quaternion/quaternion.py
Auto-merging orix/quaternion/rotation.py
CONFLICT (content): Merge conflict in orix/quaternion/rotation.py
Auto-merging orix/tests/quaternion/test_rotation.py
CONFLICT (content): Merge conflict in orix/tests/quaternion/test_rotation.py
Automatic merge failed; fix conflicts and then commit the result.
```

Open the conflicting files and do the necessary changes, in this case remove the changes on `develop` and keep the ones on `move_to_from_methods`, then:

```bash
> git add .
> git commit -s
> git push anderscmathisen move_to_from_methods  # Update your branch
```

2022-11-01 09:20 UTC, hakonanes commented
I can add a small test covering the single line missing (https://coveralls.io/builds/53787279/source?filename=orix%2Fquaternion%2Frotation.py#L581).

2022-11-01 10:22 UTC, hakonanes commented
Fixed another conflict.

2022-11-30 13:30 UTC, pc494 approved these changes
Sorry for the delay all, I'm happy with this. Because it's been a little while since the request, I'm going to let @hakonanes merge just in case something else has happened since that I'm not aware of.

2022-11-30 17:01 UTC, merged