Adding Jit-accelerated to/from functions to quaternion class
pyxem/orix pull request #450
Opened 2023-05-05 23:13 UTC by argerlt

#### Description of the change
This is NOT a finished Pull request, just starting a request so we can have a discussion.

### Short version 
I reorganized `Quaternion` class and made it's "to/from" functionality consistently call from "_conversions.py"

### Long version
I started working on Issue #374 (Purpose for Neo-Eulerian Classes), but it's been 9 months since that issue was started, and since then Neo-Eulerian vectors have been used a lot more on the plotting side of things. As such, removing them is no longer a "quick and easy" code simplification, even if it did make sense.

However, the use of `NeoEuler` in `Quaternion` and all child classes of `Quaternion` was purely for to/from functionality, so I removed those and added jit-accelerated versions of those functions to `_conversions.py`

I also reorganized the functions of `Quaternion` into groups to make them easier to navigate. 

I also removed the `Quaternion.from_neo_euler` command with the thought of later removing the `NeoEuler` class altogether, but I would like someone more familiar with the use of `Rodriguez` and `AxAngle` to weight in before I go down that path. For now, I just replaced all the `Rotation.from_neo_euler(Axangle.from_axis_angle(axis,angle)' calls with the much simpler `Rotation.from_axis_angle(axis,angle)`

Next step would be to either continue removing `NeoEuler`, or to re-add `Quaternion.from_neo_euler` and it's test functions, and leave the rest alone for now.

#### Progress of the PR
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black via pre-commit](https://orix.readthedocs.io/en/latest/contributing.html#code-style)

#### Minimal example of the bug fix or new feature
```python
>>> from orix import vector
>>> v = vector.Vector3d([1, 1, 1])
>>> # Your new feature...
```

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the unreleased
      section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `__credits__` in `orix/__init__.py` and in
      `.zenodo.json`.

2023-05-21 17:18 UTC, hakonanes requested changes
Thank you for simplifying the conversions between quaternions and Neo-eulerian vectors (axis/angle pairs, Rodrigues vectors and homochoric vectors)! This will make people's workflows shorter and debugging faster.

I've made several comments, to both changes and styling. I anticipate another review after this, as there are some points for discussion.

Please let me know where I can assist.

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        assert om.ndim >= 2
`assert` is in orix only used in tests. In code we check and raise an appropriate error (a `ValueError` if the input does not have the required form as per the docstring) with an informative error message. Could you change these checks to this format? Again, you can require 2D by using `np.atleast_2d(om)`. Then we only need the second check, I think.

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +            an orix.vector.Vector3D object containing the axes of rotation,
```suggestion
            A :class:`Vector3d` containing the axes of rotation,
```

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        --------
Sphinx requires exact number of underlines and letters

```suggestion
        -----
```

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        Rodriguez vectors, all rotations map into a finite space, bounded by
```suggestion
        Rodrigues vectors, all rotations map into a finite space, bounded by
```

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        :cite:`rowenhorst2015consistent`.
```suggestion
        """Return the neo-Eulerian homochoric vector representation of
        the normalized quaternions :cite:`rowenhorst2015consistent`.
```

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        homo
```suggestion
        vec
```

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +            with lengths equal to [0.75*(angle-sin(angle))]^(1/3).
Good to have the maths in the docstring. I suggest to move it to the notes, though. And formatted with LaTeX, like

```
:math:`0.75\cdot(\theta - \sin(\theta))^{1/3}`
```

To render correctly, the docstring string needs to be a raw string, so we must add a `r"""Return the...`

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        :cite:`rowenhorst2015consistent`.
The same formatting suggestions for this method applies to `to_rodrigues()` as well.

2023-05-21 17:18 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    @property
Not sure about adding axis and angle of rotation to the quaternion class... I hope @pc494 can give his two cents on this change.

2023-05-21 17:18 UTC, hakonanes commented on orix/tests/quaternion/test_conversions.py
> +                [-0.95541973, -0.29525098, 0.0],
Do you need so many decimals? You only check four decimals in the tests, anyway. If possible, I suggest to reduce the number of decimals to those needed for the current checks.

2023-05-21 17:18 UTC, hakonanes commented on orix/tests/quaternion/test_orientation.py
> -        assert np.allclose(o1.symmetry.data, o2.symmetry.data)
Please keep these lines, as they confirm that initialization of the orientations are correct.

2023-06-02 18:48 UTC, argerlt commented on orix/tests/quaternion/test_conversions.py
> +                [-0.95541973, -0.29525098, 0.0],
On a related note, do you know what the source was for the rest of the pytest.fixture data in this file?
I thought I remembered finding a set of files from Rowenhorst/Rollett/Degraef at one point containing these values, but cannot seem to find it back now. If such a source did exist, it would be nice to add a related link and description.

2023-06-02 20:22 UTC, argerlt commented on orix/quaternion/quaternion.py
> +    @property
moving `.axis` and `.angle` to `Quaternion` made it easier to also move `.to_rodrigues` and `.to_axis_angle`, as well as eventually write their respective `from` statements. 

That said, I'm biased. This is really more about making it easier to change up the quaternion class structure, if we ever chose to do so. Down the road options such as :
   - Make symmetry a child of Quaternion, not Rotation
   - Creating a symmetry-aware Rotation class but restricting it to (C1,C1)
   - Misorientation and Orientation inheriting directly from either `Quaternion`, `Rotation`, or `_TAtion`
   -  Allowing things like `Symmetry.from_Rodrigues()`
  
Are all easier and cleaner if all the to/from functions as well as `.axis` and `.angle` are in `Quaternion`. 

Again, I am not saying we should commit to one of these now, I just want to reduce the mental bandwidth required to make any of these changes down the road.

2023-06-02 20:24 UTC, argerlt commented on orix/quaternion/quaternion.py
> +    ########################################
Do you have a good  alternative? I agree they don't match the rest of Orix, but a separator between groups of functions would still be nice for code navigation reasons. 

Could also just remove entirely though, I'm not committed to this, just thought it made it easier to find my place in the code.

2023-06-02 20:59 UTC, argerlt commented on orix/quaternion/quaternion.py
> +        Note, while this functionality has been added for completeness,
> less opinionated and more informative

You are not the first person to tell me to be less opinionated in my writing.



How about this? I want to make it clear Rodrigues vectors are useful, but this might still be to wordy/ opinionated>

        Rodrigues vectors are a useful rotation parameterization for certain
        applications ,especially visualization. However, their lengths scale
        with :math:\tan(\theta/2), as does their relative error.
        Additionally, rotations of 180 degrees are equivalent to infinitely
        long vectors. For these reasons, it might be better to use
        axis/angle paris instead, which have a defined values and
        consistent relative errors over all rotations.

2023-06-02 21:07 UTC, argerlt commented on orix/quaternion/quaternion.py
> +        if angles.shape == ():
This is a way better approach, thanks for suggesting it. 
I previously considered putting these checks as-is in `ax2qu`, but didn't want to make the functions in `_conversions.py` accept non-numpy inputs. Your suggestion is the better middle ground though.

2023-06-05 13:28 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +    @property
I agree with your choice here, having them as attributes of the quaternion class is fine.

2023-06-05 13:38 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        Note, while this functionality has been added for completeness,
> You are not the first person to tell me to be less opinionated in my writing.

Hah. We usually write code for our own use case, but when making it available in a library like orix, there might be users who need to use Rodrigues vectors and not axis/angle pairs for some reason we haven't thought of. Best to not alienate those people, I think.

I think your wording is good, just move the first comma and write "axis/angle pairs instead, which have defined values".

2023-06-05 13:46 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        ignore_warnings: bool = False,
Remember to remove the parameter and update the docstring.

Also, the code will not pass the warnings as they are "raised", not emitted. You should use `warnings.warn("message")` for that. I suggest slight rephrasing of the warnings:

1. Highest angle is greater than 179.999 degrees. Rodrigues vectors cannot paramtrize 2-fold rotations. Consider an alternative class method.
2. Max. estimated error is greater than 0.1%. Rodrigues vectors have increasing associated errors for small angle rotations. Consider an alternative class method.

These are good checks, btw, thanks for adding them!

2023-06-05 13:56 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +            a numpy array representing the angles of rotation
Users can deduce the types from the function signature.

```suggestion
        """Return an axis-angle representation of the normalized
        quaternions :cite:`rowenhorst2015consistent`.

        Returns
        -------
        axis
            The axes of rotation.
        angle
            The angles of rotation.
```

2023-06-05 14:00 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +            with lengths equal to :math:`\tan(angle/2)` .
```suggestion
        r"""Return the neo-Eulerian Rodrigues vector representation of the
        normalized quaternions :cite:`rowenhorst2015consistent`.

        Returns
        -------
        rod
            The axes of rotation, with lengths equal to
            :math:`\tan(angle/2)`.
```

2023-06-05 14:02 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +            :math:`0.75\cdot(\theta - \sin(\theta))^{1/3}` .
```suggestion
        r"""Return the neo-Eulerian homochoric vector representation of
        the normalized quaternions :cite:`rowenhorst2015consistent`.

        Returns
        -------
        vec
            The axes of rotation, with lengths equal to
            :math:`0.75\cdot(\theta - \sin(\theta))^{1/3}`.
```

2023-06-05 14:04 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        a sphere of radius pi.
```suggestion
        This is often used as a plotting tool, as it produces an
        isomorphic (though not angle-preserving) mapping from the
        non-euclidean orientation space into cartesian coordinates.
        Additionally, unlike Rodrigues vectors, all rotations map into a
        finite space, bounded by a sphere of radius :math:`\pi`.
```

2023-06-05 14:04 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        return homo
```suggestion
        vec = ax * magnitude
        return vec
```

2023-06-05 14:19 UTC, hakonanes commented on orix/tests/quaternion/test_conversions.py
> +                [-0.95541973, -0.29525098, 0.0],
I honestly cannot say. I added these tests in https://github.com/pyxem/orix/commit/477bf4ee33b1d08453f02f67e446625fbbe25d7e, but I don't give any attribution, which I should have done.

2023-06-05 15:54 UTC, argerlt commented on orix/quaternion/quaternion.py
> +    ########################################
I like this, it takes one line instead of three, but is still visible when quickly scrolling.

2023-06-05 16:46 UTC, argerlt commented on orix/quaternion/_conversions.py
> +    return qu
Actually, nevermind. i thought about this more and I think it should be normalized here. It's faster and more consistent with how the rest of `_conversions.py` operates.

Let me know if you disagree though and I can change it back, it's a quick 5 minute switch, and I still could go either way.

2023-06-08 08:47 UTC, hakonanes requested changes
Good stuff. Thank you for sorting out most of my comments. There are a few things still left to do in this PR, I've pointed out most of them. Also, some previous comments are still not resolved.

Could you run black version 23.1.0 on the files you've changed to ensure a consist code style? The changes that are needed are reported by our [CI from this PR](https://github.com/pyxem/orix/actions/runs/5182252624/jobs/9338822308?pr=450).

There are some uncovered lines (see the coverage step in our CI). How to write and run tests (also for Numba functions) and check coverage are described in our [contributing guide](https://orix.readthedocs.io/en/stable/dev/running_writing_tests.html). Please let me know if you need any help on this.

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +
```suggestion
```

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    ma
```suggestion
    om
```

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +    return qu
I agree, best to normalize here!

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +_PI = np.pi
Can you confirm a speed-up of caching pi here? I suspect it is over-optimization and that we don't gain much. I suggest to drop it.

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +_FLOAT_EPS = np.finfo(float).eps
It's safe to drop the underscore since this entire file is private.

2023-06-08 08:47 UTC, hakonanes commented on orix/quaternion/quaternion.py
> +        return self.axis, self.angle
Remember to account for `degrees`.

2023-06-08 08:47 UTC, hakonanes commented on orix/tests/quaternion/test_quaternion.py
> +# class TestFromAxesAngles:
Why are these commented out?

2023-06-27 21:22 UTC, argerlt commented on orix/quaternion/_conversions.py
> +_PI = np.pi
I'm not sure how to test it's speedup efficiently and I'm fine with dropping it. This was a holdover from a different project I was working on at the same time as ORIX with different preferences.

2023-06-27 21:25 UTC, argerlt commented on orix/quaternion/quaternion.py
> +        return self.axis, self.angle
good catch, thanks

2023-06-27 21:30 UTC, argerlt commented on orix/tests/quaternion/test_quaternion.py
> +# class TestFromAxesAngles:
This test used neo_euler, which originally I was intending to remove. That is no longer the case though, so no need to have it commented out.

2023-06-30 04:48 UTC, argerlt commented
Okay, I believe this Pull request is now done, barring any further reviewer feedback

There are a handful of things that could still be done
 - ` _conversions.ro2qu` and `_conversions.qu2ro`
 - fully replace `NeoEulerian` with equivalent to/from calls to quaternions
 - replace `Quaternion.axis` and `Quaternion.angle` shortcuts with jit-accelerated versions
 
 However, this PR has been open a very long time, and the above are not pressing matters. If anyone wants to add them, feel free, otherwise I am fine merging this and moving on for the time being.

2023-07-07 21:11 UTC, hakonanes commented on orix/quaternion/_conversions.py
> +_PI = np.pi
If I remember correctly, I've tested caching such variables in kikuchipy in some Numba accelerated functions, and found that caching has a minimal impact on speed.

2023-07-07 21:18 UTC, hakonanes commented
Thanks for again accomodating my review comments and suggestions, @argerlt. I agree that the PR is in good shape and that functionality is tested and documented. However, there are some style inconsistencies in both syntax and docstrings. Are you OK with me pushing some commits to your branch fixing these?

2023-07-07 21:35 UTC, argerlt commented
Sure thing, go ahead.

2023-07-14 17:44 UTC, hakonanes commented
I suggest we remove the `Quaternion.from_rodrigues_frank()` method and change `Quaternion.from_rodrigues()` either of these two ways:
1. Allow an optional `omega` parameter for scaling the axis (combined being the Rodrigues-Frank vector). If users have their 4-component vectors in one array, they have to split it to pass it in. Only a minor hassle, I'd say.
2. Allow `ro` to have either 3 (vector) or 4 (vector and scaling) as the final array dimension. Drawback could be that users mistake where the scaling should be (first or last).

@argerlt, what do you think?

I'm still going through the PR and making small adjustments here and there. I especially appreciate that you had a look at 3Drotations and have attempted to harmonize orix with output from this package.

2023-07-14 18:36 UTC, argerlt commented
I went back and forth on this issue a lot, and I do think you are right, creating `Quaternion.from_rodrigues_frank()' was the wrong solution. 

I like option one. It causes users inputting a 4-vector to make a conscious decision one way or another, which will probably help avoid errors, and its a method by which users who only know of the 3-vector version won't become unnecessarily confused.

I think option two might end up being a headache to implement, as there will be inevitable edge cases from accepting either a length 3 or 4 vector. 

That said, I think both would work fine.

2023-07-15 17:20 UTC, hakonanes commented
It seems to me like the fourth component in the Rodrigues-Frank vector accepted to `Quaternion.from_rodrigues_frank(ro)` (to be removed) is not the angle omega but the scaling factor tan(omega / 2). Is this correct?

2023-07-15 17:21 UTC, hakonanes commented
Yes, I see that you interpret omega as being the scaling factor in the docstring of that method. Good.

2023-11-05 19:29 UTC, hakonanes commented
@argerlt, if it's fine by you, I'll rebase on `develop` and fix the merge conflict. The docs should then pass.

2023-11-05 19:41 UTC, argerlt commented
Works for me. Thanks again, and sorry inlet this sit so long.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Håkon Wiik Ånes ***@***.***>
Sent: Sunday, November 5, 2023 2:29:24 PM
To: pyxem/orix ***@***.***>
Cc: Austin Gerlt ***@***.***>; Mention ***@***.***>
Subject: Re: [pyxem/orix] Adding Jit-accelerated to/from functions to quaternion class (PR #450)

@argerlt, if it's fine by you, I'll rebase on develop and fix the merge conflict. The docs should then pass. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message


@argerlt<https://urldefense.com/v3/__https://github.com/argerlt__;!!KGKeukY!2anSwBRnKThzJuWRmx3Fd3HCSUScqZZbGCY-Oyxb5ilBHN6nSZvxDg2pY_v-Sp_tAzTPLojtC4KAumkAdq6-eR2g$>, if it's fine by you, I'll rebase on develop and fix the merge conflict. The docs should then pass.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/pyxem/orix/pull/450*issuecomment-1793824369__;Iw!!KGKeukY!2anSwBRnKThzJuWRmx3Fd3HCSUScqZZbGCY-Oyxb5ilBHN6nSZvxDg2pY_v-Sp_tAzTPLojtC4KAumkAdiagKt-e$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ATZZWNJHQ4PL5POVQ32MGC3YC7SJJAVCNFSM6AAAAAAXXVWIA6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTHAZDIMZWHE__;!!KGKeukY!2anSwBRnKThzJuWRmx3Fd3HCSUScqZZbGCY-Oyxb5ilBHN6nSZvxDg2pY_v-Sp_tAzTPLojtC4KAumkAdjfARksB$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-06 08:10 UTC, hakonanes commented
No problem! I've been off development myself lately.

2023-11-07 22:36 UTC, argerlt commented
@hakonanes , code has been rebased and everything seems to be working as expected. let me know if there are any other changes you would like to see.

2023-11-08 13:19 UTC, hakonanes approved these changes
This looks good to me now. Thank you for your efforts, @argerlt!

The added from/to methods should make it simpler to work with neo-eulerian rotation representations in orix.

The new tests are also a great to have going forward!

2023-11-08 13:19 UTC, merged